import { CLAGame } from '@/types';

export const SEED_GAMES: CLAGame[] = [
  // ═══════════════════════════════════════════
  // GUARD - SEATED
  // ═══════════════════════════════════════════
  {
    id: 'seated-structure-connections',
    name: 'Structure & Connections',
    category: 'guard',
    subcategory: 'seated',
    startingPosition: 'Bottom player seated, top player standing in front',
    playerA: {
      label: 'Guard Player',
      objective: 'Maintain seated posture and create connections (grips) to the standing player',
      constraints: ['Must stay seated — no lying back', 'Only posts and frames allowed initially'],
    },
    playerB: {
      label: 'Passer',
      objective: 'Break all connections and get past the legs',
      constraints: ['Knees cannot touch the mat', 'Must stay standing'],
    },
    winConditions: {
      playerA: ['Maintain at least one connection for the full round', 'Get to a dominant grip (collar tie, 2-on-1, underhook)'],
      playerB: ['Break all grips and clear the legs', 'Get to chest-to-chest contact'],
    },
    scalingFocuses: {
      beginner: 'Focus on just maintaining any grip at all',
      intermediate: 'Upgrade grip quality — move from wrist to elbow to collar tie',
      advanced: 'Chain connections into off-balancing sequences',
    },
    coachingNotes: 'This is a foundational seated guard game. The constraint of standing vs seated creates the distance management problem naturally. Watch for guard players who slouch — posture is the first principle.',
    duration: 3,
    tags: ['seated guard', 'grips', 'connections', 'distance management', 'fundamentals'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'seated-causing-posts',
    name: 'Causing Posts',
    category: 'guard',
    subcategory: 'seated',
    startingPosition: 'Bottom player seated, top player standing',
    playerA: {
      label: 'Guard Player',
      objective: 'Force the passer to post their hands on the mat',
      constraints: ['Must stay seated', 'Use pulls and off-balancing, not sweeps'],
    },
    playerB: {
      label: 'Passer',
      objective: 'Stay balanced and upright without posting hands',
      constraints: ['Knees cannot touch the mat', 'Hands cannot touch the mat'],
    },
    winConditions: {
      playerA: ['Passer posts a hand on the mat', 'Passer falls to a knee'],
      playerB: ['Stay standing for the entire round without posting'],
    },
    scalingFocuses: {
      beginner: 'Any off-balance that causes a post counts',
      intermediate: 'Cause posts in a specific direction (forward vs lateral)',
      advanced: 'Chain off-balances — cause a post, then attack the reaction',
    },
    coachingNotes: 'Posts are pre-sweeps. If you can cause a post, you can cause a sweep. This game teaches guard players to manipulate balance without needing sweep mechanics.',
    duration: 2,
    tags: ['seated guard', 'off-balancing', 'sweeps', 'posts', 'balance'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'seated-connect-shoulders',
    name: 'Connect to the Shoulders',
    category: 'guard',
    subcategory: 'seated',
    startingPosition: 'Bottom player seated, top player standing at arms length',
    playerA: {
      label: 'Guard Player',
      objective: 'Get hands to the passer\'s shoulders or collar tie position',
      constraints: ['Must stay seated', 'Cannot grab legs or hips initially'],
    },
    playerB: {
      label: 'Passer',
      objective: 'Prevent any connection to your shoulders or head',
      constraints: ['Stay standing', 'Use hand-fighting only — no passing attempts'],
    },
    winConditions: {
      playerA: ['Achieve a collar tie or hands on both shoulders'],
      playerB: ['Keep guard player\'s hands below your chest for the round'],
    },
    duration: 2,
    tags: ['seated guard', 'collar tie', 'hand fighting', 'connections'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'seated-control-leg',
    name: 'Control A Leg',
    category: 'guard',
    subcategory: 'seated',
    startingPosition: 'Bottom player seated, top player standing',
    playerA: {
      label: 'Guard Player',
      objective: 'Capture and control one of the passer\'s legs using hooks, grips, or entanglements',
      constraints: ['Must stay seated or butterfly position', 'Must maintain leg control for 3 seconds to score'],
    },
    playerB: {
      label: 'Passer',
      objective: 'Keep both legs free and mobile',
      constraints: ['Stay standing', 'Cannot sprawl or go to the mat'],
    },
    winConditions: {
      playerA: ['Control a leg (ankle, knee, or thigh) for 3 seconds'],
      playerB: ['Keep both legs free for the entire round'],
    },
    scalingFocuses: {
      beginner: 'Any leg control counts — ankle grip, foot hook',
      intermediate: 'Achieve a specific entanglement (single leg X, ashi)',
      advanced: 'Control a leg and use it to sweep or enter a submission',
    },
    duration: 3,
    tags: ['seated guard', 'leg control', 'entanglements', 'single leg x', 'ashi garami'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'seated-destabilization',
    name: 'Destabilization',
    category: 'guard',
    subcategory: 'seated',
    startingPosition: 'Bottom player seated with hooks/grips, top player standing',
    playerA: {
      label: 'Guard Player',
      objective: 'Use hooks and grips to off-balance the passer and bring their hips to the mat',
      constraints: ['Must maintain seated or butterfly base', 'Use off-balancing, not explosive sweeps'],
    },
    playerB: {
      label: 'Passer',
      objective: 'Stay balanced and on feet despite guard player\'s attacks',
      constraints: ['Knees cannot touch the mat', 'No sprawling'],
    },
    winConditions: {
      playerA: ['Passer\'s hips touch the mat (sweep)', 'Passer goes to both knees'],
      playerB: ['Stay standing for the entire round'],
    },
    scalingFocuses: {
      beginner: 'Get any reaction — even a stumble counts as progress',
      intermediate: 'Sweep to a specific direction (forward, backward, lateral)',
      advanced: 'Sweep and immediately advance to a top position',
    },
    coachingNotes: 'This is the culmination of the seated guard progression: Structure → Connections → Posts → Destabilization. Each game built the skills needed for this one.',
    duration: 3,
    tags: ['seated guard', 'sweeps', 'off-balancing', 'butterfly', 'destabilization'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    progressionIds: ['seated-structure-connections', 'seated-causing-posts', 'seated-control-leg'],
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },

  // ═══════════════════════════════════════════
  // GUARD - HALF GUARD
  // ═══════════════════════════════════════════
  {
    id: 'half-guard-underhook',
    name: 'Underhook Control',
    category: 'guard',
    subcategory: 'half',
    startingPosition: 'Chest-to-chest half guard — bottom player has legs wrapped around top player\'s one leg',
    playerA: {
      label: 'Bottom Player',
      objective: 'Achieve and maintain an underhook on the trapped-leg side',
      constraints: ['Must keep half guard locked (legs wrapped)', 'Cannot go flat on back'],
    },
    playerB: {
      label: 'Top Player',
      objective: 'Deny the underhook and maintain chest-to-chest pressure',
      constraints: ['Must keep chest pressure', 'Cannot disengage to standing'],
    },
    winConditions: {
      playerA: ['Achieve underhook and maintain it for 3 seconds', 'Get to their side (hip escape to create angle)'],
      playerB: ['Maintain crossface/underhook denial for the round', 'Flatten bottom player onto their back'],
    },
    scalingFocuses: {
      beginner: 'Just get any underhook — timing and angles will come',
      intermediate: 'Get the underhook AND turn to your side',
      advanced: 'Use underhook to initiate a sweep or back take',
    },
    coachingNotes: 'The underhook battle is the defining feature of half guard. Greg Souders starts brand new students here because the chest-to-chest position naturally teaches pinning/escaping principles.',
    duration: 3,
    tags: ['half guard', 'underhook', 'chest-to-chest', 'framing', 'fundamentals'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'half-guard-hip-access',
    name: 'Hip Access',
    category: 'guard',
    subcategory: 'half',
    startingPosition: 'Half guard with top player chest-to-chest',
    playerA: {
      label: 'Bottom Player',
      objective: 'Create space between your hips and the top player\'s hips',
      constraints: ['Must keep half guard locked', 'Focus on hip movement, not upper body'],
    },
    playerB: {
      label: 'Top Player',
      objective: 'Keep hips heavy and connected to bottom player\'s hips',
      constraints: ['Must maintain hip-to-hip contact', 'No standing up'],
    },
    winConditions: {
      playerA: ['Create enough hip space to insert a knee shield', 'Hip escape to create an angle'],
      playerB: ['Maintain hip pressure for the full round'],
    },
    duration: 3,
    tags: ['half guard', 'hip movement', 'framing', 'knee shield', 'space creation'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'half-guard-knee-shield',
    name: 'Maintaining the Knee Shield',
    category: 'guard',
    subcategory: 'half',
    startingPosition: 'Bottom player in half guard with knee shield already inserted',
    playerA: {
      label: 'Bottom Player',
      objective: 'Keep the knee shield in place to maintain distance',
      constraints: ['Knee shield must stay between you and opponent', 'Cannot switch to closed guard'],
    },
    playerB: {
      label: 'Top Player',
      objective: 'Collapse the knee shield and re-establish chest-to-chest',
      constraints: ['Must pass through the knee shield, not around it', 'No standing passes'],
    },
    winConditions: {
      playerA: ['Maintain knee shield for the full round'],
      playerB: ['Collapse the knee shield and get chest-to-chest'],
    },
    duration: 3,
    tags: ['half guard', 'knee shield', 'distance management', 'framing'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'half-guard-ball-of-yarn',
    name: 'Ball of Yarn',
    category: 'guard',
    subcategory: 'half',
    startingPosition: 'Half guard — bottom player curled tight like a ball',
    playerA: {
      label: 'Bottom Player',
      objective: 'Stay curled tight — protect all spaces, deny every opening',
      constraints: ['Stay as compact as possible', 'Elbows in, chin tucked, knees to chest'],
    },
    playerB: {
      label: 'Top Player',
      objective: 'Unravel the bottom player — create openings in their defense',
      constraints: ['Must methodically create space', 'No explosive movements'],
    },
    winConditions: {
      playerA: ['Stay curled for the full round without giving up position'],
      playerB: ['Flatten bottom player or create enough space to pass'],
    },
    coachingNotes: 'This is a defensive survival game that teaches tightness and patience. The constraint of "no explosive movements" for top forces them to problem-solve methodically.',
    duration: 3,
    tags: ['half guard', 'defense', 'survival', 'tightness', 'patience'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },

  // ═══════════════════════════════════════════
  // GUARD - CLOSED GUARD
  // ═══════════════════════════════════════════
  {
    id: 'closed-guard-create-break',
    name: 'Create & Break Connections',
    category: 'guard',
    subcategory: 'closed',
    startingPosition: 'Closed guard — bottom player has legs locked around top player\'s waist',
    playerA: {
      label: 'Guard Player',
      objective: 'Create dominant connections (collar tie, overhook, cross grip) while breaking opponent\'s grips',
      constraints: ['Keep guard closed', 'Focus on grip fighting, not submissions'],
    },
    playerB: {
      label: 'Top Player',
      objective: 'Establish posture grips and break guard player\'s connections',
      constraints: ['Stay in the closed guard — no standing to open', 'Focus on posture and grip fighting'],
    },
    winConditions: {
      playerA: ['Achieve a dominant connection (2-on-1, overhook + collar tie)'],
      playerB: ['Establish both hands on hips/biceps with good posture'],
    },
    duration: 3,
    tags: ['closed guard', 'grip fighting', 'connections', 'posture'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'closed-guard-open-feet',
    name: 'Open the Feet',
    category: 'guard',
    subcategory: 'closed',
    startingPosition: 'Closed guard locked',
    playerA: {
      label: 'Guard Player',
      objective: 'Keep your feet locked behind the top player\'s back',
      constraints: ['No attacking — only maintain the lock', 'Must keep hips active'],
    },
    playerB: {
      label: 'Top Player',
      objective: 'Open the closed guard by unlocking the feet',
      constraints: ['Must stay on knees — no standing', 'No stacking or lifting'],
    },
    winConditions: {
      playerA: ['Keep guard locked for the full round'],
      playerB: ['Open the guard (unlock the feet)'],
    },
    scalingFocuses: {
      beginner: 'Top: focus on posture and wedging elbows',
      intermediate: 'Top: use hip pressure to create opening',
      advanced: 'Top can now stand to open — bottom must manage the transition',
    },
    duration: 3,
    tags: ['closed guard', 'guard opening', 'posture', 'hip pressure'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'closed-guard-climb-back',
    name: 'Climbing the Back',
    category: 'guard',
    subcategory: 'closed',
    startingPosition: 'Closed guard with guard player having a dominant overhook or collar tie',
    playerA: {
      label: 'Guard Player',
      objective: 'Use your connections to climb from closed guard to the back',
      constraints: ['Start from closed guard only', 'Must use hip escapes to angle off'],
    },
    playerB: {
      label: 'Top Player',
      objective: 'Maintain posture and prevent the guard player from getting to your back',
      constraints: ['Stay heavy and centered', 'No standing or disengaging'],
    },
    winConditions: {
      playerA: ['Get to the back with at least one hook in', 'Get a body triangle from behind'],
      playerB: ['Stay facing the guard player for the entire round'],
    },
    duration: 4,
    tags: ['closed guard', 'back take', 'climbing', 'hip escape', 'angle'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },

  // ═══════════════════════════════════════════
  // GUARD - OPEN GUARD
  // ═══════════════════════════════════════════
  {
    id: 'open-guard-maintain-connection',
    name: 'Maintain Connection',
    category: 'guard',
    subcategory: 'open',
    startingPosition: 'Open guard — bottom player supine, top player on knees or standing',
    playerA: {
      label: 'Guard Player',
      objective: 'Maintain at least one point of connection (foot, hand, hook) at all times',
      constraints: ['Must stay on your back or side', 'Cannot close the guard'],
    },
    playerB: {
      label: 'Passer',
      objective: 'Completely disconnect from the guard player (no contact)',
      constraints: ['Can move freely', 'Must fully disengage — partial passing doesn\'t count'],
    },
    winConditions: {
      playerA: ['Maintain connection for the entire round'],
      playerB: ['Achieve zero contact for 2 seconds'],
    },
    coachingNotes: 'This is the most fundamental open guard game. If you can\'t maintain connection, nothing else in open guard works. The feet are the primary connection tool.',
    duration: 3,
    tags: ['open guard', 'retention', 'connection', 'feet', 'fundamentals'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'open-guard-sweeping',
    name: 'Open Guard Sweeping',
    category: 'guard',
    subcategory: 'open',
    startingPosition: 'Open guard with guard player having feet on hips or hooks in',
    playerA: {
      label: 'Guard Player',
      objective: 'Sweep the passer — put their hips on the mat and come on top',
      constraints: ['Cannot stand up to wrestle', 'Must use guard mechanics (hooks, grips, leverage)'],
    },
    playerB: {
      label: 'Passer',
      objective: 'Stay on top and maintain base',
      constraints: ['Cannot disengage beyond arm\'s reach', 'Must actively engage the guard'],
    },
    winConditions: {
      playerA: ['Passer\'s hips touch the mat and guard player comes to top'],
      playerB: ['Stay on top for the full round'],
    },
    duration: 4,
    tags: ['open guard', 'sweeps', 'hooks', 'leverage', 'base'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'open-guard-entanglements',
    name: 'Entanglements',
    category: 'guard',
    subcategory: 'open',
    startingPosition: 'Open guard — bottom player looking to create leg entanglements',
    playerA: {
      label: 'Guard Player',
      objective: 'Create a leg entanglement (ashi garami, single leg X, X-guard, 50/50)',
      constraints: ['Must use feet and legs primarily', 'Start from open guard, not a pre-existing entanglement'],
    },
    playerB: {
      label: 'Passer',
      objective: 'Keep your legs free of any entanglement',
      constraints: ['Stay engaged — no running away', 'Can use any passing style'],
    },
    winConditions: {
      playerA: ['Achieve and hold an entanglement for 3 seconds'],
      playerB: ['Keep legs free for the entire round'],
    },
    scalingFocuses: {
      beginner: 'Any entanglement counts (single leg X, butterfly hooks)',
      intermediate: 'Specific entanglement — e.g., inside ashi garami only',
      advanced: 'Chain between entanglements as opponent escapes',
    },
    duration: 3,
    tags: ['open guard', 'leg entanglements', 'ashi garami', 'single leg x', 'x-guard', '50/50'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },

  // ═══════════════════════════════════════════
  // PASSING
  // ═══════════════════════════════════════════
  {
    id: 'passing-no-knees',
    name: 'No Knees Passing',
    category: 'passing',
    startingPosition: 'Standing passer vs seated or supine guard player',
    playerA: {
      label: 'Passer',
      objective: 'Pass the guard and achieve chest-to-chest or chest-to-back contact',
      constraints: ['Knees cannot touch the mat at any point', 'Must pass entirely from standing/squatting'],
    },
    playerB: {
      label: 'Guard Player',
      objective: 'Prevent the pass — sweep, stand up, or maintain guard',
      constraints: ['Start seated or supine', 'Can use any guard style'],
    },
    winConditions: {
      playerA: ['Achieve chest-to-chest pin for 3 seconds past the legs'],
      playerB: ['Sweep the passer or stand up to neutral'],
    },
    coachingNotes: 'The "no knees" constraint is one of Greg Souders\' signature game constraints. It forces the passer to use pressure from above rather than smash passing, and naturally develops toreando, leg drag, and body lock passing patterns.',
    duration: 4,
    tags: ['passing', 'standing', 'toreando', 'leg drag', 'pressure passing'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'passing-half-guard-knee-free',
    name: 'Free the Knee',
    category: 'passing',
    startingPosition: 'Chest-to-chest half guard — top player has one leg trapped',
    playerA: {
      label: 'Top Player',
      objective: 'Free your trapped knee and establish side control or mount',
      constraints: ['Must maintain chest pressure while freeing the knee', 'Cannot disengage to standing'],
    },
    playerB: {
      label: 'Bottom Player',
      objective: 'Keep the leg trapped and work toward an underhook or sweep',
      constraints: ['Must keep half guard locked', 'Cannot go to full guard'],
    },
    winConditions: {
      playerA: ['Free the trapped leg to either side (pass to side control or mount)'],
      playerB: ['Keep half guard locked for the full round', 'Achieve an underhook'],
    },
    coachingNotes: 'Greg Souders\' signature starting game for beginners. The half guard knee-free game naturally teaches the knee cut pass without ever naming it. Students self-organize around the task.',
    duration: 3,
    tags: ['passing', 'half guard', 'knee cut', 'pressure', 'fundamentals', 'beginners'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'passing-connect-and-pass',
    name: 'Connect & Pass',
    category: 'passing',
    startingPosition: 'Standing passer 3 feet from seated guard player',
    playerA: {
      label: 'Passer',
      objective: 'Close the distance, establish a connection, and pass the guard in sequence',
      constraints: ['Must establish a grip/connection before attempting to pass', 'No flying passes or jumping'],
    },
    playerB: {
      label: 'Guard Player',
      objective: 'Maintain guard and prevent the pass',
      constraints: ['Must stay seated initially', 'Can transition to any guard once contact is made'],
    },
    winConditions: {
      playerA: ['Pass to side control, mount, or back'],
      playerB: ['Sweep or stand to neutral'],
    },
    duration: 4,
    tags: ['passing', 'distance management', 'engagement', 'connection'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },

  // ═══════════════════════════════════════════
  // SIDE CONTROL
  // ═══════════════════════════════════════════
  {
    id: 'side-control-chest-pin',
    name: 'Chest-to-Chest Pin Control',
    category: 'side-control',
    startingPosition: 'Side control — top player chest-to-chest',
    playerA: {
      label: 'Top Player',
      objective: 'Maintain chest-to-chest contact and pin the bottom player flat',
      constraints: ['Must keep chest connected at all times', 'No submission attempts — pin only'],
    },
    playerB: {
      label: 'Bottom Player',
      objective: 'Create space and recover guard or escape',
      constraints: ['No bridging explosively — must use technical escapes', 'Must create frames before attempting to move'],
    },
    winConditions: {
      playerA: ['Maintain pin for the full round'],
      playerB: ['Recover any form of guard or get to knees'],
    },
    coachingNotes: 'Pinning is the foundation of top game. By removing submissions, the top player must focus entirely on the mechanics of maintaining pressure and connection.',
    duration: 3,
    tags: ['side control', 'pinning', 'pressure', 'escape', 'framing'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'side-control-submission-hunting',
    name: 'Submission Hunting from Side',
    category: 'side-control',
    startingPosition: 'Established side control',
    playerA: {
      label: 'Top Player',
      objective: 'Find and finish a submission from side control',
      constraints: ['Cannot transition to mount or back — must submit from side control variations', 'Must maintain top position'],
    },
    playerB: {
      label: 'Bottom Player',
      objective: 'Defend all submissions and escape',
      constraints: ['Focus on defensive posture — elbows tight, chin protected', 'Can escape to any position'],
    },
    winConditions: {
      playerA: ['Tap via submission'],
      playerB: ['Escape to guard or neutral'],
    },
    duration: 5,
    tags: ['side control', 'submissions', 'kimura', 'americana', 'arm triangle', 'north south'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'side-control-transition-mount',
    name: 'Transition to Mount',
    category: 'side-control',
    startingPosition: 'Side control — top player in standard crossface',
    playerA: {
      label: 'Top Player',
      objective: 'Transition from side control to mount',
      constraints: ['Must maintain a pin throughout the transition — no space', 'Cannot jump to mount — must slide'],
    },
    playerB: {
      label: 'Bottom Player',
      objective: 'Prevent the mount and recover guard',
      constraints: ['Must use frames and hip movement', 'Can escape to any position'],
    },
    winConditions: {
      playerA: ['Achieve mount with both knees on the mat and hips settled'],
      playerB: ['Prevent mount for the full round'],
    },
    duration: 3,
    tags: ['side control', 'mount', 'transition', 'pressure', 'hip movement'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'side-control-kesa-gatame',
    name: 'Establish Kesa Gatame',
    category: 'side-control',
    startingPosition: 'Standard side control crossface position',
    playerA: {
      label: 'Top Player',
      objective: 'Transition from standard side control to kesa gatame (scarf hold)',
      constraints: ['Must keep heavy hip pressure throughout', 'Smooth transition — no scrambling'],
    },
    playerB: {
      label: 'Bottom Player',
      objective: 'Prevent the transition to kesa and look for escapes during the movement',
      constraints: ['Focus on the moment of transition to create space'],
    },
    winConditions: {
      playerA: ['Establish kesa gatame and hold for 3 seconds'],
      playerB: ['Escape during the transition or prevent kesa entirely'],
    },
    duration: 3,
    tags: ['side control', 'kesa gatame', 'scarf hold', 'pins', 'transitions'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },

  // ═══════════════════════════════════════════
  // MOUNT
  // ═══════════════════════════════════════════
  {
    id: 'mount-wrist-pinning',
    name: 'Wrist Pinning & Trapping',
    category: 'mount',
    startingPosition: 'Mounted position — low mount',
    playerA: {
      label: 'Top Player',
      objective: 'Pin both of the bottom player\'s wrists to the mat simultaneously',
      constraints: ['Must use methodical control, not speed', 'Stay in mount — no transitioning'],
    },
    playerB: {
      label: 'Bottom Player',
      objective: 'Keep at least one hand free at all times',
      constraints: ['Stay on your back — focus on hand fighting', 'No bridging — just hand defense'],
    },
    winConditions: {
      playerA: ['Pin both wrists to the mat simultaneously for 2 seconds'],
      playerB: ['Never have both wrists pinned at the same time'],
    },
    coachingNotes: 'Wrist control from mount is the gateway to submissions. Once both wrists are pinned, every submission opens up. This game teaches the methodical approach to attacking from mount.',
    duration: 3,
    tags: ['mount', 'wrist control', 'pinning', 'arm isolation', 'submissions'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'mount-climb-high',
    name: 'Low to High Mount',
    category: 'mount',
    startingPosition: 'Low mount — top player\'s hips near bottom player\'s hips',
    playerA: {
      label: 'Top Player',
      objective: 'Climb from low mount to high mount (knees in armpits)',
      constraints: ['Must maintain the mount at all times — no dismounting to advance', 'Incremental climbing only'],
    },
    playerB: {
      label: 'Bottom Player',
      objective: 'Keep the top player in low mount or escape',
      constraints: ['Can bridge and hip escape', 'Must prevent the climb to high mount'],
    },
    winConditions: {
      playerA: ['Achieve high mount with knees in armpits'],
      playerB: ['Keep opponent in low mount or escape entirely'],
    },
    duration: 3,
    tags: ['mount', 'high mount', 'climbing', 'pressure', 'base'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'mount-shoulder-line',
    name: 'Transitioning to Shoulder Line',
    category: 'mount',
    startingPosition: 'High mount with good wrist control',
    playerA: {
      label: 'Top Player',
      objective: 'Transition from mounted position to shoulder line (S-mount or technical mount for arm attacks)',
      constraints: ['Must maintain dominant control throughout', 'Cannot lose the mount during transition'],
    },
    playerB: {
      label: 'Bottom Player',
      objective: 'Prevent the transition and escape mount',
      constraints: ['Can use any escape attempt', 'Must protect arms and posture'],
    },
    winConditions: {
      playerA: ['Achieve shoulder line position (one knee up, one foot posted)'],
      playerB: ['Escape mount or prevent shoulder line transition'],
    },
    duration: 4,
    tags: ['mount', 'shoulder line', 's-mount', 'technical mount', 'arm attacks'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },

  // ═══════════════════════════════════════════
  // BACK CONTROL
  // ═══════════════════════════════════════════
  {
    id: 'back-maintain-connection',
    name: 'Maintain & Break Connection',
    category: 'back-control',
    startingPosition: 'Back control with seatbelt grip — hooks in or body triangle',
    playerA: {
      label: 'Back Player',
      objective: 'Maintain back control — keep seatbelt and hooks/body triangle',
      constraints: ['No submission attempts — control only', 'Must keep chest-to-back contact'],
    },
    playerB: {
      label: 'Defending Player',
      objective: 'Escape back control and face your opponent',
      constraints: ['Must escape methodically — no explosive spins', 'Focus on controlling the hands first'],
    },
    winConditions: {
      playerA: ['Maintain back control for the full round'],
      playerB: ['Face opponent (get to guard) or stand up'],
    },
    coachingNotes: 'Back control is the highest-value position. This game isolates the maintenance/escape battle without the distraction of submissions. Both players learn the fundamental mechanics.',
    duration: 3,
    tags: ['back control', 'seatbelt', 'hooks', 'back escape', 'fundamentals'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'back-shoulder-hip-control',
    name: 'Shoulder & Hip Control',
    category: 'back-control',
    startingPosition: 'Back control — back player has seatbelt',
    playerA: {
      label: 'Back Player',
      objective: 'Control both the shoulders (seatbelt/harness) and hips (hooks/body triangle) simultaneously',
      constraints: ['Must have both hooks and seatbelt to score', 'Cannot substitute body triangle for hooks in this game'],
    },
    playerB: {
      label: 'Defending Player',
      objective: 'Remove at least one hook or break the seatbelt grip',
      constraints: ['Must address either top (seatbelt) or bottom (hooks) control', 'Can escape to any position'],
    },
    winConditions: {
      playerA: ['Maintain complete back control (seatbelt + both hooks) for 3 seconds'],
      playerB: ['Remove a hook or break the seatbelt'],
    },
    duration: 3,
    tags: ['back control', 'hooks', 'seatbelt', 'harness', 'control'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'back-submission-hunting',
    name: 'Back Submission Hunting',
    category: 'back-control',
    startingPosition: 'Back control with seatbelt and hooks',
    playerA: {
      label: 'Back Player',
      objective: 'Submit from back control',
      constraints: ['Must maintain back control — if you lose it, reset', 'Can attack any submission'],
    },
    playerB: {
      label: 'Defending Player',
      objective: 'Defend submissions and escape',
      constraints: ['Must actively defend — chin tucked, hands fighting', 'Can escape to any position'],
    },
    winConditions: {
      playerA: ['Tap via submission (RNC, collar choke, arm triangle from back)'],
      playerB: ['Escape to guard or neutral'],
    },
    duration: 5,
    tags: ['back control', 'submissions', 'RNC', 'rear naked choke', 'chokes'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },

  // ═══════════════════════════════════════════
  // TAKEDOWNS
  // ═══════════════════════════════════════════
  {
    id: 'takedown-single-connection',
    name: 'Single Leg: Connection & Movement',
    category: 'takedowns',
    startingPosition: 'Standing — both players in stance at arm\'s reach',
    playerA: {
      label: 'Attacker',
      objective: 'Achieve a single leg grip (any variation — head inside or outside)',
      constraints: ['Must set up the shot with a connection first (collar tie, wrist, post)', 'No double legs or body locks'],
    },
    playerB: {
      label: 'Defender',
      objective: 'Prevent the single leg entry',
      constraints: ['Must use footwork and hand-fighting to deny entry', 'No sprawling — stay upright'],
    },
    winConditions: {
      playerA: ['Achieve a single leg grip with head on the chest'],
      playerB: ['Prevent single leg entry for the full round'],
    },
    scalingFocuses: {
      beginner: 'Just get any single leg grip — head position doesn\'t matter yet',
      intermediate: 'Achieve head-inside single leg specifically',
      advanced: 'Set up the single leg off a snap-down or arm drag',
    },
    duration: 3,
    tags: ['takedowns', 'single leg', 'wrestling', 'shots', 'entries'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'takedown-single-finish',
    name: 'Single Leg: Destabilization & Finish',
    category: 'takedowns',
    startingPosition: 'Attacker already has single leg grip, head on chest',
    playerA: {
      label: 'Attacker',
      objective: 'Finish the single leg takedown — get opponent to the mat',
      constraints: ['Must keep the single leg grip', 'Cannot switch to double leg or body lock'],
    },
    playerB: {
      label: 'Defender',
      objective: 'Escape the single leg and return to neutral standing',
      constraints: ['Can hop, whizzer, crossface — anything to get free', 'Cannot pull guard'],
    },
    winConditions: {
      playerA: ['Opponent\'s back or hips touch the mat'],
      playerB: ['Free the leg and return to standing'],
    },
    progressionIds: ['takedown-single-connection'],
    duration: 3,
    tags: ['takedowns', 'single leg', 'finishes', 'wrestling'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'takedown-body-lock',
    name: 'Body Lock Takedown',
    category: 'takedowns',
    startingPosition: 'Standing clinch — no grips established yet',
    playerA: {
      label: 'Attacker',
      objective: 'Connect your hands around opponent\'s torso (body lock)',
      constraints: ['Must achieve a full body lock (hands connected around body)', 'No head-outside shots'],
    },
    playerB: {
      label: 'Defender',
      objective: 'Prevent the body lock and maintain separation',
      constraints: ['Use frames and underhooks to prevent connection', 'Must stay standing'],
    },
    winConditions: {
      playerA: ['Connect hands in a body lock'],
      playerB: ['Prevent body lock for the full round'],
    },
    duration: 3,
    tags: ['takedowns', 'body lock', 'clinch', 'wrestling', 'underhooks'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'takedown-knee-tag',
    name: 'Knee Tag',
    category: 'takedowns',
    startingPosition: 'Standing — both players in stance at arm\'s reach',
    playerA: {
      label: 'Player A',
      objective: 'Touch your opponent\'s knee (either knee) with your hand',
      constraints: ['Must touch below the knee — no grabbing', 'Return to stance after each touch'],
    },
    playerB: {
      label: 'Player B',
      objective: 'Protect your knees from being touched while touching opponent\'s',
      constraints: ['Same constraints — touch below the knee', 'Return to stance after each touch'],
    },
    winConditions: {
      playerA: ['Score more knee touches than opponent in the round'],
      playerB: ['Score more knee touches than opponent in the round'],
    },
    coachingNotes: 'Knee tag is a classic warmup game that develops the movement patterns needed for shots and shot defense. The level change and reach mirrors a wrestling shot without the contact.',
    duration: 2,
    tags: ['takedowns', 'warmup', 'movement', 'level change', 'shots', 'fun'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },

  // ═══════════════════════════════════════════
  // SUBMISSIONS
  // ═══════════════════════════════════════════
  {
    id: 'sub-rnc-finishing',
    name: 'RNC Finishing',
    category: 'submissions',
    subcategory: 'chokes',
    startingPosition: 'Back control with seatbelt grip and hooks in',
    playerA: {
      label: 'Attacker',
      objective: 'Finish the rear naked choke',
      constraints: ['Must maintain back control', 'Only RNC — no other submissions'],
    },
    playerB: {
      label: 'Defender',
      objective: 'Defend the choke and escape',
      constraints: ['Must protect the neck — chin tucked, hands fighting', 'Can escape to any position'],
    },
    winConditions: {
      playerA: ['Tap via RNC'],
      playerB: ['Escape back control'],
    },
    scalingFocuses: {
      beginner: 'Attacker: focus on getting the choking arm under the chin',
      intermediate: 'Attacker: get the full lock (hand behind head)',
      advanced: 'Finish the RNC even against good hand-fighting defense',
    },
    duration: 3,
    tags: ['submissions', 'RNC', 'rear naked choke', 'back control', 'chokes'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'sub-rnc-one-arm',
    name: 'One-Armed RNC',
    category: 'submissions',
    subcategory: 'chokes',
    startingPosition: 'Back control with hooks',
    playerA: {
      label: 'Attacker',
      objective: 'Get the choking arm under the chin using only one arm',
      constraints: ['One arm must stay as a seatbelt/harness at all times', 'Only the "free" arm can attack the neck'],
    },
    playerB: {
      label: 'Defender',
      objective: 'Protect your neck and escape',
      constraints: ['Standard defense — hands, chin, posture'],
    },
    winConditions: {
      playerA: ['Get the choking arm past the chin line'],
      playerB: ['Escape or defend for the full round'],
    },
    duration: 3,
    tags: ['submissions', 'RNC', 'one arm', 'back control', 'chokes'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'sub-guillotine-finishing',
    name: 'Guillotine Finishing',
    category: 'submissions',
    subcategory: 'chokes',
    startingPosition: 'Standing or guard — attacker has head and arm (or chin strap) guillotine grip',
    playerA: {
      label: 'Attacker',
      objective: 'Finish the guillotine choke',
      constraints: ['Must maintain the guillotine grip', 'Can pull guard or stay standing'],
    },
    playerB: {
      label: 'Defender',
      objective: 'Escape the guillotine before it\'s finished',
      constraints: ['Must escape the grip — can use any method', 'No tapping preemptively'],
    },
    winConditions: {
      playerA: ['Tap via guillotine'],
      playerB: ['Escape the grip and establish a position'],
    },
    duration: 3,
    tags: ['submissions', 'guillotine', 'front headlock', 'chokes', 'standing'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'sub-triangle-causing-posts',
    name: 'Triangle: Causing Posts',
    category: 'submissions',
    subcategory: 'chokes',
    startingPosition: 'Closed or open guard — guard player controlling posture',
    playerA: {
      label: 'Guard Player',
      objective: 'Force the top player to post a hand on the mat (creating the "arm in, arm out" configuration)',
      constraints: ['Must use guard control to create the post', 'Not looking for the triangle yet — just the post'],
    },
    playerB: {
      label: 'Top Player',
      objective: 'Keep both hands off the mat and maintain posture',
      constraints: ['Cannot post hands on the mat', 'Must keep hands in a defensive guard position'],
    },
    winConditions: {
      playerA: ['Force a hand post creating the arm-in/arm-out position'],
      playerB: ['Keep both hands engaged (not posting) for the full round'],
    },
    coachingNotes: 'This game teaches the setup for the triangle by creating the conditions where the triangle emerges naturally. The arm-in/arm-out position is the triangle entry.',
    duration: 3,
    tags: ['submissions', 'triangle', 'closed guard', 'posts', 'setup'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    progressionIds: ['sub-triangle-maintain-finish'],
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'sub-triangle-maintain-finish',
    name: 'Triangle: Maintaining the Finish',
    category: 'submissions',
    subcategory: 'chokes',
    startingPosition: 'Guard player has a triangle locked (legs around head and one arm)',
    playerA: {
      label: 'Guard Player',
      objective: 'Finish the triangle choke — squeeze and adjust angle',
      constraints: ['Triangle must stay locked — if it opens, reset', 'Focus on angle and squeeze, not upper body attacks'],
    },
    playerB: {
      label: 'Top Player',
      objective: 'Escape the triangle — stack, posture, or create space',
      constraints: ['Cannot slam', 'Must escape technically'],
    },
    winConditions: {
      playerA: ['Tap via triangle choke'],
      playerB: ['Escape the triangle (head comes out)'],
    },
    duration: 3,
    tags: ['submissions', 'triangle', 'finishing', 'chokes', 'guard'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'sub-armbar-maintain-finish',
    name: 'Armbar: Maintaining the Finish',
    category: 'submissions',
    subcategory: 'arm-attacks',
    startingPosition: 'Attacker has armbar locked — hips under the arm, legs over the body',
    playerA: {
      label: 'Attacker',
      objective: 'Finish the armbar — extend the arm against your hips',
      constraints: ['Must maintain the armbar position (hips under arm, legs squeezing)', 'If position is lost, reset'],
    },
    playerB: {
      label: 'Defender',
      objective: 'Escape the armbar — stack, hitchhiker, or grip-fight out',
      constraints: ['Must escape technically', 'Can use any armbar defense'],
    },
    winConditions: {
      playerA: ['Tap via armbar'],
      playerB: ['Escape the armbar and establish a position'],
    },
    duration: 3,
    tags: ['submissions', 'armbar', 'arm attacks', 'finishing'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'sub-armbar-grip-break',
    name: 'Armbar: Break Their Grip',
    category: 'submissions',
    subcategory: 'arm-attacks',
    startingPosition: 'Attacker in armbar position but defender is gripping hands together',
    playerA: {
      label: 'Attacker',
      objective: 'Break the defender\'s grip so you can extend the arm',
      constraints: ['Must maintain armbar position throughout', 'Use hip pressure and angles to break the grip'],
    },
    playerB: {
      label: 'Defender',
      objective: 'Keep your hands locked together and escape',
      constraints: ['Must maintain the grip — if it breaks, reset', 'Can try to escape but grip defense is priority'],
    },
    winConditions: {
      playerA: ['Break the grip and begin extending the arm'],
      playerB: ['Maintain the grip and escape the armbar'],
    },
    duration: 3,
    tags: ['submissions', 'armbar', 'grip breaking', 'arm attacks'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'sub-kimura-control',
    name: 'Kimura: Maintain Control',
    category: 'submissions',
    subcategory: 'arm-attacks',
    startingPosition: 'Attacker has a kimura grip from any position (side control, guard, north-south)',
    playerA: {
      label: 'Attacker',
      objective: 'Maintain the kimura grip and work toward finishing',
      constraints: ['Must keep the double wrist grip (figure-four)', 'Can transition positions while maintaining the grip'],
    },
    playerB: {
      label: 'Defender',
      objective: 'Break the kimura grip and escape',
      constraints: ['Must address the grip — straighten the arm or strip the grip', 'Can escape to any position'],
    },
    winConditions: {
      playerA: ['Maintain kimura grip for the full round', 'Finish the submission'],
      playerB: ['Break the grip and escape'],
    },
    duration: 3,
    tags: ['submissions', 'kimura', 'arm attacks', 'grip', 'control'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'sub-head-arm-stabilize',
    name: 'Head & Arm: Stabilize Front Headlock',
    category: 'submissions',
    subcategory: 'chokes',
    startingPosition: 'Standing or on knees — attacker has a front headlock (head and one arm)',
    playerA: {
      label: 'Attacker',
      objective: 'Maintain the front headlock position and control',
      constraints: ['Must keep head-and-arm grip', 'Focus on position, not submission yet'],
    },
    playerB: {
      label: 'Defender',
      objective: 'Escape the front headlock and return to neutral',
      constraints: ['Must get your head free', 'Can use any escape method'],
    },
    winConditions: {
      playerA: ['Maintain front headlock for the full round'],
      playerB: ['Free your head and return to neutral or take a dominant position'],
    },
    duration: 3,
    tags: ['submissions', 'front headlock', 'head and arm', 'guillotine', 'darce', 'anaconda'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'sub-darce-control',
    name: 'Darce: Maintain Control',
    category: 'submissions',
    subcategory: 'chokes',
    startingPosition: 'Attacker has darce grip (arm through the neck-armpit gap)',
    playerA: {
      label: 'Attacker',
      objective: 'Maintain the darce grip and work to finish',
      constraints: ['Must keep the darce lock — arm threaded through', 'Can adjust position to tighten'],
    },
    playerB: {
      label: 'Defender',
      objective: 'Remove the arm and escape before the choke finishes',
      constraints: ['Must free the trapped arm or create space', 'Can escape to any position'],
    },
    winConditions: {
      playerA: ['Finish the darce choke', 'Maintain the grip for the full round'],
      playerB: ['Free the arm and escape'],
    },
    duration: 3,
    tags: ['submissions', 'darce', 'chokes', 'arm-in', 'head and arm'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'sub-straight-ankle-capture',
    name: 'Straight Ankle Lock: Capture the Foot',
    category: 'submissions',
    subcategory: 'leg-locks',
    startingPosition: 'Open guard or ashi garami — attacker looking to isolate a foot',
    playerA: {
      label: 'Attacker',
      objective: 'Capture and isolate the foot for a straight ankle lock',
      constraints: ['Must achieve proper ankle lock grip (wrist blade on Achilles)', 'Must control the hips with your legs'],
    },
    playerB: {
      label: 'Defender',
      objective: 'Keep your feet free and extract your leg',
      constraints: ['Must free the foot — cannot just wait', 'Boot (flex foot) and work to escape'],
    },
    winConditions: {
      playerA: ['Achieve proper straight ankle lock grip with hip control'],
      playerB: ['Free the foot and pass or escape'],
    },
    duration: 3,
    tags: ['submissions', 'straight ankle lock', 'leg locks', 'ashi garami', 'foot'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'sub-cross-ashi-control',
    name: 'Cross Ashi: Maintaining Control',
    category: 'submissions',
    subcategory: 'leg-locks',
    startingPosition: 'Attacker in cross ashi garami (outside ashi) position',
    playerA: {
      label: 'Attacker',
      objective: 'Maintain cross ashi control and work toward a heel hook or knee bar',
      constraints: ['Must keep cross ashi configuration', 'Must control the hip line'],
    },
    playerB: {
      label: 'Defender',
      objective: 'Escape cross ashi — free your leg and come to top',
      constraints: ['Must address the leg entanglement', 'Can use boot, hip movement, or rotation to escape'],
    },
    winConditions: {
      playerA: ['Maintain cross ashi for the full round', 'Achieve a heel hook or knee bar grip'],
      playerB: ['Escape the entanglement and come to top position'],
    },
    duration: 3,
    tags: ['submissions', 'cross ashi', 'outside ashi', 'heel hook', 'leg locks', 'leg entanglements'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },

  // ═══════════════════════════════════════════
  // PINS
  // ═══════════════════════════════════════════
  {
    id: 'pin-chest-to-chest-back',
    name: 'Chest-to-Chest / Chest-to-Back',
    category: 'pins',
    startingPosition: 'Top player in any top position (side control, mount, or back)',
    playerA: {
      label: 'Top Player',
      objective: 'Maintain chest-to-chest or chest-to-back contact at all times',
      constraints: ['Chest must be in contact with opponent', 'If connection breaks, you lose the point'],
    },
    playerB: {
      label: 'Bottom Player',
      objective: 'Break the chest contact and create space',
      constraints: ['Must use frames, bridges, and hip escapes', 'No explosive movement — technique only'],
    },
    winConditions: {
      playerA: ['Maintain chest contact for the full round'],
      playerB: ['Break chest contact and maintain separation for 2 seconds'],
    },
    coachingNotes: 'This is the most fundamental pinning game. Everything in top game comes from the ability to maintain chest contact. Greg Souders links pinning and passing as "the same thing."',
    duration: 3,
    tags: ['pins', 'pressure', 'chest contact', 'fundamentals', 'top game'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'pin-covering-hips',
    name: 'Covering the Hips',
    category: 'pins',
    startingPosition: 'Top player in side control or north-south',
    playerA: {
      label: 'Top Player',
      objective: 'Keep your hips covering/blocking the bottom player\'s hips',
      constraints: ['Your hip must stay connected to their hip area', 'Cannot use arms as primary control — hips do the work'],
    },
    playerB: {
      label: 'Bottom Player',
      objective: 'Create space between your hips and the top player\'s weight',
      constraints: ['Must use hip escapes and frames', 'Cannot just bridge and roll'],
    },
    winConditions: {
      playerA: ['Maintain hip coverage for the full round'],
      playerB: ['Create hip space and begin recovering guard'],
    },
    duration: 3,
    tags: ['pins', 'hip control', 'pressure', 'side control', 'north south'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'pin-covering-shoulders',
    name: 'Covering the Shoulders',
    category: 'pins',
    startingPosition: 'Top player in side control with crossface',
    playerA: {
      label: 'Top Player',
      objective: 'Keep the bottom player\'s shoulders flat on the mat',
      constraints: ['Must use crossface and shoulder pressure', 'Focus on preventing any turning to the side'],
    },
    playerB: {
      label: 'Bottom Player',
      objective: 'Turn to your side (get off your back)',
      constraints: ['Must turn — even getting to a 45-degree angle counts as progress'],
    },
    winConditions: {
      playerA: ['Keep both shoulders flat for the full round'],
      playerB: ['Turn to your side and maintain it for 2 seconds'],
    },
    duration: 3,
    tags: ['pins', 'shoulder control', 'crossface', 'side control', 'framing'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },

  // ═══════════════════════════════════════════
  // TURTLE
  // ═══════════════════════════════════════════
  {
    id: 'turtle-attacking-arms',
    name: 'Attacking Turtle Arms',
    category: 'turtle',
    startingPosition: 'Bottom player in turtle (on all fours), top player beside or on top',
    playerA: {
      label: 'Top Player',
      objective: 'Isolate and control one of the turtle player\'s arms',
      constraints: ['Must work to expose an arm (wrist or elbow)', 'Cannot go directly to back — arm isolation first'],
    },
    playerB: {
      label: 'Turtle Player',
      objective: 'Keep both arms tucked tight and elbows connected to knees',
      constraints: ['Must stay in turtle — no sitting to guard', 'Keep elbows tight to body'],
    },
    winConditions: {
      playerA: ['Isolate an arm and control it for 3 seconds'],
      playerB: ['Keep both arms tucked for the full round'],
    },
    duration: 3,
    tags: ['turtle', 'arm isolation', 'top turtle', 'control'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'turtle-body-lock',
    name: 'Turtle Body Lock',
    category: 'turtle',
    startingPosition: 'Turtle player on all fours, top player behind',
    playerA: {
      label: 'Top Player',
      objective: 'Achieve a body lock around the turtle player\'s waist',
      constraints: ['Must connect your hands around their body', 'Approach from behind or the side'],
    },
    playerB: {
      label: 'Turtle Player',
      objective: 'Prevent the body lock and look to sit to guard or stand up',
      constraints: ['Must address the body lock attempt — can\'t just stay in turtle passively'],
    },
    winConditions: {
      playerA: ['Connect hands in a body lock around the waist'],
      playerB: ['Prevent the body lock and escape turtle'],
    },
    duration: 3,
    tags: ['turtle', 'body lock', 'back take', 'control'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'turtle-front-headlock-to-back',
    name: 'Front Headlock to the Back',
    category: 'turtle',
    startingPosition: 'Top player has a front headlock on a turtled opponent',
    playerA: {
      label: 'Top Player',
      objective: 'Transition from front headlock to back control',
      constraints: ['Must keep head control throughout the transition', 'Cannot just jump to the back — must circle methodically'],
    },
    playerB: {
      label: 'Turtle Player',
      objective: 'Escape the front headlock — sit out, stand up, or recover guard',
      constraints: ['Must escape before opponent gets to back', 'Can use any turtle escape'],
    },
    winConditions: {
      playerA: ['Achieve back control with at least a seatbelt grip'],
      playerB: ['Escape the front headlock to any non-turtle position'],
    },
    duration: 3,
    tags: ['turtle', 'front headlock', 'back take', 'transitions'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },

  // ═══════════════════════════════════════════
  // SCRAMBLES
  // ═══════════════════════════════════════════
  {
    id: 'scramble-ankle-wars',
    name: 'Ankle Wars',
    category: 'scrambles',
    startingPosition: 'Both players on their knees, facing each other',
    playerA: {
      label: 'Player A',
      objective: 'Grab and control your opponent\'s ankle',
      constraints: ['Must stay on knees — no standing', 'Can only grab ankles, not legs above the ankle'],
    },
    playerB: {
      label: 'Player B',
      objective: 'Grab and control your opponent\'s ankle while defending yours',
      constraints: ['Same constraints — knees only, ankles only'],
    },
    winConditions: {
      playerA: ['Control opponent\'s ankle and use it to off-balance them'],
      playerB: ['Control opponent\'s ankle and use it to off-balance them'],
    },
    coachingNotes: 'A fun warmup game that builds reflexes, scrambling ability, and spatial awareness. Great for beginning of class.',
    duration: 2,
    tags: ['scrambles', 'warmup', 'fun', 'movement', 'balance', 'reflexes'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'scramble-back-to-back',
    name: 'Back-to-Back Spin Up',
    category: 'scrambles',
    startingPosition: 'Both players seated back-to-back',
    playerA: {
      label: 'Player A',
      objective: 'Spin around and get to your opponent\'s back (chest to their back)',
      constraints: ['Start from seated back-to-back', 'Cannot stand up — must spin on the mat'],
    },
    playerB: {
      label: 'Player B',
      objective: 'Spin around and get to your opponent\'s back first',
      constraints: ['Same constraints — seated, mat-level spinning'],
    },
    winConditions: {
      playerA: ['Get chest to opponent\'s back first'],
      playerB: ['Get chest to opponent\'s back first'],
    },
    coachingNotes: 'Great warmup and scramble game. Develops hip movement, spatial awareness, and the ability to race for back control.',
    duration: 2,
    tags: ['scrambles', 'warmup', 'back take', 'movement', 'fun', 'hip movement'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'scramble-no-knees-top',
    name: 'No Knees Top Player',
    category: 'scrambles',
    startingPosition: 'Guard player seated/supine, top player standing',
    playerA: {
      label: 'Top Player',
      objective: 'Pass, pin, or submit — but never let your knees touch the mat',
      constraints: ['Knees cannot touch the mat at any point', 'Must stay on feet/squat only'],
    },
    playerB: {
      label: 'Guard Player',
      objective: 'Sweep, submit, or stand up',
      constraints: ['Can use any guard or technique', 'Full freedom to move'],
    },
    winConditions: {
      playerA: ['Pass and establish a pin or submit — all without kneeling'],
      playerB: ['Sweep (top player\'s hips to mat), submit, or stand to neutral'],
    },
    coachingNotes: 'This is a signature Greg Souders constraint. By preventing kneeling, the top player must develop standing passing, floating, and top pressure from unusual angles.',
    duration: 5,
    tags: ['scrambles', 'passing', 'standing', 'constraint', 'movement'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },

  // ═══════════════════════════════════════════
  // STRIKING INTEGRATION (tag games)
  // ═══════════════════════════════════════════
  {
    id: 'striking-belly-tag',
    name: 'Belly Tag',
    category: 'scrambles',
    startingPosition: 'Both players standing in fighting stance',
    playerA: {
      label: 'Player A',
      objective: 'Touch your opponent\'s belly with an open hand',
      constraints: ['Open hand touch only — no striking', 'Must return to stance after each touch'],
    },
    playerB: {
      label: 'Player B',
      objective: 'Touch your opponent\'s belly while defending yours',
      constraints: ['Same constraints — open hand, return to stance'],
    },
    winConditions: {
      playerA: ['Score more belly touches in the round'],
      playerB: ['Score more belly touches in the round'],
    },
    coachingNotes: 'Belly tag develops distance management, timing, and defensive awareness in a safe, fun format. Use as a warmup or between heavy rounds.',
    duration: 2,
    tags: ['scrambles', 'warmup', 'striking', 'distance', 'timing', 'fun', 'MMA'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'striking-belly-forehead-tag',
    name: 'Belly & Forehead Tag',
    category: 'scrambles',
    startingPosition: 'Both players standing in fighting stance',
    playerA: {
      label: 'Player A',
      objective: 'Touch opponent\'s belly OR forehead with open hand',
      constraints: ['Light touch only', 'Must alternate between belly and forehead targets'],
    },
    playerB: {
      label: 'Player B',
      objective: 'Same — touch belly or forehead while defending',
      constraints: ['Same constraints'],
    },
    winConditions: {
      playerA: ['Score more touches overall'],
      playerB: ['Score more touches overall'],
    },
    coachingNotes: 'Adding the forehead as a target forces level-change awareness and simulates the high-low attack problem in striking.',
    duration: 2,
    tags: ['scrambles', 'warmup', 'striking', 'level change', 'timing', 'fun', 'MMA'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },

  // ═══════════════════════════════════════════
  // KNEE ON BELLY
  // ═══════════════════════════════════════════
  {
    id: 'kob-no-hands',
    name: 'Knee on Belly: No Hands',
    category: 'side-control',
    startingPosition: 'Top player in knee on belly position',
    playerA: {
      label: 'Top Player',
      objective: 'Maintain knee on belly without using your hands for balance',
      constraints: ['Hands behind your back or on your own hips', 'Must keep knee on belly using balance only'],
    },
    playerB: {
      label: 'Bottom Player',
      objective: 'Escape knee on belly',
      constraints: ['Can use any escape method', 'Full freedom of movement'],
    },
    winConditions: {
      playerA: ['Maintain knee on belly for the full round without hands'],
      playerB: ['Escape to guard, turtle, or standing'],
    },
    coachingNotes: 'Removing the hands forces the top player to develop incredible balance and sensitivity. This constraint dramatically accelerates KOB skill development.',
    duration: 2,
    tags: ['knee on belly', 'balance', 'pressure', 'constraint', 'sensitivity'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
  {
    id: 'kob-maintain',
    name: 'Knee on Belly: Maintain Position',
    category: 'side-control',
    startingPosition: 'Top player establishing knee on belly from side control',
    playerA: {
      label: 'Top Player',
      objective: 'Establish and maintain knee on belly — ride the movement',
      constraints: ['Must keep knee pressure on the belly or chest', 'Can use grips on collar/belt area'],
    },
    playerB: {
      label: 'Bottom Player',
      objective: 'Remove the knee and escape to a better position',
      constraints: ['Must address the knee — push, hip escape, or turn into it'],
    },
    winConditions: {
      playerA: ['Maintain KOB for the full round'],
      playerB: ['Remove the knee and recover guard or stand'],
    },
    duration: 3,
    tags: ['knee on belly', 'pressure', 'control', 'escape'],
    source: 'Greg Souders / Standard Jiu-Jitsu',
    createdBy: 'system',
    createdAt: '2024-01-01',
    isCustom: false,
  },
];
