const mongoose = require('mongoose');
const { v4: uuidv4 } = require('uuid');

const gameSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  name: {
    type: String,
    required: [true, 'Game name is required'],
    trim: true,
    maxlength: [100, 'Game name cannot exceed 100 characters']
  },
  topic: {
    type: String,
    required: true,
    enum: ['offensive', 'defensive', 'control', 'transition'],
    default: 'transition'
  },
  gameType: {
    type: String,
    enum: ['warmup', 'main', 'cooldown'],
    default: 'main'
  },
  topPlayer: {
    type: String,
    default: '',
    maxlength: [2000, 'Top player instructions cannot exceed 2000 characters']
  },
  bottomPlayer: {
    type: String,
    default: '',
    maxlength: [2000, 'Bottom player instructions cannot exceed 2000 characters']
  },
  coaching: {
    type: String,
    default: '',
    maxlength: [3000, 'Coaching notes cannot exceed 3000 characters']
  },
  personalNotes: {
    type: String,
    default: '',
    maxlength: [2000, 'Personal notes cannot exceed 2000 characters']
  },
  skills: [{
    type: String,
    trim: true
  }],
  favorite: {
    type: Boolean,
    default: false
  },
  rating: {
    type: Number,
    min: 0,
    max: 5,
    default: 0
  },
  lastUsed: {
    type: Date,
    default: null
  },
  usageCount: {
    type: Number,
    default: 0
  },
  // For sharing
  shareId: {
    type: String,
    unique: true,
    sparse: true
  },
  isPublic: {
    type: Boolean,
    default: false
  },
  // Track if this was generated by AI
  aiGenerated: {
    type: Boolean,
    default: false
  },
  // For AI-generated games, store additional metadata
  aiMetadata: {
    startPosition: String,
    constraints: [String],
    winConditions: {
      top: String,
      bottom: String
    },
    progressions: [String],
    pedagogicalNote: String
  },
  // For game progressions - linked games in a sequence
  linkedGames: {
    previous: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Game',
      default: null
    },
    next: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Game',
      default: null
    }
  },
  difficulty: {
    type: String,
    enum: ['beginner', 'intermediate', 'advanced'],
    default: 'intermediate'
  },
  // Video reference for the game
  videoUrl: {
    type: String,
    default: '',
    maxlength: [500, 'Video URL cannot exceed 500 characters']
  },
  // Effectiveness tracking - average rating after each use
  effectivenessRatings: [{
    rating: { type: Number, min: 1, max: 5 },
    sessionId: { type: mongoose.Schema.Types.ObjectId, ref: 'Session' },
    notes: String,
    date: { type: Date, default: Date.now }
  }],
  averageEffectiveness: {
    type: Number,
    min: 0,
    max: 5,
    default: 0
  }
}, {
  timestamps: true
});

// Index for faster queries
gameSchema.index({ user: 1, favorite: 1 });
gameSchema.index({ user: 1, lastUsed: -1 });
gameSchema.index({ user: 1, topic: 1 });
gameSchema.index({ user: 1, gameType: 1 });
gameSchema.index({ shareId: 1 });

// Generate share ID
gameSchema.methods.generateShareId = function() {
  this.shareId = uuidv4();
  this.isPublic = true;
  return this.shareId;
};

module.exports = mongoose.model('Game', gameSchema);
