const mongoose = require('mongoose');
const { v4: uuidv4 } = require('uuid');

const gameSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  name: {
    type: String,
    required: [true, 'Game name is required'],
    trim: true,
    maxlength: [100, 'Game name cannot exceed 100 characters']
  },
  topic: {
    type: String,
    required: true,
    enum: ['offensive', 'defensive', 'control', 'transition'],
    default: 'transition'
  },
  topPlayer: {
    type: String,
    default: '',
    maxlength: [2000, 'Top player instructions cannot exceed 2000 characters']
  },
  bottomPlayer: {
    type: String,
    default: '',
    maxlength: [2000, 'Bottom player instructions cannot exceed 2000 characters']
  },
  coaching: {
    type: String,
    default: '',
    maxlength: [3000, 'Coaching notes cannot exceed 3000 characters']
  },
  skills: [{
    type: String,
    trim: true
  }],
  favorite: {
    type: Boolean,
    default: false
  },
  rating: {
    type: Number,
    min: 0,
    max: 5,
    default: 0
  },
  lastUsed: {
    type: Date,
    default: null
  },
  usageCount: {
    type: Number,
    default: 0
  },
  // For sharing
  shareId: {
    type: String,
    unique: true,
    sparse: true
  },
  isPublic: {
    type: Boolean,
    default: false
  },
  // Track if this was generated by AI
  aiGenerated: {
    type: Boolean,
    default: false
  },
  // For AI-generated games, store additional metadata
  aiMetadata: {
    startPosition: String,
    constraints: [String],
    winConditions: {
      top: String,
      bottom: String
    },
    progressions: [String],
    pedagogicalNote: String
  }
}, {
  timestamps: true
});

// Index for faster queries
gameSchema.index({ user: 1, favorite: 1 });
gameSchema.index({ user: 1, lastUsed: -1 });
gameSchema.index({ user: 1, topic: 1 });
gameSchema.index({ shareId: 1 });

// Generate share ID
gameSchema.methods.generateShareId = function() {
  this.shareId = uuidv4();
  this.isPublic = true;
  return this.shareId;
};

module.exports = mongoose.model('Game', gameSchema);
