import type { CurriculumFormData } from '@/types/database'

// ═══════════════════════════════════════════════════════════
// CURRICULA - Modern Grappling Programs
// Gi and Nogi tracks with progressive skill building
// ═══════════════════════════════════════════════════════════

// Note: session_ids will be populated after sessions are seeded

export const curricula: CurriculumFormData[] = [
  {
    name: 'Modern Gi Fundamentals (8-Week Cycle)',
    description: 'Complete gi curriculum covering closed guard, half guard, passing, back attacks, side control, and competition prep. Built on Danaher systems with traditional gi techniques.',
    duration_weeks: 8,
    goal: 'Build a complete gi game from guard to top control. Students should have a functional closed guard, basic passing sequence, and 2-3 reliable submissions by the end.',
    target_belt_level: 'white',
    environment: 'gi',
    session_ids: [],
    progression_notes: 'Week 1-2: Guard & Escapes (survival first). Week 3-4: Attacks & Passing. Week 5-6: Advanced positions. Week 7-8: Competition prep & review. Each week builds on the last. White and blue belts focus on core techniques, purple+ add advanced variations.',
  },
  {
    name: 'Modern Nogi Grappling (8-Week Cycle)',
    description: 'Complete nogi curriculum based on New Wave / Danaher system. Takedowns, body lock passing, leg locks, back attacks, and modern guard play.',
    duration_weeks: 8,
    goal: 'Develop a systematic nogi game. Students will have entries into leg entanglements, pressure passing chains, and back attack sequences.',
    target_belt_level: 'blue',
    environment: 'nogi',
    session_ids: [],
    progression_notes: 'Week 1-2: Takedowns & Closed Guard. Week 3-4: Open Guard & Passing. Week 5: Leg Locks. Week 6: Front Headlock. Week 7: Scrambles. Week 8: Competition. Blue belts focus on systems, purple+ refine timing and chains.',
  },
  {
    name: 'Competition Preparation (4-Week Camp)',
    description: 'Intensive 4-week camp for upcoming competition. High-intensity positional sparring, takedown drilling, and mental preparation.',
    duration_weeks: 4,
    goal: 'Peak physical and technical readiness for competition. Sharpen A-game, improve cardio, develop competition mindset.',
    target_belt_level: 'blue',
    environment: 'nogi',
    session_ids: [],
    progression_notes: 'Week 1: Identify and drill A-game. Week 2: Positional sparring focused on weak spots. Week 3: Full competition simulation. Week 4: Taper - light technique, mental prep, weight management.',
  },
  {
    name: 'Leg Lock Mastery (6-Week Program)',
    description: 'Dedicated leg lock curriculum. Ashi garami positions, entries from guard and passing, heel hooks, knee bars, and defensive escapes. Danaher / Craig Jones system.',
    duration_weeks: 6,
    goal: 'Complete understanding of the leg lock game. Students will know all major entanglement positions, entries, finishes, and defenses.',
    target_belt_level: 'purple',
    environment: 'nogi',
    session_ids: [],
    progression_notes: 'Week 1: Positional hierarchy (SLX, ashi, inside sankaku, 50/50). Week 2: Entries from guard. Week 3: Entries from passing/top. Week 4: Inside heel hook & outside heel hook finishing. Week 5: Knee bar & toe hold. Week 6: Defense, escapes, and live drilling.',
  },
  {
    name: 'Back Attack Specialist (4-Week Program)',
    description: 'Deep dive into the back attack system. Entries from every position, seatbelt & body triangle control, RNC system, and gi-specific back attacks.',
    duration_weeks: 4,
    goal: 'Make the back your home. Multiple entries, unbreakable control, and systematic finishing sequences.',
    target_belt_level: 'blue',
    environment: 'nogi',
    session_ids: [],
    progression_notes: 'Week 1: Back take entries (arm drag, turtle, mount, guard). Week 2: Back retention (seatbelt, body triangle, ride the escape). Week 3: Finishing (RNC short choke, armbar, triangle). Week 4: Defense & live rounds.',
  },
  {
    name: 'Guard Passing Masterclass (6-Week Program)',
    description: 'Comprehensive passing curriculum. Speed passing, pressure passing, and leg drag system. Both gi and nogi applications.',
    duration_weeks: 6,
    goal: 'Systematic approach to passing any guard. Students will have answers for every guard they encounter.',
    target_belt_level: 'blue',
    environment: 'nogi',
    session_ids: [],
    progression_notes: 'Week 1: Headquarters & toreando. Week 2: Knee cut & long step. Week 3: Body lock & over-under (pressure). Week 4: Leg drag system. Week 5: Guard-specific solutions (DLR, half, butterfly). Week 6: Live passing rounds & competition passing.',
  },
  {
    name: 'White Belt Survival Guide (12-Week Program)',
    description: 'Complete beginner curriculum. Escapes from every bad position, basic guard, fundamental submissions. Build confidence and safety awareness.',
    duration_weeks: 12,
    goal: 'Survive against higher belts. Know escapes from mount, side control, and back. Have 1-2 sweeps and 1-2 submissions.',
    target_belt_level: 'white',
    environment: 'gi',
    session_ids: [],
    progression_notes: 'Weeks 1-3: Escapes (mount escape, side control escape, back escape). Weeks 4-6: Closed guard (hip bump, scissor sweep, armbar, triangle). Weeks 7-9: Half guard & side control top. Weeks 10-12: Standing & open guard basics. Repeat cycle for 2nd stripe+.',
  },
  {
    name: 'Gi Guard Specialist (6-Week Program)',
    description: 'Deep dive into gi-specific guards. Collar sleeve, spider, lasso, DLR, RDLR. Build a complete gi guard system with sweeps and submissions from each.',
    duration_weeks: 6,
    goal: 'Develop an impassable guard in the gi. Chain between guards, sweep from any position, submit from guard.',
    target_belt_level: 'blue',
    environment: 'gi',
    session_ids: [],
    progression_notes: 'Week 1: Collar sleeve fundamentals. Week 2: Spider & lasso. Week 3: DLR system. Week 4: RDLR & berimbolo. Week 5: Guard transitions & chaining. Week 6: Live guard play & troubleshooting.',
  },

  // ── ADDITIONAL CURRICULA ────────────────────────────────

  {
    name: 'Lachlan Giles Half Guard Anthology (6-Week Program)',
    description: 'Comprehensive half guard system based on Lachlan Giles methodology. Deep half, knee shield, lockdown, sweeps, back takes, and underhook battles from half guard. Covers both retention and attacking.',
    duration_weeks: 6,
    goal: 'Make half guard your most dangerous position. Develop a complete half guard game with multiple sweep paths, back takes, and submission entries from every half guard variation.',
    target_belt_level: 'purple',
    environment: 'nogi',
    session_ids: [],
    progression_notes: 'Week 1: Knee shield half guard - framing, hip positioning, underhook pummel, basic sweeps. Week 2: Deep half guard entries, waiter sweep, Homer Simpson sweep, electric chair. Week 3: Lockdown half guard - whip up, electric chair, old school sweep. Week 4: Half guard to back takes - dog fight, underhook series, coyote half guard. Week 5: Half guard sweeps to leg entanglements - K-guard entries, calf slicer, kneebar from half. Week 6: Live half guard rounds, troubleshooting, and chaining all systems together.',
  },
  {
    name: 'Craig Jones Leg Lock System (4-Week Program)',
    description: 'Dedicated leg lock curriculum inspired by Craig Jones. Z-guard to leg entries, inside sankaku mastery, power ride concepts, heel hook finishing mechanics, and defensive awareness.',
    duration_weeks: 4,
    goal: 'Develop a dangerous leg lock game with reliable entries, strong control positions, and high-percentage finishes. Understand both offense and defense in the leg lock meta.',
    target_belt_level: 'purple',
    environment: 'nogi',
    session_ids: [],
    progression_notes: 'Week 1: Z-guard entries to leg entanglements - outside ashi, cross ashi, inside sankaku entries from guard. Positional hierarchy review. Week 2: Inside sankaku (411/saddle) mastery - entries from top and bottom, hip positioning, knee line control, inside heel hook finishing mechanics. Week 3: Power ride & cradle system - top-side leg lock entries, power ride to back, cradle to inside sankaku, transitional leg attacks from passing. Week 4: Heel hook defense & escape, boot defense, hitchhiker escape, live leg lock rounds with progressive resistance.',
  },
  {
    name: 'Gordon Ryan Passing Masterclass (6-Week Program)',
    description: 'Systematic guard passing curriculum based on Gordon Ryan methodology. Body lock passing, over-under, headquarters position, float passing, and relentless pressure. The most methodical passing system in modern grappling.',
    duration_weeks: 6,
    goal: 'Pass any guard systematically. Develop a pressure-based passing game that breaks even the best guard players. Chain passes together so every defense leads to a new pass.',
    target_belt_level: 'blue',
    environment: 'nogi',
    session_ids: [],
    progression_notes: 'Week 1: Headquarters position - stance, grips, distance management, toreando & knee cut from HQ. Week 2: Body lock passing - closing distance, body lock grip, smash pass, leg drag from body lock, over-under pass. Week 3: Float passing & leg drags - backstep, float over guard, leg drag to side control, long step pass. Week 4: Pressure passing system - stack pass, over-under, double under, forcing half guard to pass. Week 5: Guard-specific solutions - passing DLR, RDLR, butterfly, half guard, lasso. Troubleshooting common problems. Week 6: Live passing rounds, competition passing strategy, chaining passes into submission sequences.',
  },
  {
    name: 'Marcelo Garcia Guard System (4-Week Program)',
    description: 'Guard system based on Marcelo Garcia methodology. Butterfly guard as the foundation, X-guard and single leg X sweeps, arm drags to back takes, guillotine system, and north-south attacks. The GOAT guard player system.',
    duration_weeks: 4,
    goal: 'Build a dynamic guard game centered on butterfly guard. Chain between butterfly, X-guard, and SLX fluidly. Develop reliable arm drags and guillotines as primary weapons.',
    target_belt_level: 'blue',
    environment: 'nogi',
    session_ids: [],
    progression_notes: 'Week 1: Butterfly guard fundamentals - posture, hooks, elevations, basic sweeps, arm drag from butterfly to back take. Week 2: X-guard & SLX - entries from butterfly, technical standup sweep, ankle pick from X, back take from SLX. Week 3: Guillotine system - arm-in guillotine, high elbow guillotine, Marcelotine, guillotine from guard pull, guillotine from failed takedown defense. Week 4: North-south choke & putting it all together - north-south position, Marcelo choke, flow drilling butterfly > X > SLX > back > submission chains.',
  },
  {
    name: 'CLA-Based Skill Acquisition (8-Week Program)',
    description: 'Constraints-led approach (CLA) to BJJ skill acquisition based on Greg Souders methodology. Ecological dynamics, representative learning design, constraint manipulation, and self-organization principles applied to grappling development.',
    duration_weeks: 8,
    goal: 'Develop adaptive, creative grapplers who can solve novel movement problems. Move away from prescriptive technique drilling toward emergent skill development through carefully designed practice environments.',
    target_belt_level: 'white',
    environment: 'nogi',
    session_ids: [],
    progression_notes: 'Week 1: Introduction to CLA - what are constraints? Task, environment, and individual constraints. Simple guard retention games with progressive constraints. Week 2: Guard passing games - manipulate constraints to shape passing behavior (e.g., passer must maintain contact, limited grips). Week 3: Takedown & wrestling games - space constraints, touch rules, positional starts that encourage specific solutions. Week 4: Submission hunting games - constraint games that encourage offensive submissions without prescribing specific techniques. Week 5: Transition & scramble games - chaotic positional starts, short rounds, reward transitions. Week 6: Defense & escape games - start in bad positions, constraint manipulation to develop escape creativity. Week 7: Combined games - layer multiple constraints, full positional sequences, student-designed games. Week 8: Assessment through game play - evaluate skill development through representative game scenarios, student reflection, goal setting.',
  },
  {
    name: 'Wrestling for BJJ (4-Week Program)',
    description: 'Wrestling fundamentals adapted for BJJ competition. Clinch work, single legs, double legs, snap downs, sprawl defense, and guard pull integration. Build a complete standup game that connects to your ground game.',
    duration_weeks: 4,
    goal: 'Develop confidence and competence on the feet. Have at least 2 reliable takedowns, solid sprawl defense, and the ability to seamlessly transition between wrestling and guard pulling.',
    target_belt_level: 'white',
    environment: 'wrestling',
    session_ids: [],
    progression_notes: 'Week 1: Stance, motion, and clinch work - wrestling stance for BJJ, level changes, collar ties, underhook/overhook pummeling, snap downs to front headlock. Week 2: Double leg & single leg takedowns - penetration step, double leg finish variations, single leg (head inside & outside), chain wrestling between single and double. Week 3: Takedown defense - sprawl mechanics, whizzer defense, re-shooting off defense, guard pull as defensive option, sitting to guard from clinch. Week 4: Integration & live wrestling - takedown to pass sequences, takedown to submission chains, guard pull setups from clinch, live standup rounds with BJJ rules.',
  },
]
