import type { GameFormData } from '@/types/database'

// ═══════════════════════════════════════════════════════════
// GAMES / DRILLS / POSITIONAL SPARRING
// Based on CLA (Constraints-Led Approach) principles
// ═══════════════════════════════════════════════════════════

export const games: GameFormData[] = [
  // ── WARMUPS ─────────────────────────────────────────────
  {
    name: 'Animal Flow Movement Prep',
    description: 'Bear crawls, crab walks, monkey walks, frog jumps, crocodile walks. Full body movement prep that builds grappling-specific coordination.',
    position: 'other',
    topic: 'Movement',
    difficulty: 'beginner',
    category: 'warmup',
    duration_minutes: 8,
    techniques: ['hip mobility', 'crawling patterns', 'coordination'],
    variations: ['Add partner follow-the-leader', 'Obstacle course style', 'Race format'],
    environment_tags: ['nogi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Stay low, knees off ground for bear crawl' },
      { type: 'environmental', description: 'Use full mat space' },
    ],
    technique_ids: [],
  },
  {
    name: 'Guard Retention Flow',
    description: 'Partner A tries to pass standing, Partner B uses feet on hips, frames, and hip escapes to maintain guard. No submissions. Pure movement.',
    position: 'open-guard',
    topic: 'Guard Retention',
    difficulty: 'beginner',
    category: 'warmup',
    duration_minutes: 6,
    techniques: ['hip escape', 'feet on hips', 'leg pummeling', 'framing'],
    variations: ['Bottom only uses one leg', 'Top can only use hands (no passing)', 'Add timer pressure'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'No submissions, no grips above waist for top player' },
      { type: 'performer', description: 'Bottom must keep at least one foot connected at all times' },
    ],
    technique_ids: [],
  },
  {
    name: 'Pummeling Rounds',
    description: 'Underhook pummeling from clinch. Win double underhooks or body lock. Reset when achieved.',
    position: 'clinch',
    topic: 'Clinch Work',
    difficulty: 'beginner',
    category: 'warmup',
    duration_minutes: 5,
    techniques: ['pummeling', 'underhook', 'body lock'],
    variations: ['Add snap down on winning', 'Russian tie entries', 'One person starts with double unders'],
    environment_tags: ['nogi', 'wrestling'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'No takedowns, focus on hand fighting and pummeling only' },
    ],
    technique_ids: [],
  },
  {
    name: 'Butterfly Elevation Drill',
    description: 'Seated butterfly guard. Partner A posts on Partner B. B elevates with hooks and comes up, then resets. Continuous.',
    position: 'open-guard',
    topic: 'Butterfly Guard',
    difficulty: 'beginner',
    category: 'warmup',
    duration_minutes: 5,
    techniques: ['butterfly hook', 'elevation', 'underhook'],
    variations: ['Add arm drag when elevation fails', 'Alternate sides', 'Partner resists 50%'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'low',
    rule_constraints: [
      { type: 'task', description: 'Attacker resets after each successful elevation' },
    ],
    technique_ids: [],
  },
  {
    name: 'Granby Roll & Inversion Flow',
    description: 'Solo and partner granby rolls, shoulder rolls, inversions. Build comfort upside down for guard retention and leg lock defense.',
    position: 'other',
    topic: 'Inversions',
    difficulty: 'intermediate',
    category: 'warmup',
    duration_minutes: 6,
    techniques: ['granby roll', 'inversion', 'shoulder roll'],
    variations: ['Partner provides light pressure', 'Chain 3 inversions in a row', 'Add reguard at end'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'low',
    rule_constraints: [
      { type: 'performer', description: 'Move slowly and controlled, protect the neck' },
    ],
    technique_ids: [],
  },
  {
    name: 'Hip Escape Relay Race',
    description: 'Teams race across the mat using hip escapes. Fun competitive warmup that drills the most fundamental movement.',
    position: 'other',
    topic: 'Movement',
    difficulty: 'beginner',
    category: 'warmup',
    duration_minutes: 5,
    techniques: ['hip escape', 'shrimping'],
    variations: ['Forward shrimps', 'Reverse shrimps', 'Mix in technical standups'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'environmental', description: 'Full mat length' },
      { type: 'task', description: 'Hips must touch mat on each escape' },
    ],
    technique_ids: [],
  },
  {
    name: 'Seated Guard Wrestling Flow',
    description: 'Both partners start seated. Fight for grips, entries, and sweeps. If swept, reset. Flow intensity.',
    position: 'open-guard',
    topic: 'Seated Guard',
    difficulty: 'intermediate',
    category: 'warmup',
    duration_minutes: 6,
    techniques: ['seated guard', 'collar tie', 'arm drag', 'shin-to-shin'],
    variations: ['One seated one standing', 'No hand touching ground', 'Add leg lock entries'],
    environment_tags: ['nogi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Reset after each sweep, no submissions' },
    ],
    technique_ids: [],
  },

  // ── MAIN DRILLS & POSITIONAL SPARRING ──────────────────
  {
    name: 'Pass vs Guard - King of the Hill',
    description: 'One person stays in guard. Challengers rotate in trying to pass. If they pass, they become the new guard player.',
    position: 'guard',
    topic: 'Guard Passing',
    difficulty: 'intermediate',
    category: 'main',
    duration_minutes: 15,
    techniques: ['guard passing', 'guard retention', 'sweeps'],
    variations: ['Guard player gets points for sweeps', 'Time limit per attempt', 'Specific guard only (half, DLR, etc.)'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'Start from open guard, pass scores a point, sweep scores a point' },
      { type: 'environmental', description: 'Rotate every 2 minutes or on score' },
    ],
    technique_ids: [],
  },
  {
    name: 'Submission-Only Positional: Mount',
    description: 'Start in mount. Top attacks, bottom escapes. Reset if escape or submission. Track success rate.',
    position: 'mount',
    topic: 'Mount',
    difficulty: 'intermediate',
    category: 'positional',
    duration_minutes: 10,
    techniques: ['mount attacks', 'mount escapes', 'mount retention'],
    variations: ['High mount only', 'Bottom starts flat (worst case)', 'Gi chokes allowed'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'Start in full mount. Top player seeks submission, bottom seeks escape to guard.' },
      { type: 'performer', description: 'Reset after submission or full escape' },
    ],
    technique_ids: [],
  },
  {
    name: 'Submission-Only Positional: Back',
    description: 'Start with seatbelt and hooks. Attacker hunts RNC, defender fights hands and escapes. The most important position.',
    position: 'back',
    topic: 'Back Attacks',
    difficulty: 'intermediate',
    category: 'positional',
    duration_minutes: 10,
    techniques: ['RNC', 'back escape', 'back retention', 'seatbelt'],
    variations: ['Body triangle variation', 'Start from turtle', 'Allow armbar transitions'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'Start with seatbelt and both hooks. Attacker seeks choke, defender seeks escape.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Submission-Only Positional: Side Control',
    description: 'Start in side control. Top works submissions, bottom escapes or reguards. Build pressure game.',
    position: 'side-control',
    topic: 'Side Control',
    difficulty: 'intermediate',
    category: 'positional',
    duration_minutes: 10,
    techniques: ['side control attacks', 'escapes', 'mount transition'],
    variations: ['Top can advance to mount (bonus)', 'Kesa gatame start', 'North-south transitions allowed'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'Start in crossface side control. Top attacks or advances, bottom escapes.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Half Guard Battle',
    description: 'Start in half guard. Both players fight for position. Top passes, bottom sweeps or submits.',
    position: 'half-guard',
    topic: 'Half Guard',
    difficulty: 'intermediate',
    category: 'positional',
    duration_minutes: 10,
    techniques: ['half guard sweep', 'knee cut', 'underhook battle'],
    variations: ['Z guard start', 'Deep half entries allowed', 'No knee cut (force creative passing)'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'Start in knee shield half guard. Top passes, bottom sweeps or submits.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Leg Lock Entry Sparring',
    description: 'Start from standing or seated. Goal is to enter a leg entanglement. No finishing, just entry. Builds leg lock awareness.',
    position: 'guard',
    topic: 'Leg Locks',
    difficulty: 'advanced',
    category: 'positional',
    duration_minutes: 10,
    techniques: ['SLX entry', 'inside sankaku', 'ashi garami', 'K guard'],
    variations: ['Only from guard pull', 'Only from passing attempts', 'Allow finishes for advanced'],
    environment_tags: ['nogi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Score by achieving leg entanglement control for 3 seconds. No finishing subs.' },
      { type: 'performer', description: 'Controlled entries only, no cranking' },
    ],
    technique_ids: [],
  },
  {
    name: 'Takedown Sparring - Light',
    description: '70% intensity takedown rounds. Work shots, sprawls, clinch entries, and guard pulls.',
    position: 'standing',
    topic: 'Takedowns',
    difficulty: 'intermediate',
    category: 'positional',
    duration_minutes: 10,
    techniques: ['single leg', 'double leg', 'snap down', 'sprawl'],
    variations: ['Gi grips only', 'No double legs', 'Must set up with hand fighting first'],
    environment_tags: ['nogi', 'wrestling'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'Takedown scores, guard pull is neutral. Reset standing after each score.' },
      { type: 'performer', description: '70% speed max. Protect your partner.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Turtle Attack / Escape Drill',
    description: 'One player starts in turtle, other has back exposure. Attack the back or flatten. Turtle player escapes or reguards.',
    position: 'turtle',
    topic: 'Turtle',
    difficulty: 'intermediate',
    category: 'positional',
    duration_minutes: 8,
    techniques: ['turtle escape', 'back take', 'front headlock', 'sit out'],
    variations: ['Start from referee position', 'Allow front headlock subs', 'Granby rolls only'],
    environment_tags: ['nogi', 'gi', 'wrestling'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Top scores with back take or flatten. Bottom scores with escape to guard or reversal.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Front Headlock Series - Live',
    description: 'Start in front headlock position. Attacker works guillotine, darce, anaconda. Defender escapes to guard or standing.',
    position: 'turtle',
    topic: 'Front Headlock',
    difficulty: 'intermediate',
    category: 'positional',
    duration_minutes: 8,
    techniques: ['guillotine', 'darce', 'anaconda', 'front headlock escape'],
    variations: ['Only guillotines', 'Must chain 2 attacks before reset', 'Standing front headlock start'],
    environment_tags: ['nogi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Attacker works front headlock submissions. Defender escapes to neutral.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Guard Pull to Sweep Game',
    description: 'Start standing. One player pulls guard and must sweep within 30 seconds. Teaches urgency from bottom.',
    position: 'standing',
    topic: 'Guard Pulling',
    difficulty: 'intermediate',
    category: 'main',
    duration_minutes: 10,
    techniques: ['guard pull', 'butterfly sweep', 'collar sleeve', 'x guard'],
    variations: ['Must pull to specific guard', 'Passer can submit', 'Switch roles each round'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Guard puller has 30 seconds to sweep. Failure = top player scores.' },
      { type: 'environmental', description: '30 second timer per attempt' },
    ],
    technique_ids: [],
  },
  {
    name: 'Shark Tank',
    description: 'One person in the middle, fresh opponents rotate in every 90 seconds. Middle person starts in worst position each round.',
    position: 'other',
    topic: 'Conditioning',
    difficulty: 'advanced',
    category: 'main',
    duration_minutes: 12,
    techniques: ['all positions', 'escapes', 'survival'],
    variations: ['Start from mount bottom', 'Start from back', 'Submission-only resets'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'Middle person must escape or survive. Fresh partner every 90 seconds.' },
      { type: 'performer', description: 'Fresh partners go 100%, middle person works technique under fatigue' },
    ],
    technique_ids: [],
  },
  {
    name: 'Closed Guard Offense - Sweep or Submit',
    description: 'Start in closed guard. Bottom player must sweep or submit. Top player defends and tries to open and pass.',
    position: 'closed-guard',
    topic: 'Closed Guard',
    difficulty: 'beginner',
    category: 'positional',
    duration_minutes: 10,
    techniques: ['hip bump', 'kimura', 'scissor sweep', 'triangle'],
    variations: ['No submissions, sweeps only', 'Only kimura/guillotine chain', 'Add gi chokes'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Start locked in closed guard. Bottom attacks, top defends and opens guard.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Body Lock Passing Drill',
    description: 'Passer must achieve body lock and pass. Guard player fights to maintain distance. Gordon Ryan style.',
    position: 'guard',
    topic: 'Guard Passing',
    difficulty: 'advanced',
    category: 'main',
    duration_minutes: 10,
    techniques: ['body lock pass', 'guard retention', 'leg pummeling'],
    variations: ['Over-under allowed too', 'Guard player can sweep for points', 'Start from standing'],
    environment_tags: ['nogi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'Passer must use body lock or over-under to pass. No toreando or speed passes.' },
      { type: 'performer', description: 'Work heavy top pressure, methodical passing' },
    ],
    technique_ids: [],
  },
  {
    name: 'Back Take Chain Drill',
    description: 'Partner A tries to take the back from various positions. Start seated, progress to turtle, to dog fight. Chain entries together.',
    position: 'back',
    topic: 'Back Takes',
    difficulty: 'intermediate',
    category: 'drill',
    duration_minutes: 8,
    techniques: ['arm drag', 'chair sit', 'gift wrap', 'seatbelt'],
    variations: ['From closed guard arm drag', 'From front headlock', 'Standing back take entries'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Focus on back take entries only. No finishing submissions.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Scramble Rounds',
    description: 'Start from a scramble position (both on knees, or tangled up). First to establish dominant position wins.',
    position: 'other',
    topic: 'Scrambles',
    difficulty: 'intermediate',
    category: 'main',
    duration_minutes: 8,
    techniques: ['wrestling', 'transitions', 'reversals'],
    variations: ['Start from different positions', 'Must submit from the scramble', 'Feet-only starts'],
    environment_tags: ['nogi', 'wrestling'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'First to establish control for 3 seconds scores. Reset.' },
    ],
    technique_ids: [],
  },

  // ── GI-SPECIFIC DRILLS ─────────────────────────────────
  {
    name: 'Collar & Sleeve Guard Game',
    description: 'Start in collar sleeve guard. Bottom works sweeps and submissions, top works to strip grips and pass.',
    position: 'open-guard',
    topic: 'Gi Guard',
    difficulty: 'intermediate',
    category: 'positional',
    duration_minutes: 10,
    techniques: ['collar sleeve', 'triangle', 'omoplata', 'sweep'],
    variations: ['Spider guard allowed', 'Lasso entries', 'DLR transitions'],
    environment_tags: ['gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Start in collar sleeve guard. Bottom sweeps/submits, top passes.' },
      { type: 'environmental', description: 'Gi only' },
    ],
    technique_ids: [],
  },
  {
    name: 'DLR / RDLR Guard Flow',
    description: 'Guard player uses De La Riva and Reverse De La Riva to sweep, take back, or enter berimbolo. Top works to disengage and pass.',
    position: 'open-guard',
    topic: 'DLR System',
    difficulty: 'advanced',
    category: 'positional',
    duration_minutes: 10,
    techniques: ['DLR', 'RDLR', 'berimbolo', 'kiss of the dragon'],
    variations: ['Berimbolo entries only', 'Kiss of the dragon focus', 'Add X guard transitions'],
    environment_tags: ['gi', 'nogi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Guard must use DLR or RDLR as primary guard. Top passes freely.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Grip Fighting Rounds',
    description: 'Gi grip fighting from standing. Win dominant grips (collar + sleeve, double lapel). No takedowns, just grip strategy.',
    position: 'standing',
    topic: 'Grip Fighting',
    difficulty: 'intermediate',
    category: 'drill',
    duration_minutes: 6,
    techniques: ['grip fighting', 'grip breaking', 'collar grip', 'sleeve grip'],
    variations: ['One person defends only', 'Specific grip sequence required', 'Judo grip rules'],
    environment_tags: ['gi', 'judo'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'No takedowns. Score by achieving and holding dominant grip for 3 seconds.' },
      { type: 'environmental', description: 'Gi required' },
    ],
    technique_ids: [],
  },

  // ── NOGI-SPECIFIC DRILLS ───────────────────────────────
  {
    name: 'Leg Lock Flow - Entry to Finish',
    description: 'Start from neutral. Work leg lock entries, transitions between entanglements, and controlled finishes.',
    position: 'guard',
    topic: 'Leg Locks',
    difficulty: 'advanced',
    category: 'drill',
    duration_minutes: 10,
    techniques: ['inside sankaku', 'ashi garami', 'heel hook', 'knee bar'],
    variations: ['Entries from SLX only', 'K guard entries', 'Defense/escape focus for one partner'],
    environment_tags: ['nogi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Flow drilling leg locks. Catch and release. No cranking.' },
      { type: 'performer', description: 'Controlled, communicative. Tap early to repping entries.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Nogi Passing Gauntlet',
    description: 'Guard player sits, passer stands. Must pass using body lock, over-under, or leg drag. No toreando. Modern nogi passing.',
    position: 'guard',
    topic: 'Nogi Passing',
    difficulty: 'advanced',
    category: 'main',
    duration_minutes: 12,
    techniques: ['body lock pass', 'over-under', 'leg drag', 'guard retention'],
    variations: ['Guard player starts in butterfly', 'Passer starts on knees', 'Allow toreando as option'],
    environment_tags: ['nogi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'Passer uses pressure passing only. Guard player can sweep or submit.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Wrestling Up Game',
    description: 'Bottom player must stand up from seated guard against a standing opponent. Teaches wrestling up and technical standup.',
    position: 'open-guard',
    topic: 'Wrestling Up',
    difficulty: 'intermediate',
    category: 'main',
    duration_minutes: 8,
    techniques: ['technical standup', 'single leg from bottom', 'seated guard'],
    variations: ['No pulling back to guard', 'Top can shoot when bottom stands', 'Points for clean standup'],
    environment_tags: ['nogi', 'wrestling'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Bottom must achieve standing position. Top tries to maintain top position.' },
    ],
    technique_ids: [],
  },

  // ── COOLDOWNS ──────────────────────────────────────────
  {
    name: 'Flow Rolling (5 min)',
    description: 'Light, technical rolling. No resistance over 30%. Focus on movement, transitions, and chains. No ego.',
    position: 'other',
    topic: 'Flow',
    difficulty: 'beginner',
    category: 'cooldown',
    duration_minutes: 5,
    techniques: ['all'],
    variations: ['Submission-only flow', 'Positional flow (guard only)', 'Slow motion rolling'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'low',
    rule_constraints: [
      { type: 'performer', description: 'Maximum 30% resistance. Catch and release.' },
      { type: 'task', description: 'Focus on smooth transitions, not winning' },
    ],
    technique_ids: [],
  },
  {
    name: 'Grappling-Specific Stretching',
    description: 'Hip flexors, hamstrings, groin, shoulders, neck. Hold each stretch 30+ seconds. Essential for injury prevention.',
    position: 'other',
    topic: 'Recovery',
    difficulty: 'beginner',
    category: 'cooldown',
    duration_minutes: 8,
    techniques: ['pigeon stretch', 'butterfly stretch', 'shoulder stretches'],
    variations: ['Partner-assisted stretches', 'Yoga flow style', 'Focus on problem areas'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'low',
    rule_constraints: [
      { type: 'performer', description: 'Hold each stretch minimum 30 seconds, breathe deeply' },
    ],
    technique_ids: [],
  },
  {
    name: 'Breathing & Visualization',
    description: 'Box breathing (4-4-4-4), then 2 minutes of match visualization. Mental game training.',
    position: 'other',
    topic: 'Mental Training',
    difficulty: 'beginner',
    category: 'cooldown',
    duration_minutes: 5,
    techniques: ['breathing', 'visualization', 'mental prep'],
    variations: ['Guided visualization', 'Competition scenario focus', 'Relaxation only'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'low',
    rule_constraints: [
      { type: 'performer', description: 'Eyes closed, controlled breathing throughout' },
    ],
    technique_ids: [],
  },
  {
    name: 'Position Review & Q/A',
    description: 'Coach reviews key positions from class. Students ask questions. Troubleshoot common problems.',
    position: 'other',
    topic: 'Review',
    difficulty: 'beginner',
    category: 'cooldown',
    duration_minutes: 5,
    techniques: ['review'],
    variations: ['Student-led review', 'Partner quiz each other', 'Video review if available'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'low',
    rule_constraints: [],
    technique_ids: [],
  },
  {
    name: 'Light Positional Cycling',
    description: 'Start in mount, escape to guard, sweep to mount, give up back, escape. Continuous cycling through positions at low intensity.',
    position: 'other',
    topic: 'Transitions',
    difficulty: 'beginner',
    category: 'cooldown',
    duration_minutes: 6,
    techniques: ['transitions', 'escapes', 'sweeps'],
    variations: ['Add specific techniques at each position', 'One person leads', 'Alternate who attacks'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'low',
    rule_constraints: [
      { type: 'performer', description: 'Low intensity, focus on smooth transitions' },
      { type: 'task', description: 'Cycle: mount > guard > sweep > side control > guard > back > escape > repeat' },
    ],
    technique_ids: [],
  },
]
