import type { GameFormData } from '@/types/database'

// ═══════════════════════════════════════════════════════════
// GAMES / DRILLS / POSITIONAL SPARRING
// Based on CLA (Constraints-Led Approach) principles
// ═══════════════════════════════════════════════════════════

export const games: GameFormData[] = [
  // ── WARMUPS ─────────────────────────────────────────────
  {
    name: 'Animal Flow Movement Prep',
    description: 'Bear crawls, crab walks, monkey walks, frog jumps, crocodile walks. Full body movement prep that builds grappling-specific coordination.',
    position: 'other',
    topic: 'Movement',
    difficulty: 'beginner',
    category: 'warmup',
    duration_minutes: 8,
    techniques: ['hip mobility', 'crawling patterns', 'coordination'],
    variations: ['Add partner follow-the-leader', 'Obstacle course style', 'Race format'],
    environment_tags: ['nogi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Stay low, knees off ground for bear crawl' },
      { type: 'environmental', description: 'Use full mat space' },
    ],
    technique_ids: [],
  },
  {
    name: 'Guard Retention Flow',
    description: 'Partner A tries to pass standing, Partner B uses feet on hips, frames, and hip escapes to maintain guard. No submissions. Pure movement.',
    position: 'open-guard',
    topic: 'Guard Retention',
    difficulty: 'beginner',
    category: 'warmup',
    duration_minutes: 6,
    techniques: ['hip escape', 'feet on hips', 'leg pummeling', 'framing'],
    variations: ['Bottom only uses one leg', 'Top can only use hands (no passing)', 'Add timer pressure'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'No submissions, no grips above waist for top player' },
      { type: 'performer', description: 'Bottom must keep at least one foot connected at all times' },
    ],
    technique_ids: [],
  },
  {
    name: 'Pummeling Rounds',
    description: 'Underhook pummeling from clinch. Win double underhooks or body lock. Reset when achieved.',
    position: 'clinch',
    topic: 'Clinch Work',
    difficulty: 'beginner',
    category: 'warmup',
    duration_minutes: 5,
    techniques: ['pummeling', 'underhook', 'body lock'],
    variations: ['Add snap down on winning', 'Russian tie entries', 'One person starts with double unders'],
    environment_tags: ['nogi', 'wrestling'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'No takedowns, focus on hand fighting and pummeling only' },
    ],
    technique_ids: [],
  },
  {
    name: 'Butterfly Elevation Drill',
    description: 'Seated butterfly guard. Partner A posts on Partner B. B elevates with hooks and comes up, then resets. Continuous.',
    position: 'open-guard',
    topic: 'Butterfly Guard',
    difficulty: 'beginner',
    category: 'warmup',
    duration_minutes: 5,
    techniques: ['butterfly hook', 'elevation', 'underhook'],
    variations: ['Add arm drag when elevation fails', 'Alternate sides', 'Partner resists 50%'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'low',
    rule_constraints: [
      { type: 'task', description: 'Attacker resets after each successful elevation' },
    ],
    technique_ids: [],
  },
  {
    name: 'Granby Roll & Inversion Flow',
    description: 'Solo and partner granby rolls, shoulder rolls, inversions. Build comfort upside down for guard retention and leg lock defense.',
    position: 'other',
    topic: 'Inversions',
    difficulty: 'intermediate',
    category: 'warmup',
    duration_minutes: 6,
    techniques: ['granby roll', 'inversion', 'shoulder roll'],
    variations: ['Partner provides light pressure', 'Chain 3 inversions in a row', 'Add reguard at end'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'low',
    rule_constraints: [
      { type: 'performer', description: 'Move slowly and controlled, protect the neck' },
    ],
    technique_ids: [],
  },
  {
    name: 'Hip Escape Relay Race',
    description: 'Teams race across the mat using hip escapes. Fun competitive warmup that drills the most fundamental movement.',
    position: 'other',
    topic: 'Movement',
    difficulty: 'beginner',
    category: 'warmup',
    duration_minutes: 5,
    techniques: ['hip escape', 'shrimping'],
    variations: ['Forward shrimps', 'Reverse shrimps', 'Mix in technical standups'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'environmental', description: 'Full mat length' },
      { type: 'task', description: 'Hips must touch mat on each escape' },
    ],
    technique_ids: [],
  },
  {
    name: 'Seated Guard Wrestling Flow',
    description: 'Both partners start seated. Fight for grips, entries, and sweeps. If swept, reset. Flow intensity.',
    position: 'open-guard',
    topic: 'Seated Guard',
    difficulty: 'intermediate',
    category: 'warmup',
    duration_minutes: 6,
    techniques: ['seated guard', 'collar tie', 'arm drag', 'shin-to-shin'],
    variations: ['One seated one standing', 'No hand touching ground', 'Add leg lock entries'],
    environment_tags: ['nogi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Reset after each sweep, no submissions' },
    ],
    technique_ids: [],
  },

  // ── MAIN DRILLS & POSITIONAL SPARRING ──────────────────
  {
    name: 'Pass vs Guard - King of the Hill',
    description: 'One person stays in guard. Challengers rotate in trying to pass. If they pass, they become the new guard player.',
    position: 'guard',
    topic: 'Guard Passing',
    difficulty: 'intermediate',
    category: 'main',
    duration_minutes: 15,
    techniques: ['guard passing', 'guard retention', 'sweeps'],
    variations: ['Guard player gets points for sweeps', 'Time limit per attempt', 'Specific guard only (half, DLR, etc.)'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'Start from open guard, pass scores a point, sweep scores a point' },
      { type: 'environmental', description: 'Rotate every 2 minutes or on score' },
    ],
    technique_ids: [],
  },
  {
    name: 'Submission-Only Positional: Mount',
    description: 'Start in mount. Top attacks, bottom escapes. Reset if escape or submission. Track success rate.',
    position: 'mount',
    topic: 'Mount',
    difficulty: 'intermediate',
    category: 'positional',
    duration_minutes: 10,
    techniques: ['mount attacks', 'mount escapes', 'mount retention'],
    variations: ['High mount only', 'Bottom starts flat (worst case)', 'Gi chokes allowed'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'Start in full mount. Top player seeks submission, bottom seeks escape to guard.' },
      { type: 'performer', description: 'Reset after submission or full escape' },
    ],
    technique_ids: [],
  },
  {
    name: 'Submission-Only Positional: Back',
    description: 'Start with seatbelt and hooks. Attacker hunts RNC, defender fights hands and escapes. The most important position.',
    position: 'back',
    topic: 'Back Attacks',
    difficulty: 'intermediate',
    category: 'positional',
    duration_minutes: 10,
    techniques: ['RNC', 'back escape', 'back retention', 'seatbelt'],
    variations: ['Body triangle variation', 'Start from turtle', 'Allow armbar transitions'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'Start with seatbelt and both hooks. Attacker seeks choke, defender seeks escape.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Submission-Only Positional: Side Control',
    description: 'Start in side control. Top works submissions, bottom escapes or reguards. Build pressure game.',
    position: 'side-control',
    topic: 'Side Control',
    difficulty: 'intermediate',
    category: 'positional',
    duration_minutes: 10,
    techniques: ['side control attacks', 'escapes', 'mount transition'],
    variations: ['Top can advance to mount (bonus)', 'Kesa gatame start', 'North-south transitions allowed'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'Start in crossface side control. Top attacks or advances, bottom escapes.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Half Guard Battle',
    description: 'Start in half guard. Both players fight for position. Top passes, bottom sweeps or submits.',
    position: 'half-guard',
    topic: 'Half Guard',
    difficulty: 'intermediate',
    category: 'positional',
    duration_minutes: 10,
    techniques: ['half guard sweep', 'knee cut', 'underhook battle'],
    variations: ['Z guard start', 'Deep half entries allowed', 'No knee cut (force creative passing)'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'Start in knee shield half guard. Top passes, bottom sweeps or submits.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Leg Lock Entry Sparring',
    description: 'Start from standing or seated. Goal is to enter a leg entanglement. No finishing, just entry. Builds leg lock awareness.',
    position: 'guard',
    topic: 'Leg Locks',
    difficulty: 'advanced',
    category: 'positional',
    duration_minutes: 10,
    techniques: ['SLX entry', 'inside sankaku', 'ashi garami', 'K guard'],
    variations: ['Only from guard pull', 'Only from passing attempts', 'Allow finishes for advanced'],
    environment_tags: ['nogi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Score by achieving leg entanglement control for 3 seconds. No finishing subs.' },
      { type: 'performer', description: 'Controlled entries only, no cranking' },
    ],
    technique_ids: [],
  },
  {
    name: 'Takedown Sparring - Light',
    description: '70% intensity takedown rounds. Work shots, sprawls, clinch entries, and guard pulls.',
    position: 'standing',
    topic: 'Takedowns',
    difficulty: 'intermediate',
    category: 'positional',
    duration_minutes: 10,
    techniques: ['single leg', 'double leg', 'snap down', 'sprawl'],
    variations: ['Gi grips only', 'No double legs', 'Must set up with hand fighting first'],
    environment_tags: ['nogi', 'wrestling'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'Takedown scores, guard pull is neutral. Reset standing after each score.' },
      { type: 'performer', description: '70% speed max. Protect your partner.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Turtle Attack / Escape Drill',
    description: 'One player starts in turtle, other has back exposure. Attack the back or flatten. Turtle player escapes or reguards.',
    position: 'turtle',
    topic: 'Turtle',
    difficulty: 'intermediate',
    category: 'positional',
    duration_minutes: 8,
    techniques: ['turtle escape', 'back take', 'front headlock', 'sit out'],
    variations: ['Start from referee position', 'Allow front headlock subs', 'Granby rolls only'],
    environment_tags: ['nogi', 'gi', 'wrestling'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Top scores with back take or flatten. Bottom scores with escape to guard or reversal.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Front Headlock Series - Live',
    description: 'Start in front headlock position. Attacker works guillotine, darce, anaconda. Defender escapes to guard or standing.',
    position: 'turtle',
    topic: 'Front Headlock',
    difficulty: 'intermediate',
    category: 'positional',
    duration_minutes: 8,
    techniques: ['guillotine', 'darce', 'anaconda', 'front headlock escape'],
    variations: ['Only guillotines', 'Must chain 2 attacks before reset', 'Standing front headlock start'],
    environment_tags: ['nogi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Attacker works front headlock submissions. Defender escapes to neutral.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Guard Pull to Sweep Game',
    description: 'Start standing. One player pulls guard and must sweep within 30 seconds. Teaches urgency from bottom.',
    position: 'standing',
    topic: 'Guard Pulling',
    difficulty: 'intermediate',
    category: 'main',
    duration_minutes: 10,
    techniques: ['guard pull', 'butterfly sweep', 'collar sleeve', 'x guard'],
    variations: ['Must pull to specific guard', 'Passer can submit', 'Switch roles each round'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Guard puller has 30 seconds to sweep. Failure = top player scores.' },
      { type: 'environmental', description: '30 second timer per attempt' },
    ],
    technique_ids: [],
  },
  {
    name: 'Shark Tank',
    description: 'One person in the middle, fresh opponents rotate in every 90 seconds. Middle person starts in worst position each round.',
    position: 'other',
    topic: 'Conditioning',
    difficulty: 'advanced',
    category: 'main',
    duration_minutes: 12,
    techniques: ['all positions', 'escapes', 'survival'],
    variations: ['Start from mount bottom', 'Start from back', 'Submission-only resets'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'Middle person must escape or survive. Fresh partner every 90 seconds.' },
      { type: 'performer', description: 'Fresh partners go 100%, middle person works technique under fatigue' },
    ],
    technique_ids: [],
  },
  {
    name: 'Closed Guard Offense - Sweep or Submit',
    description: 'Start in closed guard. Bottom player must sweep or submit. Top player defends and tries to open and pass.',
    position: 'closed-guard',
    topic: 'Closed Guard',
    difficulty: 'beginner',
    category: 'positional',
    duration_minutes: 10,
    techniques: ['hip bump', 'kimura', 'scissor sweep', 'triangle'],
    variations: ['No submissions, sweeps only', 'Only kimura/guillotine chain', 'Add gi chokes'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Start locked in closed guard. Bottom attacks, top defends and opens guard.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Body Lock Passing Drill',
    description: 'Passer must achieve body lock and pass. Guard player fights to maintain distance. Gordon Ryan style.',
    position: 'guard',
    topic: 'Guard Passing',
    difficulty: 'advanced',
    category: 'main',
    duration_minutes: 10,
    techniques: ['body lock pass', 'guard retention', 'leg pummeling'],
    variations: ['Over-under allowed too', 'Guard player can sweep for points', 'Start from standing'],
    environment_tags: ['nogi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'Passer must use body lock or over-under to pass. No toreando or speed passes.' },
      { type: 'performer', description: 'Work heavy top pressure, methodical passing' },
    ],
    technique_ids: [],
  },
  {
    name: 'Back Take Chain Drill',
    description: 'Partner A tries to take the back from various positions. Start seated, progress to turtle, to dog fight. Chain entries together.',
    position: 'back',
    topic: 'Back Takes',
    difficulty: 'intermediate',
    category: 'drill',
    duration_minutes: 8,
    techniques: ['arm drag', 'chair sit', 'gift wrap', 'seatbelt'],
    variations: ['From closed guard arm drag', 'From front headlock', 'Standing back take entries'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Focus on back take entries only. No finishing submissions.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Scramble Rounds',
    description: 'Start from a scramble position (both on knees, or tangled up). First to establish dominant position wins.',
    position: 'other',
    topic: 'Scrambles',
    difficulty: 'intermediate',
    category: 'main',
    duration_minutes: 8,
    techniques: ['wrestling', 'transitions', 'reversals'],
    variations: ['Start from different positions', 'Must submit from the scramble', 'Feet-only starts'],
    environment_tags: ['nogi', 'wrestling'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'First to establish control for 3 seconds scores. Reset.' },
    ],
    technique_ids: [],
  },

  // ── GI-SPECIFIC DRILLS ─────────────────────────────────
  {
    name: 'Collar & Sleeve Guard Game',
    description: 'Start in collar sleeve guard. Bottom works sweeps and submissions, top works to strip grips and pass.',
    position: 'open-guard',
    topic: 'Gi Guard',
    difficulty: 'intermediate',
    category: 'positional',
    duration_minutes: 10,
    techniques: ['collar sleeve', 'triangle', 'omoplata', 'sweep'],
    variations: ['Spider guard allowed', 'Lasso entries', 'DLR transitions'],
    environment_tags: ['gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Start in collar sleeve guard. Bottom sweeps/submits, top passes.' },
      { type: 'environmental', description: 'Gi only' },
    ],
    technique_ids: [],
  },
  {
    name: 'DLR / RDLR Guard Flow',
    description: 'Guard player uses De La Riva and Reverse De La Riva to sweep, take back, or enter berimbolo. Top works to disengage and pass.',
    position: 'open-guard',
    topic: 'DLR System',
    difficulty: 'advanced',
    category: 'positional',
    duration_minutes: 10,
    techniques: ['DLR', 'RDLR', 'berimbolo', 'kiss of the dragon'],
    variations: ['Berimbolo entries only', 'Kiss of the dragon focus', 'Add X guard transitions'],
    environment_tags: ['gi', 'nogi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Guard must use DLR or RDLR as primary guard. Top passes freely.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Grip Fighting Rounds',
    description: 'Gi grip fighting from standing. Win dominant grips (collar + sleeve, double lapel). No takedowns, just grip strategy.',
    position: 'standing',
    topic: 'Grip Fighting',
    difficulty: 'intermediate',
    category: 'drill',
    duration_minutes: 6,
    techniques: ['grip fighting', 'grip breaking', 'collar grip', 'sleeve grip'],
    variations: ['One person defends only', 'Specific grip sequence required', 'Judo grip rules'],
    environment_tags: ['gi', 'judo'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'No takedowns. Score by achieving and holding dominant grip for 3 seconds.' },
      { type: 'environmental', description: 'Gi required' },
    ],
    technique_ids: [],
  },

  // ── NOGI-SPECIFIC DRILLS ───────────────────────────────
  {
    name: 'Leg Lock Flow - Entry to Finish',
    description: 'Start from neutral. Work leg lock entries, transitions between entanglements, and controlled finishes.',
    position: 'guard',
    topic: 'Leg Locks',
    difficulty: 'advanced',
    category: 'drill',
    duration_minutes: 10,
    techniques: ['inside sankaku', 'ashi garami', 'heel hook', 'knee bar'],
    variations: ['Entries from SLX only', 'K guard entries', 'Defense/escape focus for one partner'],
    environment_tags: ['nogi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Flow drilling leg locks. Catch and release. No cranking.' },
      { type: 'performer', description: 'Controlled, communicative. Tap early to repping entries.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Nogi Passing Gauntlet',
    description: 'Guard player sits, passer stands. Must pass using body lock, over-under, or leg drag. No toreando. Modern nogi passing.',
    position: 'guard',
    topic: 'Nogi Passing',
    difficulty: 'advanced',
    category: 'main',
    duration_minutes: 12,
    techniques: ['body lock pass', 'over-under', 'leg drag', 'guard retention'],
    variations: ['Guard player starts in butterfly', 'Passer starts on knees', 'Allow toreando as option'],
    environment_tags: ['nogi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'Passer uses pressure passing only. Guard player can sweep or submit.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Wrestling Up Game',
    description: 'Bottom player must stand up from seated guard against a standing opponent. Teaches wrestling up and technical standup.',
    position: 'open-guard',
    topic: 'Wrestling Up',
    difficulty: 'intermediate',
    category: 'main',
    duration_minutes: 8,
    techniques: ['technical standup', 'single leg from bottom', 'seated guard'],
    variations: ['No pulling back to guard', 'Top can shoot when bottom stands', 'Points for clean standup'],
    environment_tags: ['nogi', 'wrestling'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Bottom must achieve standing position. Top tries to maintain top position.' },
    ],
    technique_ids: [],
  },

  // ── COOLDOWNS ──────────────────────────────────────────
  {
    name: 'Flow Rolling (5 min)',
    description: 'Light, technical rolling. No resistance over 30%. Focus on movement, transitions, and chains. No ego.',
    position: 'other',
    topic: 'Flow',
    difficulty: 'beginner',
    category: 'cooldown',
    duration_minutes: 5,
    techniques: ['all'],
    variations: ['Submission-only flow', 'Positional flow (guard only)', 'Slow motion rolling'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'low',
    rule_constraints: [
      { type: 'performer', description: 'Maximum 30% resistance. Catch and release.' },
      { type: 'task', description: 'Focus on smooth transitions, not winning' },
    ],
    technique_ids: [],
  },
  {
    name: 'Grappling-Specific Stretching',
    description: 'Hip flexors, hamstrings, groin, shoulders, neck. Hold each stretch 30+ seconds. Essential for injury prevention.',
    position: 'other',
    topic: 'Recovery',
    difficulty: 'beginner',
    category: 'cooldown',
    duration_minutes: 8,
    techniques: ['pigeon stretch', 'butterfly stretch', 'shoulder stretches'],
    variations: ['Partner-assisted stretches', 'Yoga flow style', 'Focus on problem areas'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'low',
    rule_constraints: [
      { type: 'performer', description: 'Hold each stretch minimum 30 seconds, breathe deeply' },
    ],
    technique_ids: [],
  },
  {
    name: 'Breathing & Visualization',
    description: 'Box breathing (4-4-4-4), then 2 minutes of match visualization. Mental game training.',
    position: 'other',
    topic: 'Mental Training',
    difficulty: 'beginner',
    category: 'cooldown',
    duration_minutes: 5,
    techniques: ['breathing', 'visualization', 'mental prep'],
    variations: ['Guided visualization', 'Competition scenario focus', 'Relaxation only'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'low',
    rule_constraints: [
      { type: 'performer', description: 'Eyes closed, controlled breathing throughout' },
    ],
    technique_ids: [],
  },
  {
    name: 'Position Review & Q/A',
    description: 'Coach reviews key positions from class. Students ask questions. Troubleshoot common problems.',
    position: 'other',
    topic: 'Review',
    difficulty: 'beginner',
    category: 'cooldown',
    duration_minutes: 5,
    techniques: ['review'],
    variations: ['Student-led review', 'Partner quiz each other', 'Video review if available'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'low',
    rule_constraints: [],
    technique_ids: [],
  },
  {
    name: 'Light Positional Cycling',
    description: 'Start in mount, escape to guard, sweep to mount, give up back, escape. Continuous cycling through positions at low intensity.',
    position: 'other',
    topic: 'Transitions',
    difficulty: 'beginner',
    category: 'cooldown',
    duration_minutes: 6,
    techniques: ['transitions', 'escapes', 'sweeps'],
    variations: ['Add specific techniques at each position', 'One person leads', 'Alternate who attacks'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'low',
    rule_constraints: [
      { type: 'performer', description: 'Low intensity, focus on smooth transitions' },
      { type: 'task', description: 'Cycle: mount > guard > sweep > side control > guard > back > escape > repeat' },
    ],
    technique_ids: [],
  },

  // ══════════════════════════════════════════════════════════
  // CLA WARMUP GAMES — Greg Souders / Kit Dale Style
  // ══════════════════════════════════════════════════════════
  {
    name: 'BJJ Tag - Knee Touch',
    description: 'Stand-up tag game. Score by touching opponents knees while defending your own. Develops level change, hand fighting, and reaction speed.',
    position: 'standing',
    topic: 'Movement',
    difficulty: 'beginner',
    category: 'warmup',
    duration_minutes: 5,
    techniques: ['level change', 'hand fighting', 'sprawl'],
    variations: ['Must use specific hand (left only)', 'Touch ankles instead', 'Both knees = win'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Score by touching opponents knees. First to 5 touches wins.' },
      { type: 'environmental', description: 'Stay within a 3m circle' },
    ],
    technique_ids: [],
  },
  {
    name: 'BJJ Tag - Back Touch',
    description: 'Touch opponents back while protecting yours. Develops angle creation, circling, and head position concepts. CLA: naturally teaches off-balancing.',
    position: 'standing',
    topic: 'Movement',
    difficulty: 'beginner',
    category: 'warmup',
    duration_minutes: 5,
    techniques: ['circling', 'angle creation', 'arm drag concepts'],
    variations: ['Must slap with alternating hands', 'Must touch with both hands simultaneously', 'Add takedown once back is touched'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Score by touching opponents back. Defend your own back.' },
      { type: 'performer', description: 'No gripping the gi or clothing' },
    ],
    technique_ids: [],
  },
  {
    name: 'Sumo Wrestling',
    description: 'Start in small circle. Win by pushing opponent out or making them touch anything other than feet to ground. Develops base, pressure, and clinch concepts.',
    position: 'standing',
    topic: 'Balance',
    difficulty: 'beginner',
    category: 'warmup',
    duration_minutes: 6,
    techniques: ['base', 'pressure', 'underhook', 'body lock'],
    variations: ['One hand behind back', 'No underhooks allowed', 'Start back-to-back'],
    environment_tags: ['nogi', 'gi', 'wrestling'],
    intensity: 'high',
    rule_constraints: [
      { type: 'environmental', description: 'Circle of about 2m diameter' },
      { type: 'task', description: 'Push opponent out of circle or make them touch ground with anything other than feet' },
    ],
    technique_ids: [],
  },
  {
    name: 'Foot Sweep Tag',
    description: 'Light foot sweeps only. Score by making opponent stumble or step. Develops timing, distance management, and judo-style ashi-waza concepts.',
    position: 'standing',
    topic: 'Foot Sweeps',
    difficulty: 'beginner',
    category: 'warmup',
    duration_minutes: 5,
    techniques: ['foot sweep', 'timing', 'balance'],
    variations: ['Only inside sweeps', 'Only outside sweeps', 'Add collar grip'],
    environment_tags: ['gi', 'judo'],
    intensity: 'low',
    rule_constraints: [
      { type: 'task', description: 'Score with clean foot sweep only. No hand throws.' },
      { type: 'performer', description: 'Light contact only. Goal is timing not power.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Partner Mirror Game',
    description: 'One person leads, other mirrors their movements. Develops reaction speed, spatial awareness, and movement patterns. Switch leader every 30 seconds.',
    position: 'other',
    topic: 'Movement',
    difficulty: 'beginner',
    category: 'warmup',
    duration_minutes: 5,
    techniques: ['movement patterns', 'reaction time', 'spatial awareness'],
    variations: ['Add wrestling level changes', 'Include ground transitions', 'Eyes closed for leader'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'low',
    rule_constraints: [
      { type: 'task', description: 'Follower must mirror leaders movements as closely as possible' },
      { type: 'environmental', description: 'Switch leader every 30 seconds' },
    ],
    technique_ids: [],
  },
  {
    name: 'Balance Challenge - One Foot',
    description: 'Both standing on one foot. Push, pull, and off-balance opponent to make them put second foot down. Develops base and balance under pressure.',
    position: 'standing',
    topic: 'Balance',
    difficulty: 'beginner',
    category: 'warmup',
    duration_minutes: 4,
    techniques: ['balance', 'base', 'off-balancing'],
    variations: ['Hands behind back, use chest only', 'Hold collar tie while balancing', 'Switch standing foot each round'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'low',
    rule_constraints: [
      { type: 'performer', description: 'Must stay on one foot at all times' },
      { type: 'task', description: 'Make opponent put their second foot down or fall' },
    ],
    technique_ids: [],
  },
  {
    name: 'Chain Wrestling Warm-Up',
    description: 'Continuous low-intensity chain wrestling. Single > sprawl > re-shot > front headlock > snap down. Flow between attacks and defenses without stopping.',
    position: 'standing',
    topic: 'Wrestling',
    difficulty: 'intermediate',
    category: 'warmup',
    duration_minutes: 6,
    techniques: ['single leg', 'sprawl', 're-shot', 'snap down'],
    variations: ['Add guard pull option', 'Must alternate attacker each exchange', 'No double legs'],
    environment_tags: ['nogi', 'wrestling'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'performer', description: '50% resistance. Flow pace, not competition pace.' },
      { type: 'task', description: 'Continuous wrestling chains. Never stop moving.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Seated Guard Musical Chairs',
    description: 'One person seated, one standing. Standing player circles. When coach says go, seated player must engage. Develops seated guard entries under time pressure.',
    position: 'open-guard',
    topic: 'Seated Guard',
    difficulty: 'beginner',
    category: 'warmup',
    duration_minutes: 5,
    techniques: ['seated guard', 'guard pull', 'shin-to-shin'],
    variations: ['Standing player can attack when coach says go', 'Must sweep within 10 seconds', 'Both start seated'],
    environment_tags: ['nogi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'environmental', description: 'React to coaches signal' },
      { type: 'task', description: 'Seated player must engage and attack immediately on signal' },
    ],
    technique_ids: [],
  },

  // ══════════════════════════════════════════════════════════
  // CLA MAIN GAMES — Greg Souders Constraint Methodology
  // ══════════════════════════════════════════════════════════
  {
    name: 'Sweep-Only Guard Game',
    description: 'Guard player can ONLY sweep (no submissions). Passer can pass freely. Task constraint forces guard player to focus on off-balancing and sweep mechanics.',
    position: 'guard',
    topic: 'Sweeps',
    difficulty: 'beginner',
    category: 'main',
    duration_minutes: 10,
    techniques: ['sweeps', 'off-balance', 'hip movement'],
    variations: ['Add submission option after 3 sweep attempts', 'Must sweep within 30 seconds', 'Only butterfly sweeps'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Guard player can ONLY sweep. No submissions allowed.' },
      { type: 'task', description: 'Passer can pass and submit freely.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Contact-Only Passing',
    description: 'Passer must maintain chest-to-chest or chest-to-back contact at all times. Forces pressure passing behavior without explicit instruction. CLA attractor game.',
    position: 'guard',
    topic: 'Pressure Passing',
    difficulty: 'intermediate',
    category: 'main',
    duration_minutes: 10,
    techniques: ['body lock pass', 'over-under', 'pressure passing'],
    variations: ['Guard player also must maintain contact', 'Allow brief 1-second breaks', 'Start from body lock position'],
    environment_tags: ['nogi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'Passer must maintain torso contact at ALL times. Any break = reset.' },
      { type: 'environmental', description: 'Guard player can use any guard' },
    ],
    technique_ids: [],
  },
  {
    name: 'Small Mat Passing',
    description: 'Guard battle on a very small mat area (2m x 2m). Environmental constraint forces engagement and prevents running. Develops tight passing and guard retention.',
    position: 'guard',
    topic: 'Guard Passing',
    difficulty: 'intermediate',
    category: 'main',
    duration_minutes: 10,
    techniques: ['tight passing', 'guard retention', 'sweeps'],
    variations: ['Shrink the mat further as rounds progress', 'Start from specific guard', 'Sub-only on the small mat'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'environmental', description: 'Restrict to a 2m x 2m area. Out of bounds = reset.' },
      { type: 'task', description: 'Normal guard passing rules. Stay in bounds.' },
    ],
    technique_ids: [],
  },
  {
    name: 'One-Arm Guard Game',
    description: 'Guard player can only use one arm. Performer constraint forces reliance on legs and hips. Develops leg-based guard retention and hip movement.',
    position: 'guard',
    topic: 'Guard Retention',
    difficulty: 'intermediate',
    category: 'main',
    duration_minutes: 8,
    techniques: ['guard retention', 'hip movement', 'leg pummeling'],
    variations: ['Passer also loses one arm', 'Switch arms halfway', 'No arms at all (advanced)'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'performer', description: 'Guard player tucks one arm in belt/waistband. Cannot use it.' },
      { type: 'task', description: 'Guard player must retain guard using only legs and one arm.' },
    ],
    technique_ids: [],
  },
  {
    name: 'No Grips Passing Game',
    description: 'Passer cannot grip opponents body at all. Must pass using only pressure, movement, and position. Forces development of body position and timing over grip-dependent techniques.',
    position: 'guard',
    topic: 'Guard Passing',
    difficulty: 'advanced',
    category: 'main',
    duration_minutes: 8,
    techniques: ['pressure passing', 'float passing', 'timing'],
    variations: ['Guard player also cannot grip', 'Passer can grip below knees only', 'Both players no grips'],
    environment_tags: ['nogi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'performer', description: 'Passer cannot grip or grab opponents body. Open hands only.' },
      { type: 'task', description: 'Must pass using position, pressure, and movement only.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Time Pressure Sweep Game',
    description: 'Guard player has 30 seconds to sweep or submit. Clock resets on success. Creates urgency and forces aggressive bottom game. CLA time constraint.',
    position: 'guard',
    topic: 'Sweeps',
    difficulty: 'intermediate',
    category: 'main',
    duration_minutes: 10,
    techniques: ['sweeps', 'urgency', 'aggressive guard'],
    variations: ['20 second limit (advanced)', '45 seconds (beginners)', 'Must sweep from specific guard'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'environmental', description: '30 second clock per attempt. Failure = top player scores.' },
      { type: 'task', description: 'Guard player must sweep or submit within time limit.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Escape Ladder',
    description: 'Start in worst position (back mount). Escape to mount bottom. Escape to side control bottom. Escape to guard. Full escape sequence. CLA progressive overload.',
    position: 'back',
    topic: 'Escapes',
    difficulty: 'intermediate',
    category: 'main',
    duration_minutes: 12,
    techniques: ['back escape', 'mount escape', 'side control escape', 'guard recovery'],
    variations: ['Start from different worst position', 'Time limit per stage', 'Opponent increases resistance at each stage'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'Must escape each position in sequence. Top player tries to maintain or re-take.' },
      { type: 'performer', description: 'Top player works at 70-80% intensity' },
    ],
    technique_ids: [],
  },
  {
    name: 'Submission Chain Game',
    description: 'Must attempt 3 different submissions before repeating any. Forces chaining attacks and developing a diverse submission game.',
    position: 'mount',
    topic: 'Submissions',
    difficulty: 'intermediate',
    category: 'main',
    duration_minutes: 10,
    techniques: ['submission chains', 'transitions', 'attack variety'],
    variations: ['Must chain from the same position', 'Can transition positions between subs', 'Start from different dominant positions'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Must attempt 3 DIFFERENT submissions before repeating any submission.' },
      { type: 'performer', description: 'Hold each submission attempt for 3 seconds before transitioning.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Guard Retention Progressive Overload',
    description: 'Guard player retains guard against progressively harder constraints: 1) passer walks, 2) passer jogs, 3) passer full speed, 4) passer submits too. CLA scaling.',
    position: 'guard',
    topic: 'Guard Retention',
    difficulty: 'intermediate',
    category: 'main',
    duration_minutes: 12,
    techniques: ['guard retention', 'frames', 'hip movement', 'leg pummeling'],
    variations: ['Start from butterfly', 'Start from closed guard that gets opened', 'Add reset after each pass'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'environmental', description: 'Progressive rounds: 1) walking pace, 2) 50%, 3) 75%, 4) 100% with subs' },
      { type: 'task', description: 'Guard player focuses purely on retention. No sweeps or subs.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Attractor Landscape - Underhook Discovery',
    description: 'Positional sparring from half guard. No technique instruction. Constraint: bottom player scores by getting to dog fight. Natural discovery of underhook as key movement solution.',
    position: 'half-guard',
    topic: 'Half Guard',
    difficulty: 'beginner',
    category: 'main',
    duration_minutes: 10,
    techniques: ['underhook', 'dog fight', 'half guard'],
    variations: ['Start without underhook', 'Start with underhook already won', 'Top player can only crossface'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Bottom player scores by reaching dog fight (both on knees with underhook).' },
      { type: 'task', description: 'Top player scores by flattening bottom player or passing.' },
    ],
    technique_ids: [],
  },

  // ══════════════════════════════════════════════════════════
  // KIT DALE CONCEPT GAMES
  // ══════════════════════════════════════════════════════════
  {
    name: 'Concept Game: Pressure vs Movement',
    description: 'Kit Dale style concept exploration. Top player uses only pressure (no grips). Bottom uses only movement (no frames). Discover how pressure and movement interact.',
    position: 'side-control',
    topic: 'Concepts',
    difficulty: 'intermediate',
    category: 'main',
    duration_minutes: 8,
    techniques: ['pressure', 'movement', 'hip escape', 'weight distribution'],
    variations: ['Switch roles', 'Add one grip allowed', 'Both restrictions simultaneously'],
    environment_tags: ['nogi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'performer', description: 'Top: no grips, only body pressure. Bottom: no frames, only movement.' },
      { type: 'task', description: 'Top maintains position. Bottom escapes.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Concept Game: Leverage Discovery',
    description: 'What-if game: can you sweep using only your legs? No arm grips allowed. Forces discovery of leverage principles through hip and leg movements.',
    position: 'guard',
    topic: 'Leverage',
    difficulty: 'intermediate',
    category: 'main',
    duration_minutes: 8,
    techniques: ['leverage', 'hip movement', 'leg-based sweeps'],
    variations: ['Can use only one leg', 'Arms crossed on chest', 'Opponent also cannot use arms'],
    environment_tags: ['nogi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'performer', description: 'Guard player cannot grip or use arms. Hands behind back or on own chest.' },
      { type: 'task', description: 'Guard player must sweep using only legs and hips.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Concept Game: Timing Windows',
    description: 'Kit Dale timing exploration. Sweep is only valid in the first 3 seconds after passer changes position. Forces recognition of transition moments.',
    position: 'guard',
    topic: 'Timing',
    difficulty: 'advanced',
    category: 'main',
    duration_minutes: 10,
    techniques: ['timing', 'transitions', 'sweep recognition'],
    variations: ['Shorter window (2 seconds)', 'Apply to submissions too', 'Coach calls the windows'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Sweep attempts only valid in the first 3 seconds after opponent shifts position.' },
      { type: 'environmental', description: 'Coach or partner signals when position changes occur.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Problem Solving Game: How Many Ways?',
    description: 'Start in a specific position. Each round, must find a DIFFERENT solution (sweep, escape, submission). How many unique solutions can you find in 10 rounds?',
    position: 'other',
    topic: 'Problem Solving',
    difficulty: 'intermediate',
    category: 'main',
    duration_minutes: 12,
    techniques: ['creativity', 'problem solving', 'varied techniques'],
    variations: ['Same position entire time', 'Different start position each round', 'Partner rates each solution'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Must use a DIFFERENT technique each round. No repeats.' },
      { type: 'environmental', description: '1-minute rounds, 10 rounds total. Count unique solutions.' },
    ],
    technique_ids: [],
  },

  // ══════════════════════════════════════════════════════════
  // COACH-SYSTEM-SPECIFIC DRILLS
  // ══════════════════════════════════════════════════════════
  {
    name: 'Gordon Ryan Body Lock Passing Drill',
    description: 'Start standing over seated guard. Must close distance, achieve body lock, and pass. Systematic approach: control hips > body lock > pressure pass.',
    position: 'guard',
    topic: 'Body Lock Passing',
    difficulty: 'advanced',
    category: 'drill',
    duration_minutes: 10,
    techniques: ['body lock pass', 'over-under', 'pressure'],
    variations: ['Must pass left side only', 'Guard player starts in butterfly', 'Add leg drag option'],
    environment_tags: ['nogi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'Must achieve body lock before passing. No speed passes.' },
      { type: 'performer', description: 'Methodical, pressure-based. No rushing.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Craig Jones Leg Lock Entry Game',
    description: 'Start from seated guard vs standing. Score by entering any leg entanglement and holding for 3 seconds. No finishes. Focus on entries only.',
    position: 'guard',
    topic: 'Leg Lock Entries',
    difficulty: 'advanced',
    category: 'drill',
    duration_minutes: 10,
    techniques: ['SLX entry', 'ashi garami', 'inside sankaku', 'K guard'],
    variations: ['Entries from half guard only', 'Must enter from Z guard', 'Allow finishes for advanced'],
    environment_tags: ['nogi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Score by holding any leg entanglement for 3 seconds. No finishes.' },
      { type: 'performer', description: 'Controlled entries. No cranking.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Lachlan Giles K-Guard Entry Game',
    description: 'Start from open guard. Goal is to enter K-guard position. Partner stands and tries to pass. Focus on inversion timing and hook placement.',
    position: 'open-guard',
    topic: 'K-Guard',
    difficulty: 'advanced',
    category: 'drill',
    duration_minutes: 8,
    techniques: ['K guard', 'inversion', 'leg entanglement entry'],
    variations: ['Must enter K-guard to specific side', 'Chain to backside 50/50', 'Partner adds leg lock defense'],
    environment_tags: ['nogi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Score by achieving K-guard position with proper hooks for 3 seconds.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Danaher Pin System Game',
    description: 'Top player tries to maintain side control, advance to mount, then advance to back. Bottom player tries to escape at each stage. Positional hierarchy training.',
    position: 'side-control',
    topic: 'Pin Progression',
    difficulty: 'intermediate',
    category: 'drill',
    duration_minutes: 10,
    techniques: ['side control', 'mount transition', 'back take', 'escapes'],
    variations: ['Start from knee on belly', 'Must submit from mount before taking back', 'Time limit per position'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'Top player: side control > mount > back. Score for each advancement.' },
      { type: 'task', description: 'Bottom player: escape to guard at any stage.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Back Attack Cycling',
    description: 'Start with back control. Attacker cycles through RNC > armbar > triangle > collar choke. Defender blocks each. Focus on transitioning between attacks.',
    position: 'back',
    topic: 'Back Attack Chains',
    difficulty: 'intermediate',
    category: 'drill',
    duration_minutes: 10,
    techniques: ['RNC', 'armbar from back', 'back triangle', 'collar choke'],
    variations: ['Defender can escape after blocking 3 attacks', 'Must chain at least 2 attacks', 'Add crucifix entries'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Attacker must attempt different submissions. Rotate through attack options.' },
      { type: 'performer', description: 'Defender blocks but stays in position. Attacker keeps control while cycling.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Mount Escape Ladder',
    description: 'Start in mount bottom. Must chain escape attempts: trap & roll > if blocked > elbow-knee > if blocked > heel drag > if blocked > bridge to back. Progressive escape chain.',
    position: 'mount',
    topic: 'Mount Escapes',
    difficulty: 'beginner',
    category: 'drill',
    duration_minutes: 8,
    techniques: ['trap and roll', 'elbow-knee escape', 'heel drag', 'bridge'],
    variations: ['Start from high mount', 'Add mount retention drill for top', 'Time each escape attempt'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Bottom player must chain escape attempts. If one fails, immediately try next option.' },
      { type: 'performer', description: 'Top player resists at 70%. Allows escape after 3-4 attempts.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Scramble Sprint Rounds',
    description: 'Start tangled in a random position. Coach says go. First to establish and hold dominant position for 3 seconds wins. Quick resets. Develops scramble instincts.',
    position: 'other',
    topic: 'Scrambles',
    difficulty: 'intermediate',
    category: 'main',
    duration_minutes: 10,
    techniques: ['scrambles', 'transitions', 'reversals', 'base'],
    variations: ['Start from specific scramble position', 'Must stand up first', 'Winning position is back control only'],
    environment_tags: ['nogi', 'wrestling'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'First to hold dominant position (mount, back, side control) for 3 seconds wins.' },
      { type: 'environmental', description: '30-second rounds. Quick resets.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Headquarters Passing Drill',
    description: 'Passer starts in headquarters position (one knee in, one out). Must pass from HQ using any technique. Guard player can sweep or submit. Danaher system drill.',
    position: 'guard',
    topic: 'Headquarters Passing',
    difficulty: 'intermediate',
    category: 'drill',
    duration_minutes: 10,
    techniques: ['headquarters', 'knee cut', 'long step', 'backstep'],
    variations: ['Only knee cut allowed', 'Must backstep at least once', 'Guard player starts in butterfly'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Passer must start from and return to headquarters position between pass attempts.' },
    ],
    technique_ids: [],
  },

  // ══════════════════════════════════════════════════════════
  // ADDITIONAL POSITIONAL SPARRING
  // ══════════════════════════════════════════════════════════
  {
    name: '50/50 Guard Battle',
    description: 'Start in 50/50. Both players attack and defend equally. Sweep, submit, or escape. Develops 50/50 awareness and leg lock defense.',
    position: 'guard',
    topic: '50/50 Guard',
    difficulty: 'advanced',
    category: 'positional',
    duration_minutes: 8,
    techniques: ['50/50 sweeps', 'heel hook', '50/50 escape', 'knee bar'],
    variations: ['No heel hooks (straight ankle only)', 'Must escape 50/50 to score', 'Sub-only in 50/50'],
    environment_tags: ['nogi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Start in 50/50. Score by sweeping, submitting, or cleanly escaping.' },
      { type: 'performer', description: 'Controlled leg lock attacks. Catch and release for drilling.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Butterfly Guard Wars',
    description: 'Both seated in butterfly guard. First to sweep wins the round. Develops the seated guard battle that defines modern nogi competition.',
    position: 'open-guard',
    topic: 'Butterfly Guard',
    difficulty: 'intermediate',
    category: 'positional',
    duration_minutes: 10,
    techniques: ['butterfly sweep', 'arm drag', 'snap down', 'single leg X'],
    variations: ['One seated one standing', 'Must sweep to specific side', 'Add guillotine option'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Both start seated. First to sweep or take back wins the round.' },
      { type: 'environmental', description: '1-minute rounds with quick resets.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Spider/Lasso Guard Positional (Gi)',
    description: 'Guard player must use spider or lasso guard only. Passer works to strip grips and pass. Develops gi-specific guard skills.',
    position: 'open-guard',
    topic: 'Gi Guard',
    difficulty: 'intermediate',
    category: 'positional',
    duration_minutes: 10,
    techniques: ['spider guard', 'lasso guard', 'grip fighting', 'triangle'],
    variations: ['Spider only (no lasso)', 'Lasso only', 'Allow DLR transitions'],
    environment_tags: ['gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Guard player must maintain spider or lasso grip. Passer passes freely.' },
      { type: 'environmental', description: 'Gi only. Grip fighting is the game.' },
    ],
    technique_ids: [],
  },
  {
    name: 'North-South Escape Game',
    description: 'Start in north-south bottom. Escape to any guard position. Top player hunts kimura and north-south choke while maintaining control.',
    position: 'side-control',
    topic: 'North-South',
    difficulty: 'intermediate',
    category: 'positional',
    duration_minutes: 8,
    techniques: ['north-south escape', 'north-south choke', 'kimura', 'ghost escape'],
    variations: ['Top can only use north-south choke', 'Bottom must bridge first', 'Add time pressure'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'Start in north-south. Top attacks/maintains. Bottom escapes to any guard.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Crucifix Attack/Defense',
    description: 'Start in crucifix position. Attacker works submissions (neck cranks, chokes, armbars). Defender works to free arms and escape. Rare but devastating position.',
    position: 'back',
    topic: 'Crucifix',
    difficulty: 'advanced',
    category: 'positional',
    duration_minutes: 8,
    techniques: ['crucifix choke', 'crucifix armbar', 'crucifix escape'],
    variations: ['Must enter crucifix from turtle first', 'Gi-specific collar attacks', 'Defense focus only'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Start in crucifix. Attacker submits, defender escapes.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Deep Half Guard Positional',
    description: 'Start in deep half guard. Bottom sweeps, top tries to extract and pass. Develops the deep half game - a key position at all levels.',
    position: 'half-guard',
    topic: 'Deep Half Guard',
    difficulty: 'intermediate',
    category: 'positional',
    duration_minutes: 10,
    techniques: ['deep half sweep', 'waiter sweep', 'deep half escape', 'counter'],
    variations: ['Must use waiter sweep', 'Top can back step to leg lock', 'Start from knee shield transition'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Start in deep half. Bottom sweeps, top extracts and passes.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Kimura System Positional',
    description: 'Top player hunts kimura from any position (side, mount, north-south). Bottom defends. If kimura is defended, top uses it as a control grip to advance position.',
    position: 'side-control',
    topic: 'Kimura System',
    difficulty: 'intermediate',
    category: 'positional',
    duration_minutes: 10,
    techniques: ['kimura', 'kimura trap', 'mount transition', 'back take'],
    variations: ['Only from side control', 'Add north-south kimura', 'Bottom can counter with own kimura'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'medium',
    rule_constraints: [
      { type: 'task', description: 'Top player must use kimura grip as primary control and attack.' },
      { type: 'task', description: 'Top scores with kimura finish, mount advancement, or back take off kimura threat.' },
    ],
    technique_ids: [],
  },
  {
    name: 'Stand-Up to Guard Pull Game',
    description: 'One person wants to take down, other wants to pull guard. Realistic competition scenario. Teaches both wrestling and guard pulling integration.',
    position: 'standing',
    topic: 'Takedowns vs Guard Pull',
    difficulty: 'intermediate',
    category: 'main',
    duration_minutes: 10,
    techniques: ['takedown', 'guard pull', 'snap down', 'sprawl'],
    variations: ['Switch roles each round', 'Must get takedown to top position (no guard pull option)', 'Time limit before pull'],
    environment_tags: ['nogi', 'gi'],
    intensity: 'high',
    rule_constraints: [
      { type: 'task', description: 'Player A must take down. Player B must pull guard and immediately sweep/attack.' },
      { type: 'environmental', description: '90-second rounds. Switch roles.' },
    ],
    technique_ids: [],
  },
]
