import type { ClassPrepFormData } from '@/types/database'

// ═══════════════════════════════════════════════════════════
// CLASS SESSIONS - Structured using CLA Arc
// Each session follows: Movement Prep > Technique > Guided Discovery > Open Play > Cool Down
// ═══════════════════════════════════════════════════════════

// Note: game_ids will be populated after games are seeded
// These sessions define the structure - game linking happens in the seed page

export const sessions: ClassPrepFormData[] = [
  // ── WEEK 1: CLOSED GUARD FUNDAMENTALS ──────────────────
  {
    name: 'Week 1 Mon - Closed Guard Offense (Gi)',
    description: 'Hip bump sweep, scissor sweep, kimura/guillotine chain from closed guard. CLA arc.',
    date: '2026-02-16',
    duration_minutes: 90,
    focus: 'Closed Guard Sweeps & Submissions',
    skill_level: 'beginner',
    game_ids: [],
    notes: 'Focus on the hip bump > kimura > guillotine chain. Let students discover the connections.',
  },
  {
    name: 'Week 1 Wed - Mount Escapes & Control (Gi)',
    description: 'Trap & roll, elbow-knee escape, mount control from top. Both sides of the position.',
    date: '2026-02-18',
    duration_minutes: 90,
    focus: 'Mount',
    skill_level: 'beginner',
    game_ids: [],
    notes: 'Spend extra time on mount retention. Top players need to ride the buck before attacking.',
  },
  {
    name: 'Week 1 Fri - Nogi Takedowns & Guard Pulls',
    description: 'Double leg, single leg, snap down, guard pull entries. Standing to ground transitions.',
    date: '2026-02-20',
    duration_minutes: 90,
    focus: 'Takedowns',
    skill_level: 'beginner',
    game_ids: [],
    notes: 'Nogi class. Emphasize level change and penetration step. Guard pull as backup option.',
  },

  // ── WEEK 2: HALF GUARD & PASSING ──────────────────────
  {
    name: 'Week 2 Mon - Half Guard Bottom (Gi)',
    description: 'Knee shield, underhook battle, dog fight to back take, John Wayne sweep.',
    date: '2026-02-23',
    duration_minutes: 90,
    focus: 'Half Guard Bottom',
    skill_level: 'intermediate',
    game_ids: [],
    notes: 'The underhook is EVERYTHING in half guard. Drill the pummel extensively.',
  },
  {
    name: 'Week 2 Wed - Guard Passing Fundamentals (Gi)',
    description: 'Toreando, knee cut, stack pass. Headquarters position. Systematic approach to passing.',
    date: '2026-02-25',
    duration_minutes: 90,
    focus: 'Guard Passing',
    skill_level: 'intermediate',
    game_ids: [],
    notes: 'Introduce headquarters concept. Every pass branches from HQ. Danaher system.',
  },
  {
    name: 'Week 2 Fri - Nogi Body Lock Passing',
    description: 'Body lock pass, over-under pass, leg drag. Modern nogi pressure passing system.',
    date: '2026-02-27',
    duration_minutes: 90,
    focus: 'Nogi Passing',
    skill_level: 'intermediate',
    game_ids: [],
    notes: 'Gordon Ryan style. Close distance, lock body lock, methodical pressure. No rushing.',
  },

  // ── WEEK 3: BACK ATTACKS ──────────────────────────────
  {
    name: 'Week 3 Mon - Back Takes from Everywhere (Both)',
    description: 'Arm drag to back, gift wrap from mount, turtle back take. Multiple entries into back control.',
    date: '2026-03-02',
    duration_minutes: 90,
    focus: 'Back Takes',
    skill_level: 'intermediate',
    game_ids: [],
    notes: 'The back is the highest percentage finishing position. Every position should have a back take path.',
  },
  {
    name: 'Week 3 Wed - Back Attack System (Both)',
    description: 'Seatbelt control, RNC short choke, bow & arrow (gi), armbar from back. Complete back system.',
    date: '2026-03-04',
    duration_minutes: 90,
    focus: 'Back Attacks',
    skill_level: 'intermediate',
    game_ids: [],
    notes: 'Danaher system: control first, then attack. Seatbelt > body triangle > attack cycle.',
  },
  {
    name: 'Week 3 Fri - Nogi Back Escapes & Defense',
    description: 'Back escape fundamentals. Clear hooks, fight hands, turn in. Survival skills.',
    date: '2026-03-06',
    duration_minutes: 90,
    focus: 'Back Escapes',
    skill_level: 'intermediate',
    game_ids: [],
    notes: 'If you cant escape the back, you will get choked. Survival position, hand fighting, escape sequences.',
  },

  // ── WEEK 4: OPEN GUARD & SWEEPS ───────────────────────
  {
    name: 'Week 4 Mon - Butterfly Guard System (Both)',
    description: 'Butterfly elevations, arm drag series, SLX & X guard entries from butterfly.',
    date: '2026-03-09',
    duration_minutes: 90,
    focus: 'Butterfly Guard',
    skill_level: 'intermediate',
    game_ids: [],
    notes: 'Butterfly is the gateway to modern guard. Entry point to entire leg entanglement system.',
  },
  {
    name: 'Week 4 Wed - Gi Guard: DLR & RDLR',
    description: 'De La Riva hooks, RDLR entries, berimbolo concept, kiss of the dragon back take.',
    date: '2026-03-11',
    duration_minutes: 90,
    focus: 'DLR System',
    skill_level: 'advanced',
    game_ids: [],
    notes: 'Modern gi guard system. DLR is the foundation of advanced gi guard play.',
  },
  {
    name: 'Week 4 Fri - Nogi Seated Guard & Wrestling Up',
    description: 'Seated guard entries, shin-to-shin, wrestling up, single leg from seated. Complete seated game.',
    date: '2026-03-13',
    duration_minutes: 90,
    focus: 'Seated Guard',
    skill_level: 'intermediate',
    game_ids: [],
    notes: 'Nogi seated guard is essential. Must be able to stand up OR attack from seated.',
  },

  // ── WEEK 5: LEG LOCKS ────────────────────────────────
  {
    name: 'Week 5 Mon - Leg Lock Foundations (Nogi)',
    description: 'Ashi garami positions, straight ankle lock, positional hierarchy. Safe leg lock practice.',
    date: '2026-03-16',
    duration_minutes: 90,
    focus: 'Leg Lock Basics',
    skill_level: 'intermediate',
    game_ids: [],
    notes: 'SAFETY FIRST. Teach positions before submissions. Tapping etiquette for leg locks.',
  },
  {
    name: 'Week 5 Wed - Inside Sankaku & Heel Hooks (Nogi)',
    description: 'Inside sankaku (411/saddle) entries, inside heel hook mechanics, outside heel hook from cross ashi.',
    date: '2026-03-18',
    duration_minutes: 90,
    focus: 'Heel Hooks',
    skill_level: 'advanced',
    game_ids: [],
    notes: 'Advanced students only. Danaher/Craig Jones system. Controlled environment, catch and release drilling.',
  },
  {
    name: 'Week 5 Fri - Leg Lock Defense & Escapes (Nogi)',
    description: 'Boot defense, hitchhiker escape, clearing entanglements. Survival and escape from leg locks.',
    date: '2026-03-20',
    duration_minutes: 90,
    focus: 'Leg Lock Defense',
    skill_level: 'intermediate',
    game_ids: [],
    notes: 'Everyone needs leg lock defense, even if they dont attack legs. Modern meta requirement.',
  },

  // ── WEEK 6: SIDE CONTROL & SUBMISSIONS ────────────────
  {
    name: 'Week 6 Mon - Side Control Mastery (Gi)',
    description: 'Crossface control, kesa gatame, kimura, americana, arm triangle. Complete side control.',
    date: '2026-03-23',
    duration_minutes: 90,
    focus: 'Side Control',
    skill_level: 'intermediate',
    game_ids: [],
    notes: 'Side control is where you BREAK opponents. Pressure, then submissions. Never rush.',
  },
  {
    name: 'Week 6 Wed - Front Headlock & Guillotine System (Both)',
    description: 'Snap down to front headlock, guillotine variations, darce, anaconda. Complete front headlock game.',
    date: '2026-03-25',
    duration_minutes: 90,
    focus: 'Front Headlock',
    skill_level: 'intermediate',
    game_ids: [],
    notes: 'The guillotine is the guard players takedown defense. Every guard puller needs this.',
  },
  {
    name: 'Week 6 Fri - Nogi Competition Prep',
    description: 'Full rounds: takedowns to finish. Competition simulation. Point scoring scenarios.',
    date: '2026-03-27',
    duration_minutes: 90,
    focus: 'Competition Prep',
    skill_level: 'intermediate',
    game_ids: [],
    notes: 'Simulate competition. Timed rounds, point tracking, referee decisions. Build competition mindset.',
  },

  // ── WEEK 7: TURTLE & TRANSITIONS ──────────────────────
  {
    name: 'Week 7 Mon - Turtle Attacks & Escapes (Both)',
    description: 'Turtle breakdown, back take from turtle, sit outs, granby rolls. Complete turtle game.',
    date: '2026-03-30',
    duration_minutes: 90,
    focus: 'Turtle',
    skill_level: 'intermediate',
    game_ids: [],
    notes: 'Turtle is an underserved position. Many people end up here and dont know what to do.',
  },
  {
    name: 'Week 7 Wed - Transition Game (Both)',
    description: 'Chain attacks across positions. Mount to back, side control to mount, guard to sweep to pass.',
    date: '2026-04-01',
    duration_minutes: 90,
    focus: 'Transitions',
    skill_level: 'intermediate',
    game_ids: [],
    notes: 'The best grapplers chain positions. Teach flowing between dominant positions.',
  },
  {
    name: 'Week 7 Fri - Nogi Scramble Training',
    description: 'Scramble situations, hand fighting, getting up from bottom, explosive transitions.',
    date: '2026-04-03',
    duration_minutes: 90,
    focus: 'Scrambles',
    skill_level: 'intermediate',
    game_ids: [],
    notes: 'Scrambles win matches. Train the chaos. Ruotolo brothers style.',
  },

  // ── WEEK 8: REVIEW & COMPETITION ──────────────────────
  {
    name: 'Week 8 Mon - Gi Review: Complete Game',
    description: 'Review all gi techniques from the cycle. Fill gaps. Student choice drilling.',
    date: '2026-04-06',
    duration_minutes: 90,
    focus: 'Review',
    skill_level: 'intermediate',
    game_ids: [],
    notes: 'Let students choose what to review. Address individual weaknesses.',
  },
  {
    name: 'Week 8 Wed - Nogi Review: Complete Game',
    description: 'Review all nogi techniques. Leg lock system review. Competition Q&A.',
    date: '2026-04-08',
    duration_minutes: 90,
    focus: 'Review',
    skill_level: 'intermediate',
    game_ids: [],
    notes: 'Final review before the cycle restarts. Identify what stuck and what needs more work.',
  },
  {
    name: 'Week 8 Fri - In-House Tournament',
    description: 'In-house round robin tournament. Both gi and nogi divisions. Fun competition experience.',
    date: '2026-04-10',
    duration_minutes: 120,
    focus: 'Competition',
    skill_level: 'intermediate',
    game_ids: [],
    notes: 'Make it fun! Round robin so everyone gets multiple matches. Good energy, supportive atmosphere.',
  },
]
