import type { StudentFormData } from '@/types/database'

// ═══════════════════════════════════════════════════════════
// REALISTIC STUDENT ROSTER
// Mixed levels, goals, and training preferences
// ═══════════════════════════════════════════════════════════

export const students: StudentFormData[] = [
  {
    name: 'Marcus Rivera',
    belt_rank: 'white',
    stripes: 2,
    start_date: '2025-09-15',
    competition_goals: 'First local tournament by mid-2026',
    strengths: ['athleticism', 'takedowns', 'cardio'],
    weaknesses: ['guard retention', 'submissions from bottom', 'grip fighting'],
    notes: 'Former wrestler. Strong top game but needs guard development. Very coachable.',
    environment_preference: 'nogi',
  },
  {
    name: 'Sarah Chen',
    belt_rank: 'blue',
    stripes: 3,
    start_date: '2023-06-01',
    competition_goals: 'IBJJF Worlds at purple belt',
    strengths: ['guard play', 'flexibility', 'submissions from guard', 'DLR'],
    weaknesses: ['takedowns', 'top pressure', 'passing against bigger opponents'],
    injury_notes: 'Previous MCL sprain (left knee) - cleared but careful with heel hooks',
    notes: 'Competition-focused. Great technique, needs to develop aggression on top.',
    environment_preference: 'gi',
  },
  {
    name: 'Jake Thompson',
    belt_rank: 'white',
    stripes: 4,
    start_date: '2025-03-10',
    competition_goals: 'Just wants to get better, no competition plans yet',
    strengths: ['strength', 'mount control', 'kimura'],
    weaknesses: ['guard', 'flexibility', 'leg locks', 'cardio'],
    injury_notes: 'Lower back tightness, needs to stretch more',
    notes: 'Big guy (220lbs). Relies on strength. Working on developing technique over power.',
    environment_preference: 'nogi',
  },
  {
    name: 'Aisha Patel',
    belt_rank: 'purple',
    stripes: 1,
    start_date: '2021-01-15',
    competition_goals: 'ADCC Trials 2027',
    strengths: ['leg locks', 'back attacks', 'scrambles', 'cardio'],
    weaknesses: ['gi guard passing', 'mount retention', 'collar chokes'],

    notes: 'Competition beast. Trains 6x/week. Developing systematic passing game.',
    environment_preference: 'nogi',
  },
  {
    name: 'Carlos Mendez',
    belt_rank: 'blue',
    stripes: 1,
    start_date: '2024-02-20',
    competition_goals: 'Local tournament circuit',
    strengths: ['closed guard', 'hip bump sweep', 'triangle'],
    weaknesses: ['open guard', 'standing work', 'half guard top'],
    injury_notes: 'Reconstructed ACL (right knee, 2022). No jumping guard pulls.',
    notes: 'Methodical learner. Takes detailed notes. Needs to develop stand-up game.',
    environment_preference: 'gi',
  },
  {
    name: 'Emma O\'Brien',
    belt_rank: 'white',
    stripes: 1,
    start_date: '2025-11-01',
    competition_goals: 'Build self-defense confidence',
    strengths: ['determination', 'hip escapes', 'attention to detail'],
    weaknesses: ['everything - still learning fundamentals', 'comfort under pressure'],

    notes: 'Brand new. Very dedicated, comes to every class. Building confidence on the mat.',
    environment_preference: 'gi',
  },
  {
    name: 'Derek Williams',
    belt_rank: 'brown',
    stripes: 2,
    start_date: '2018-08-10',
    competition_goals: 'Masters Worlds',
    strengths: ['pressure passing', 'side control', 'kimura system', 'mount'],
    weaknesses: ['modern leg lock defense', 'berimbolo counter', 'cardio decline'],
    injury_notes: 'Chronic shoulder issues (both). Avoids stacking.',
    notes: 'Veteran competitor. Assistant instructor. Working on modernizing game with leg locks.',
    environment_preference: 'gi',
  },
  {
    name: 'Tyler Kim',
    belt_rank: 'blue',
    stripes: 0,
    start_date: '2024-08-15',
    competition_goals: 'Sub-only tournaments',
    strengths: ['butterfly guard', 'arm drags', 'guillotines'],
    weaknesses: ['top control', 'passing', 'patience'],

    notes: 'Athletic, 155lbs. Good at scrambles but needs to develop control. Rushes submissions.',
    environment_preference: 'nogi',
  },
  {
    name: 'Rachel Santos',
    belt_rank: 'purple',
    stripes: 0,
    start_date: '2022-03-01',
    competition_goals: 'No-gi Pans',
    strengths: ['back takes', 'RNC', 'arm drags', 'wrestling'],
    weaknesses: ['bottom guard in gi', 'half guard', 'wrist locks'],
    injury_notes: 'Separated AC joint (left shoulder) - healed but limited overhead mobility',
    notes: 'Former D1 wrestler. Dominant top game. Teaching her to be comfortable on bottom.',
    environment_preference: 'wrestling',
  },
  {
    name: 'Omar Hassan',
    belt_rank: 'white',
    stripes: 3,
    start_date: '2025-05-20',
    competition_goals: 'First tournament in 2026',
    strengths: ['closed guard', 'armbar from mount', 'shrimping'],
    weaknesses: ['open guard', 'half guard', 'standing', 'leg locks'],

    notes: 'Consistent training 3x/week. Good fundamentals developing. Ready for first comp soon.',
    environment_preference: 'nogi',
  },
  {
    name: 'Lisa Park',
    belt_rank: 'blue',
    stripes: 2,
    start_date: '2023-11-01',
    competition_goals: 'IBJJF local opens',
    strengths: ['spider guard', 'lasso', 'collar sleeve', 'flexibility'],
    weaknesses: ['takedowns', 'nogi game', 'top pressure'],
    injury_notes: 'Hyperextended elbow (right) - 6 months ago, fully healed',
    notes: 'Gi specialist. Need to develop nogi skills. Great guard player.',
    environment_preference: 'gi',
  },
  {
    name: 'Mike Russo',
    belt_rank: 'white',
    stripes: 0,
    start_date: '2026-01-10',
    competition_goals: 'Get in shape and learn self-defense',
    strengths: ['upper body strength', 'learning mindset'],
    weaknesses: ['everything - brand new', 'flexibility', 'coordination'],
    injury_notes: 'Mild knee arthritis - no deep knee bends',
    notes: 'New student. 45 years old. Starting BJJ for fitness and mental challenge. Go easy on knees.',
    environment_preference: 'gi',
  },
  {
    name: 'Jasmine Torres',
    belt_rank: 'brown',
    stripes: 0,
    start_date: '2019-04-15',
    competition_goals: 'Black belt by 2027, Mundials at black belt',
    strengths: ['complete game', 'teaching ability', 'competition mindset', 'berimbolo'],
    weaknesses: ['wrestling scrambles', 'heavy top passers'],

    notes: 'Co-instructor. Competition record: 45-12. Developing Danaher passing system.',
    environment_preference: 'gi',
  },
  {
    name: 'Alex Volkov',
    belt_rank: 'blue',
    stripes: 4,
    start_date: '2023-01-20',
    competition_goals: 'Purple belt within 6 months',
    strengths: ['half guard bottom', 'kimura trap', 'pressure passing'],
    weaknesses: ['open guard', 'speed passing', 'back defense'],
    injury_notes: 'Herniated disc L4-L5 - avoid heavy stacking, no suplex',
    notes: 'Methodical, pressure-based game. Needs more dynamic movement. Judo background.',
    environment_preference: 'gi',
  },
  {
    name: 'Nadia Okafor',
    belt_rank: 'white',
    stripes: 2,
    start_date: '2025-07-01',
    competition_goals: 'Compete in 2026 at white belt',
    strengths: ['speed', 'guard retention', 'work ethic'],
    weaknesses: ['submissions', 'top control', 'takedowns'],

    notes: 'Fast learner, natural athlete. Gymnastics background helps with movement.',
    environment_preference: 'nogi',
  },
]
