import type { TechniqueFormData } from '@/types/database'

// ═══════════════════════════════════════════════════════════
// MODERN GRAPPLING TECHNIQUE DATABASE
// Systems: Danaher, Gordon Ryan, Craig Jones, Lachlan Giles,
//          Mikey Musumeci, John Danaher New Wave, Ruotolo Bros
// ═══════════════════════════════════════════════════════════

export const techniques: TechniqueFormData[] = [
  // ── CLOSED GUARD ─────────────────────────────────────────
  {
    name: 'Hip Clamp Guard (Closed Guard Retention)',
    position: 'closed-guard',
    category: 'guard-retention',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Fundamental closed guard retention using hip clamp principle. Knees pinched, ankles crossed, constant breaking of posture.',
    tags: ['fundamentals', 'retention', 'danaher'],
  },
  {
    name: 'Arm Drag from Closed Guard',
    position: 'closed-guard',
    category: 'transition',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Two-on-one grip to arm drag, creating back take or sweep opportunity. Key connector between guard and back system.',
    tags: ['arm-drag', 'transition', 'back-take', 'nogi-meta'],
  },
  {
    name: 'Hip Bump Sweep',
    position: 'closed-guard',
    category: 'sweep',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Classic sweep using hip extension to off-balance opponent when they posture up. Chains to kimura and guillotine.',
    tags: ['fundamentals', 'sweep', 'chain'],
  },
  {
    name: 'Scissor Sweep',
    position: 'closed-guard',
    category: 'sweep',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Fundamental sweep using shin across belly with collar/sleeve grip (gi) or collar tie/wrist (nogi). Push-pull principle.',
    tags: ['fundamentals', 'sweep'],
  },
  {
    name: 'Kimura from Closed Guard',
    position: 'closed-guard',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Double wrist lock attack. Gateway submission that chains to hip bump, guillotine, and back takes.',
    tags: ['fundamentals', 'kimura', 'submission-chain'],
  },
  {
    name: 'Guillotine from Closed Guard',
    position: 'closed-guard',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Arm-in or no-arm guillotine. Modern chin strap grip preferred. Chains from hip bump and failed takedowns.',
    tags: ['guillotine', 'front-headlock', 'submission'],
  },
  {
    name: 'Triangle Choke from Closed Guard',
    position: 'closed-guard',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Fundamental triangle setup. Isolate one arm, shoot hips up, lock figure-four with legs. Angle off for finish.',
    tags: ['fundamentals', 'triangle', 'submission'],
  },
  {
    name: 'Overhook Guard (Williams Guard Entry)',
    position: 'closed-guard',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Overhook one arm from closed guard. Creates triangle, omoplata, and armbar opportunities. High-percentage control position.',
    tags: ['overhook', 'williams-guard', 'control'],
  },

  // ── OPEN GUARD / BUTTERFLY ──────────────────────────────
  {
    name: 'Butterfly Guard - Elevating Sweep',
    position: 'open-guard',
    category: 'sweep',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Classic butterfly hook elevation with underhook. Off-balance with head position, elevate and come up on top.',
    tags: ['butterfly', 'fundamentals', 'sweep'],
  },
  {
    name: 'Butterfly Guard - Arm Drag to Back',
    position: 'open-guard',
    category: 'transition',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Arm drag from butterfly guard directly into back take. High-percentage nogi chain.',
    tags: ['butterfly', 'arm-drag', 'back-take', 'nogi-meta'],
  },
  {
    name: 'Single Leg X Guard Entry',
    position: 'open-guard',
    category: 'transition',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Entry into SLX from butterfly or seated guard. Inside hook elevation, outside foot on hip, control ankle.',
    tags: ['slx', 'leg-entanglement', 'danaher'],
  },
  {
    name: 'X Guard Entry & Sweep',
    position: 'open-guard',
    category: 'sweep',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Full X guard with double under hooks on the leg. Technical standup sweep or back door sweep.',
    tags: ['x-guard', 'sweep', 'leg-entanglement'],
  },
  {
    name: 'K Guard Entry',
    position: 'open-guard',
    category: 'transition',
    gi_nogi: 'nogi',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'Lachlan Giles K Guard system. Inverted entry into leg entanglements. Primary path to inside sankaku and heel hooks.',
    tags: ['k-guard', 'lachlan-giles', 'leg-locks', 'advanced'],
  },
  {
    name: 'Collar Sleeve Guard',
    position: 'open-guard',
    category: 'control',
    gi_nogi: 'gi',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Fundamental gi open guard. Cross collar grip + same side sleeve. Feet on bicep and hip. Controls distance.',
    tags: ['gi-guard', 'fundamentals', 'collar-sleeve'],
  },
  {
    name: 'Spider Guard',
    position: 'open-guard',
    category: 'control',
    gi_nogi: 'gi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Double sleeve grips with feet in biceps. Strong distance management. Chains to triangles, omoplatas, sweeps.',
    tags: ['gi-guard', 'spider', 'distance-management'],
  },
  {
    name: 'Lasso Guard',
    position: 'open-guard',
    category: 'control',
    gi_nogi: 'gi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Wrap leg around opponents arm from outside. Deep lasso creates omoplata and triangle entries. Shallow lasso for sweeps.',
    tags: ['gi-guard', 'lasso', 'control'],
  },
  {
    name: 'De La Riva Guard',
    position: 'open-guard',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Outside hook on far leg, collar or ankle grip. Foundation for berimbolo, kiss of the dragon, and modern guard play.',
    tags: ['dlr', 'modern-guard', 'berimbolo'],
  },
  {
    name: 'Reverse De La Riva Guard',
    position: 'open-guard',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Inside hook between opponents legs from outside position. Kiss of the dragon back take. Mikey Musumeci system.',
    tags: ['rdlr', 'modern-guard', 'mikey-musumeci', 'back-take'],
  },
  {
    name: 'Seated Guard - Shin-to-Shin',
    position: 'open-guard',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Seated position with shin-to-shin contact. Primary seated guard entry into SLX, X guard, and single legs.',
    tags: ['seated-guard', 'shin-to-shin', 'nogi-meta'],
  },

  // ── HALF GUARD ──────────────────────────────────────────
  {
    name: 'Knee Shield Half Guard',
    position: 'half-guard',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Fundamental half guard frame. Knee across opponents torso creating distance. Underhook battle is key.',
    tags: ['fundamentals', 'half-guard', 'frames'],
  },
  {
    name: 'Underhook Half Guard Sweep (Dog Fight)',
    position: 'half-guard',
    category: 'sweep',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Win the underhook, come to knees (dog fight), finish with single leg or back take.',
    tags: ['fundamentals', 'half-guard', 'underhook', 'sweep'],
  },
  {
    name: 'Deep Half Guard Entry & Sweep',
    position: 'half-guard',
    category: 'sweep',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Dive under opponent into deep half. Waiter sweep, Homer Simpson sweep, or back door escape.',
    tags: ['deep-half', 'sweep', 'advanced-half-guard'],
  },
  {
    name: 'Lockdown Half Guard',
    position: 'half-guard',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Figure-four leg entanglement on trapped leg. Electric chair sweep and whip-up series.',
    tags: ['lockdown', '10th-planet', 'half-guard'],
  },
  {
    name: 'Half Guard - John Wayne Sweep',
    position: 'half-guard',
    category: 'sweep',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Knee tap style sweep from half guard bottom. Use underhook and knee tap to off-balance.',
    tags: ['half-guard', 'sweep', 'fundamentals'],
  },
  {
    name: 'Z Guard (Knee Shield) to Leg Drag',
    position: 'half-guard',
    category: 'transition',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'From Z guard, pummel knee through to leg drag position. Creates passing opportunity from guard.',
    tags: ['z-guard', 'transition', 'guard-to-pass'],
  },

  // ── MOUNT ───────────────────────────────────────────────
  {
    name: 'Low Mount Control',
    position: 'mount',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Grapevine legs, head pressure, swim hands for underhooks. Ride the buck. Foundation of mount mastery.',
    tags: ['fundamentals', 'mount', 'control', 'gordon-ryan'],
  },
  {
    name: 'High Mount Transition',
    position: 'mount',
    category: 'transition',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Walk knees to armpits. S-mount entry. Creates armbar, mounted triangle, and collar choke opportunities.',
    tags: ['mount', 'transition', 'submission-setup'],
  },
  {
    name: 'Mounted Cross Collar Choke',
    position: 'mount',
    category: 'submission',
    gi_nogi: 'gi',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Classic gi choke from mount. Deep cross collar grip, second hand feeds in for the finish.',
    tags: ['gi', 'choke', 'mount', 'fundamentals'],
  },
  {
    name: 'Armbar from Mount',
    position: 'mount',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'S-mount or high mount to armbar. Pinch knees, hips up, control wrist. The king of submissions.',
    tags: ['armbar', 'fundamentals', 'mount'],
  },
  {
    name: 'Mounted Triangle',
    position: 'mount',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'From high mount, isolate arm and thread leg for mounted triangle. Extremely high finish rate.',
    tags: ['triangle', 'mount', 'submission'],
  },
  {
    name: 'Gift Wrap from Mount',
    position: 'mount',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Trap opponents arm across their body. Creates back take, armbar, and choke entries.',
    tags: ['gift-wrap', 'mount', 'control', 'back-take'],
  },
  {
    name: 'Mount Escape - Elbow Knee',
    position: 'mount',
    category: 'escape',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Fundamental mount escape. Frame at hip, shrimp, insert knee to recover half guard.',
    tags: ['fundamentals', 'escape', 'mount'],
  },
  {
    name: 'Mount Escape - Trap & Roll (Upa)',
    position: 'mount',
    category: 'escape',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Bridge and roll escape. Trap arm and foot on same side, bridge explosively to reverse position.',
    tags: ['fundamentals', 'escape', 'mount'],
  },

  // ── SIDE CONTROL ────────────────────────────────────────
  {
    name: 'Crossface Side Control',
    position: 'side-control',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Fundamental top side control. Crossface with shoulder pressure, underhook far arm, chest-to-chest.',
    tags: ['fundamentals', 'side-control', 'control', 'pressure'],
  },
  {
    name: 'Kesa Gatame (Scarf Hold)',
    position: 'side-control',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Head and arm control from side. Hip out, shoulder pressure. Chains to arm triangle and kimura.',
    tags: ['kesa', 'side-control', 'judo', 'control'],
  },
  {
    name: 'Kimura from Side Control',
    position: 'side-control',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'North-south kimura or standard side kimura. Key grip for controlling and submitting. Gordon Ryan system.',
    tags: ['kimura', 'side-control', 'gordon-ryan', 'submission'],
  },
  {
    name: 'Americana from Side Control',
    position: 'side-control',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Paint brush the arm to the mat, figure-four grip, rotate shoulder externally.',
    tags: ['americana', 'fundamentals', 'side-control'],
  },
  {
    name: 'Arm Triangle (Head & Arm Choke)',
    position: 'side-control',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'D\'arce / arm triangle from side control. Walk to north south, lock figure-four, squeeze.',
    tags: ['arm-triangle', 'choke', 'side-control'],
  },
  {
    name: 'Paper Cutter Choke',
    position: 'side-control',
    category: 'submission',
    gi_nogi: 'gi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Gi choke from side control using far lapel. Slide blade of wrist across throat.',
    tags: ['gi', 'choke', 'side-control'],
  },
  {
    name: 'Side Control Escape - Frame & Reguard',
    position: 'side-control',
    category: 'escape',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Elbow-knee frame, create space with hip escape, reinsert knee to recover guard.',
    tags: ['fundamentals', 'escape', 'side-control'],
  },
  {
    name: 'Side Control Escape - Ghost Escape',
    position: 'side-control',
    category: 'escape',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Turn away, create space, thread arm through for underhook and recover to turtle or guard.',
    tags: ['escape', 'side-control', 'ghost'],
  },

  // ── BACK ATTACKS ────────────────────────────────────────
  {
    name: 'Rear Naked Choke (RNC)',
    position: 'back',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'The highest percentage submission in grappling. Short choke or full RNC. Chin strap to finish.',
    tags: ['fundamentals', 'rnc', 'back', 'submission', 'danaher'],
  },
  {
    name: 'Seatbelt Back Control',
    position: 'back',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Over-under seatbelt grip. Choking arm over the shoulder, support arm under. Hooks or body triangle.',
    tags: ['fundamentals', 'back', 'control', 'danaher'],
  },
  {
    name: 'Body Triangle Back Control',
    position: 'back',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Figure-four legs around opponents torso from back. Superior control to hooks. Gordon Ryan preferred method.',
    tags: ['body-triangle', 'back', 'gordon-ryan', 'control'],
  },
  {
    name: 'Bow & Arrow Choke',
    position: 'back',
    category: 'submission',
    gi_nogi: 'gi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Highest percentage gi choke. Cross collar grip from back, grab pant leg, extend for the finish.',
    tags: ['gi', 'back', 'choke', 'bow-arrow'],
  },
  {
    name: 'Short Choke (Mata Leao Variation)',
    position: 'back',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Danaher system short choke. Forearm across throat without linking hands behind head. Quick finish.',
    tags: ['short-choke', 'back', 'danaher', 'submission'],
  },
  {
    name: 'Armbar from Back',
    position: 'back',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Transition from back control to armbar when opponent defends choke. Trap arm, rotate, finish.',
    tags: ['armbar', 'back', 'submission-chain'],
  },
  {
    name: 'Back Escape - Clear Hooks & Turn In',
    position: 'back',
    category: 'escape',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Fight hands, clear bottom hook, turn into opponent to recover half guard or closed guard.',
    tags: ['fundamentals', 'escape', 'back'],
  },

  // ── TURTLE ──────────────────────────────────────────────
  {
    name: 'Turtle - Granby Roll',
    position: 'turtle',
    category: 'escape',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Forward roll from turtle to recover guard. Shoulder roll to invert and reguard.',
    tags: ['turtle', 'escape', 'granby', 'guard-recovery'],
  },
  {
    name: 'Turtle - Sit Out Escape',
    position: 'turtle',
    category: 'escape',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Wrestling sit-out from turtle. Clear wrist, sit through, face opponent.',
    tags: ['turtle', 'escape', 'wrestling', 'fundamentals'],
  },
  {
    name: 'Turtle Breakdown - Spiral Ride',
    position: 'turtle',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Break down turtle with spiral ride to take the back. Seatbelt grip, insert hooks.',
    tags: ['turtle', 'back-take', 'wrestling', 'control'],
  },

  // ── STANDING / TAKEDOWNS ────────────────────────────────
  {
    name: 'Double Leg Takedown',
    position: 'standing',
    category: 'takedown',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Level change, penetration step, drive through. The king of takedowns. Setup with collar ties and hand fighting.',
    tags: ['wrestling', 'takedown', 'fundamentals'],
  },
  {
    name: 'Single Leg Takedown',
    position: 'standing',
    category: 'takedown',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Capture single leg, head inside or outside. Finish with trip, run the pipe, or lift.',
    tags: ['wrestling', 'takedown', 'fundamentals'],
  },
  {
    name: 'Arm Drag to Single/Back Take',
    position: 'standing',
    category: 'takedown',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Two-on-one arm drag from standing. Creates angle for single leg or direct back take. Ruotolo brothers specialty.',
    tags: ['arm-drag', 'takedown', 'back-take', 'ruotolo'],
  },
  {
    name: 'Snap Down to Front Headlock',
    position: 'standing',
    category: 'takedown',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Collar tie snap down. Forces opponent to turtle or take front headlock position. Guillotine series entry.',
    tags: ['wrestling', 'front-headlock', 'snap-down'],
  },
  {
    name: 'Ankle Pick',
    position: 'standing',
    category: 'takedown',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Low single / ankle pick. Collar tie, push head down, reach and pick the ankle. Low energy takedown.',
    tags: ['wrestling', 'takedown', 'ankle-pick'],
  },
  {
    name: 'Osoto Gari (Major Outer Reap)',
    position: 'standing',
    category: 'throw',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Judo throw. Collar and sleeve/underhook, reap the far leg. High amplitude throw.',
    tags: ['judo', 'throw', 'fundamentals'],
  },
  {
    name: 'Ouchi Gari (Major Inner Reap)',
    position: 'standing',
    category: 'throw',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Inside trip. Collar tie and underhook, step inside and reap the leg. Chains with osoto gari.',
    tags: ['judo', 'throw', 'fundamentals'],
  },
  {
    name: 'Drop Seoi Nage',
    position: 'standing',
    category: 'throw',
    gi_nogi: 'gi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Drop shoulder throw. Sleeve grip, turn in on knees, throw over shoulder. High amplitude gi throw.',
    tags: ['judo', 'throw', 'gi'],
  },
  {
    name: 'Body Lock Takedown',
    position: 'standing',
    category: 'takedown',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Clinch to body lock, trip or lift takedown. Gordon Ryan preferred takedown method for nogi.',
    tags: ['body-lock', 'takedown', 'gordon-ryan', 'clinch'],
  },
  {
    name: 'Guard Pull (Seated or Jump)',
    position: 'standing',
    category: 'transition',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Controlled pull to seated guard or closed guard. Collar + sleeve grip (gi) or collar tie + wrist (nogi).',
    tags: ['guard-pull', 'transition', 'competition'],
  },

  // ── CLINCH ──────────────────────────────────────────────
  {
    name: 'Underhook Pummeling',
    position: 'clinch',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Fundamental clinch skill. Fight for underhooks through pummeling. Foundation of all clinch work.',
    tags: ['pummeling', 'clinch', 'fundamentals', 'wrestling'],
  },
  {
    name: 'Collar Tie (Thai Clinch)',
    position: 'clinch',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Cup the back of the head/neck. Control posture and create snap-down and knee tap opportunities.',
    tags: ['clinch', 'collar-tie', 'fundamentals'],
  },
  {
    name: 'Two-on-One (Russian Tie)',
    position: 'clinch',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Wrist and tricep control. Creates arm drag, single leg, and snap down opportunities.',
    tags: ['clinch', 'russian-tie', 'wrestling', 'control'],
  },

  // ── LEG LOCKS (DANAHER / CRAIG JONES SYSTEM) ───────────
  {
    name: 'Straight Ankle Lock',
    position: 'guard',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Ashi garami position, figure-four grip on ankle, arch back for the break. IBJJF legal at all belts.',
    tags: ['leg-lock', 'ankle-lock', 'ashi-garami', 'fundamentals'],
  },
  {
    name: 'Inside Heel Hook',
    position: 'guard',
    category: 'submission',
    gi_nogi: 'nogi',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'The most devastating leg lock. Inside sankaku (411/honey hole), cup the heel, rotate. Danaher system.',
    tags: ['leg-lock', 'heel-hook', 'danaher', 'advanced', 'inside-sankaku'],
  },
  {
    name: 'Outside Heel Hook',
    position: 'guard',
    category: 'submission',
    gi_nogi: 'nogi',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'Standard ashi garami or cross ashi. Heel hook with outside rotation. High percentage from 50/50.',
    tags: ['leg-lock', 'heel-hook', 'outside', 'cross-ashi'],
  },
  {
    name: 'Knee Bar',
    position: 'guard',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'Hyperextend the knee joint. Triangle legs around the leg, hips into the knee, extend.',
    tags: ['leg-lock', 'knee-bar', 'submission'],
  },
  {
    name: 'Toe Hold',
    position: 'guard',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'Kimura grip on the foot, rotate the ankle/knee. Figure-four on foot, twist toward opponent.',
    tags: ['leg-lock', 'toe-hold', 'submission'],
  },
  {
    name: 'Ashi Garami (Standard Position)',
    position: 'guard',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Outside ashi position. One leg across hip, one hooking from inside. Base position for leg lock system.',
    tags: ['leg-lock', 'ashi-garami', 'control', 'danaher'],
  },
  {
    name: 'Inside Sankaku (411 / Saddle / Honey Hole)',
    position: 'guard',
    category: 'control',
    gi_nogi: 'nogi',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'Triangle legs around opponents leg from inside. Most powerful leg lock control. Danaher/Craig Jones system.',
    tags: ['leg-lock', 'inside-sankaku', 'danaher', 'craig-jones', 'advanced'],
  },
  {
    name: '50/50 Guard',
    position: 'guard',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Symmetrical leg entanglement. Both athletes have a hook. Modern use: outside heel hook position or gi sweep battles.',
    tags: ['50-50', 'leg-entanglement', 'guard'],
  },

  // ── GUARD PASSES ────────────────────────────────────────
  {
    name: 'Toreando Pass (Bullfighter)',
    position: 'guard',
    category: 'pass',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Grip pants/ankles, push legs to one side, circle around to side control. Speed pass.',
    tags: ['guard-pass', 'toreando', 'speed-pass', 'fundamentals'],
  },
  {
    name: 'Knee Cut Pass (Knee Slice)',
    position: 'half-guard',
    category: 'pass',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Slide knee through opponents legs. Cross face, far underhook, drive knee to mat. The bread and butter pass.',
    tags: ['guard-pass', 'knee-cut', 'fundamentals', 'pressure-pass'],
  },
  {
    name: 'Headquarters Position',
    position: 'guard',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'One knee in, one knee out stance for guard passing. Danaher system HQ position. Branch to all passes.',
    tags: ['guard-pass', 'headquarters', 'danaher', 'passing-system'],
  },
  {
    name: 'Over-Under Pass',
    position: 'guard',
    category: 'pass',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'One arm over the leg, one arm under. Stack and pressure pass. Bernardo Faria and Gordon Ryan style.',
    tags: ['guard-pass', 'over-under', 'pressure-pass', 'gordon-ryan'],
  },
  {
    name: 'Leg Drag Pass',
    position: 'guard',
    category: 'pass',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Control the leg across your body. Pin the hip, circle to side control or back take. Modern passing essential.',
    tags: ['guard-pass', 'leg-drag', 'modern-passing'],
  },
  {
    name: 'Body Lock Pass',
    position: 'guard',
    category: 'pass',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Close distance, lock body lock around waist, smash pass to side. Gordon Ryan primary passing method.',
    tags: ['guard-pass', 'body-lock', 'pressure-pass', 'gordon-ryan'],
  },
  {
    name: 'Long Step Pass',
    position: 'guard',
    category: 'pass',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'From headquarters, long step the back leg through to clear half guard. Technical passing.',
    tags: ['guard-pass', 'long-step', 'danaher'],
  },
  {
    name: 'Stack Pass',
    position: 'guard',
    category: 'pass',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Drive opponent onto their shoulders/neck, walk around. Effective against closed guard and spider guard.',
    tags: ['guard-pass', 'stack', 'pressure-pass', 'fundamentals'],
  },
  {
    name: 'X Pass',
    position: 'guard',
    category: 'pass',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Control one leg, step over the other in an X pattern. Quick pass against open guard.',
    tags: ['guard-pass', 'x-pass', 'speed-pass'],
  },

  // ── FRONT HEADLOCK / GUILLOTINE SYSTEM ─────────────────
  {
    name: 'Front Headlock Control',
    position: 'turtle',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Chin strap and far wrist control. Sprawl position. Gateway to all front headlock submissions.',
    tags: ['front-headlock', 'control', 'danaher'],
  },
  {
    name: 'Guillotine - Arm In (High Elbow)',
    position: 'guard',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Modern high elbow guillotine. Arm in variation. Chin strap, elbow high, crunch and squeeze.',
    tags: ['guillotine', 'front-headlock', 'submission', 'marcelo-garcia'],
  },
  {
    name: 'D\'Arce Choke (Brabo)',
    position: 'side-control',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Arm-in head and arm choke from side or front headlock. Thread arm under neck and through armpit.',
    tags: ['darce', 'front-headlock', 'choke', 'submission'],
  },
  {
    name: 'Anaconda Choke',
    position: 'turtle',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Arm-in head and arm choke. Thread from front, roll to complete. Reverse of the D\'arce.',
    tags: ['anaconda', 'front-headlock', 'choke', 'submission'],
  },
  {
    name: 'Japanese Necktie',
    position: 'turtle',
    category: 'submission',
    gi_nogi: 'nogi',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'Front headlock submission. Arm-in, sprawl and lock up necktie grip, walk hips to create angle.',
    tags: ['japanese-necktie', 'front-headlock', 'submission'],
  },

  // ── GUARD RETENTION ─────────────────────────────────────
  {
    name: 'Hip Escape (Shrimp) Series',
    position: 'guard',
    category: 'guard-retention',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Foundation of all guard recovery. Hip escape to create distance and reinsert frames and guards.',
    tags: ['fundamentals', 'movement', 'guard-retention'],
  },
  {
    name: 'Leg Pummeling (Guard Retention)',
    position: 'guard',
    category: 'guard-retention',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Active feet and leg pummeling to maintain guard. Keep feet on hips, repummel when legs are cleared.',
    tags: ['guard-retention', 'pummeling', 'fundamentals'],
  },
  {
    name: 'Inversion for Guard Recovery',
    position: 'guard',
    category: 'guard-retention',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Shoulder roll / granby style inversion to recover guard when pass is nearly complete.',
    tags: ['inversion', 'guard-retention', 'advanced'],
  },

  // ── WRESTLING SPECIFIC ──────────────────────────────────
  {
    name: 'Sprawl',
    position: 'standing',
    category: 'escape',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Fundamental takedown defense. Hips back, chest down, crossface. Transition to front headlock.',
    tags: ['wrestling', 'defense', 'sprawl', 'fundamentals'],
  },
  {
    name: 'Fireman\'s Carry',
    position: 'standing',
    category: 'takedown',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Level change, duck under arm, load opponent on shoulders. High amplitude takedown.',
    tags: ['wrestling', 'takedown', 'firemans-carry'],
  },
  {
    name: 'Duck Under',
    position: 'clinch',
    category: 'takedown',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'From collar tie, duck under opponents arm to get behind. Take the back or finish single leg.',
    tags: ['wrestling', 'duck-under', 'clinch'],
  },

  // ── SUBMISSION CHAINS ───────────────────────────────────
  {
    name: 'Omoplata',
    position: 'guard',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Shoulder lock using legs. From guard, isolate arm, swing leg over shoulder, sit up and lean forward.',
    tags: ['omoplata', 'submission', 'guard'],
  },
  {
    name: 'North-South Choke',
    position: 'side-control',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Transition to north-south, wrap arm around neck, squeeze with shoulder pressure.',
    tags: ['north-south', 'choke', 'submission', 'marcelo-garcia'],
  },
  {
    name: 'Ezekiel Choke from Mount',
    position: 'mount',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Feed hand through sleeve (gi) or use fist (nogi). Choke with blade of forearm.',
    tags: ['ezekiel', 'mount', 'choke'],
  },
  {
    name: 'Loop Choke',
    position: 'guard',
    category: 'submission',
    gi_nogi: 'gi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Cross collar grip, loop arm around head as opponent shoots or passes. Sneaky gi choke.',
    tags: ['gi', 'loop-choke', 'collar-choke'],
  },
  {
    name: 'Baseball Bat Choke',
    position: 'side-control',
    category: 'submission',
    gi_nogi: 'gi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Split collar grips (one palm up, one palm down), spin to north-south for the finish.',
    tags: ['gi', 'baseball-bat', 'collar-choke', 'side-control'],
  },
  {
    name: 'Wrist Lock',
    position: 'other',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Bend wrist past natural range. Available from mount, guard, and many grip fighting situations.',
    tags: ['wrist-lock', 'sneaky', 'submission'],
  },
  {
    name: 'Crucifix',
    position: 'back',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Trap both arms using legs and arm. Creates neck cranks, chokes, and armbar opportunities.',
    tags: ['crucifix', 'back', 'control'],
  },
]
