import type { TechniqueFormData } from '@/types/database'

// ═══════════════════════════════════════════════════════════
// MODERN GRAPPLING TECHNIQUE DATABASE
// Systems: Danaher, Gordon Ryan, Craig Jones, Lachlan Giles,
//          Mikey Musumeci, John Danaher New Wave, Ruotolo Bros
// ═══════════════════════════════════════════════════════════

export const techniques: TechniqueFormData[] = [
  // ── CLOSED GUARD ─────────────────────────────────────────
  {
    name: 'Hip Clamp Guard (Closed Guard Retention)',
    position: 'closed-guard',
    category: 'guard-retention',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Fundamental closed guard retention using hip clamp principle. Knees pinched, ankles crossed, constant breaking of posture.',
    tags: ['fundamentals', 'retention', 'danaher'],
  },
  {
    name: 'Arm Drag from Closed Guard',
    position: 'closed-guard',
    category: 'transition',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Two-on-one grip to arm drag, creating back take or sweep opportunity. Key connector between guard and back system.',
    tags: ['arm-drag', 'transition', 'back-take', 'nogi-meta'],
  },
  {
    name: 'Hip Bump Sweep',
    position: 'closed-guard',
    category: 'sweep',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Classic sweep using hip extension to off-balance opponent when they posture up. Chains to kimura and guillotine.',
    tags: ['fundamentals', 'sweep', 'chain'],
  },
  {
    name: 'Scissor Sweep',
    position: 'closed-guard',
    category: 'sweep',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Fundamental sweep using shin across belly with collar/sleeve grip (gi) or collar tie/wrist (nogi). Push-pull principle.',
    tags: ['fundamentals', 'sweep'],
  },
  {
    name: 'Kimura from Closed Guard',
    position: 'closed-guard',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Double wrist lock attack. Gateway submission that chains to hip bump, guillotine, and back takes.',
    tags: ['fundamentals', 'kimura', 'submission-chain'],
  },
  {
    name: 'Guillotine from Closed Guard',
    position: 'closed-guard',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Arm-in or no-arm guillotine. Modern chin strap grip preferred. Chains from hip bump and failed takedowns.',
    tags: ['guillotine', 'front-headlock', 'submission'],
  },
  {
    name: 'Triangle Choke from Closed Guard',
    position: 'closed-guard',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Fundamental triangle setup. Isolate one arm, shoot hips up, lock figure-four with legs. Angle off for finish.',
    tags: ['fundamentals', 'triangle', 'submission'],
  },
  {
    name: 'Overhook Guard (Williams Guard Entry)',
    position: 'closed-guard',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Overhook one arm from closed guard. Creates triangle, omoplata, and armbar opportunities. High-percentage control position.',
    tags: ['overhook', 'williams-guard', 'control'],
  },

  // ── OPEN GUARD / BUTTERFLY ──────────────────────────────
  {
    name: 'Butterfly Guard - Elevating Sweep',
    position: 'open-guard',
    category: 'sweep',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Classic butterfly hook elevation with underhook. Off-balance with head position, elevate and come up on top.',
    tags: ['butterfly', 'fundamentals', 'sweep'],
  },
  {
    name: 'Butterfly Guard - Arm Drag to Back',
    position: 'open-guard',
    category: 'transition',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Arm drag from butterfly guard directly into back take. High-percentage nogi chain.',
    tags: ['butterfly', 'arm-drag', 'back-take', 'nogi-meta'],
  },
  {
    name: 'Single Leg X Guard Entry',
    position: 'open-guard',
    category: 'transition',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Entry into SLX from butterfly or seated guard. Inside hook elevation, outside foot on hip, control ankle.',
    tags: ['slx', 'leg-entanglement', 'danaher'],
  },
  {
    name: 'X Guard Entry & Sweep',
    position: 'open-guard',
    category: 'sweep',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Full X guard with double under hooks on the leg. Technical standup sweep or back door sweep.',
    tags: ['x-guard', 'sweep', 'leg-entanglement'],
  },
  {
    name: 'K Guard Entry',
    position: 'open-guard',
    category: 'transition',
    gi_nogi: 'nogi',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'Lachlan Giles K Guard system. Inverted entry into leg entanglements. Primary path to inside sankaku and heel hooks.',
    tags: ['k-guard', 'lachlan-giles', 'leg-locks', 'advanced'],
  },
  {
    name: 'Collar Sleeve Guard',
    position: 'open-guard',
    category: 'control',
    gi_nogi: 'gi',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Fundamental gi open guard. Cross collar grip + same side sleeve. Feet on bicep and hip. Controls distance.',
    tags: ['gi-guard', 'fundamentals', 'collar-sleeve'],
  },
  {
    name: 'Spider Guard',
    position: 'open-guard',
    category: 'control',
    gi_nogi: 'gi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Double sleeve grips with feet in biceps. Strong distance management. Chains to triangles, omoplatas, sweeps.',
    tags: ['gi-guard', 'spider', 'distance-management'],
  },
  {
    name: 'Lasso Guard',
    position: 'open-guard',
    category: 'control',
    gi_nogi: 'gi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Wrap leg around opponents arm from outside. Deep lasso creates omoplata and triangle entries. Shallow lasso for sweeps.',
    tags: ['gi-guard', 'lasso', 'control'],
  },
  {
    name: 'De La Riva Guard',
    position: 'open-guard',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Outside hook on far leg, collar or ankle grip. Foundation for berimbolo, kiss of the dragon, and modern guard play.',
    tags: ['dlr', 'modern-guard', 'berimbolo'],
  },
  {
    name: 'Reverse De La Riva Guard',
    position: 'open-guard',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Inside hook between opponents legs from outside position. Kiss of the dragon back take. Mikey Musumeci system.',
    tags: ['rdlr', 'modern-guard', 'mikey-musumeci', 'back-take'],
  },
  {
    name: 'Seated Guard - Shin-to-Shin',
    position: 'open-guard',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Seated position with shin-to-shin contact. Primary seated guard entry into SLX, X guard, and single legs.',
    tags: ['seated-guard', 'shin-to-shin', 'nogi-meta'],
  },

  // ── HALF GUARD ──────────────────────────────────────────
  {
    name: 'Knee Shield Half Guard',
    position: 'half-guard',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Fundamental half guard frame. Knee across opponents torso creating distance. Underhook battle is key.',
    tags: ['fundamentals', 'half-guard', 'frames'],
  },
  {
    name: 'Underhook Half Guard Sweep (Dog Fight)',
    position: 'half-guard',
    category: 'sweep',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Win the underhook, come to knees (dog fight), finish with single leg or back take.',
    tags: ['fundamentals', 'half-guard', 'underhook', 'sweep'],
  },
  {
    name: 'Deep Half Guard Entry & Sweep',
    position: 'half-guard',
    category: 'sweep',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Dive under opponent into deep half. Waiter sweep, Homer Simpson sweep, or back door escape.',
    tags: ['deep-half', 'sweep', 'advanced-half-guard'],
  },
  {
    name: 'Lockdown Half Guard',
    position: 'half-guard',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Figure-four leg entanglement on trapped leg. Electric chair sweep and whip-up series.',
    tags: ['lockdown', '10th-planet', 'half-guard'],
  },
  {
    name: 'Half Guard - John Wayne Sweep',
    position: 'half-guard',
    category: 'sweep',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Knee tap style sweep from half guard bottom. Use underhook and knee tap to off-balance.',
    tags: ['half-guard', 'sweep', 'fundamentals'],
  },
  {
    name: 'Z Guard (Knee Shield) to Leg Drag',
    position: 'half-guard',
    category: 'transition',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'From Z guard, pummel knee through to leg drag position. Creates passing opportunity from guard.',
    tags: ['z-guard', 'transition', 'guard-to-pass'],
  },

  // ── MOUNT ───────────────────────────────────────────────
  {
    name: 'Low Mount Control',
    position: 'mount',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Grapevine legs, head pressure, swim hands for underhooks. Ride the buck. Foundation of mount mastery.',
    tags: ['fundamentals', 'mount', 'control', 'gordon-ryan'],
  },
  {
    name: 'High Mount Transition',
    position: 'mount',
    category: 'transition',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Walk knees to armpits. S-mount entry. Creates armbar, mounted triangle, and collar choke opportunities.',
    tags: ['mount', 'transition', 'submission-setup'],
  },
  {
    name: 'Mounted Cross Collar Choke',
    position: 'mount',
    category: 'submission',
    gi_nogi: 'gi',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Classic gi choke from mount. Deep cross collar grip, second hand feeds in for the finish.',
    tags: ['gi', 'choke', 'mount', 'fundamentals'],
  },
  {
    name: 'Armbar from Mount',
    position: 'mount',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'S-mount or high mount to armbar. Pinch knees, hips up, control wrist. The king of submissions.',
    tags: ['armbar', 'fundamentals', 'mount'],
  },
  {
    name: 'Mounted Triangle',
    position: 'mount',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'From high mount, isolate arm and thread leg for mounted triangle. Extremely high finish rate.',
    tags: ['triangle', 'mount', 'submission'],
  },
  {
    name: 'Gift Wrap from Mount',
    position: 'mount',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Trap opponents arm across their body. Creates back take, armbar, and choke entries.',
    tags: ['gift-wrap', 'mount', 'control', 'back-take'],
  },
  {
    name: 'Mount Escape - Elbow Knee',
    position: 'mount',
    category: 'escape',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Fundamental mount escape. Frame at hip, shrimp, insert knee to recover half guard.',
    tags: ['fundamentals', 'escape', 'mount'],
  },
  {
    name: 'Mount Escape - Trap & Roll (Upa)',
    position: 'mount',
    category: 'escape',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Bridge and roll escape. Trap arm and foot on same side, bridge explosively to reverse position.',
    tags: ['fundamentals', 'escape', 'mount'],
  },

  // ── SIDE CONTROL ────────────────────────────────────────
  {
    name: 'Crossface Side Control',
    position: 'side-control',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Fundamental top side control. Crossface with shoulder pressure, underhook far arm, chest-to-chest.',
    tags: ['fundamentals', 'side-control', 'control', 'pressure'],
  },
  {
    name: 'Kesa Gatame (Scarf Hold)',
    position: 'side-control',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Head and arm control from side. Hip out, shoulder pressure. Chains to arm triangle and kimura.',
    tags: ['kesa', 'side-control', 'judo', 'control'],
  },
  {
    name: 'Kimura from Side Control',
    position: 'side-control',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'North-south kimura or standard side kimura. Key grip for controlling and submitting. Gordon Ryan system.',
    tags: ['kimura', 'side-control', 'gordon-ryan', 'submission'],
  },
  {
    name: 'Americana from Side Control',
    position: 'side-control',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Paint brush the arm to the mat, figure-four grip, rotate shoulder externally.',
    tags: ['americana', 'fundamentals', 'side-control'],
  },
  {
    name: 'Arm Triangle (Head & Arm Choke)',
    position: 'side-control',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'D\'arce / arm triangle from side control. Walk to north south, lock figure-four, squeeze.',
    tags: ['arm-triangle', 'choke', 'side-control'],
  },
  {
    name: 'Paper Cutter Choke',
    position: 'side-control',
    category: 'submission',
    gi_nogi: 'gi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Gi choke from side control using far lapel. Slide blade of wrist across throat.',
    tags: ['gi', 'choke', 'side-control'],
  },
  {
    name: 'Side Control Escape - Frame & Reguard',
    position: 'side-control',
    category: 'escape',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Elbow-knee frame, create space with hip escape, reinsert knee to recover guard.',
    tags: ['fundamentals', 'escape', 'side-control'],
  },
  {
    name: 'Side Control Escape - Ghost Escape',
    position: 'side-control',
    category: 'escape',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Turn away, create space, thread arm through for underhook and recover to turtle or guard.',
    tags: ['escape', 'side-control', 'ghost'],
  },

  // ── BACK ATTACKS ────────────────────────────────────────
  {
    name: 'Rear Naked Choke (RNC)',
    position: 'back',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'The highest percentage submission in grappling. Short choke or full RNC. Chin strap to finish.',
    tags: ['fundamentals', 'rnc', 'back', 'submission', 'danaher'],
  },
  {
    name: 'Seatbelt Back Control',
    position: 'back',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Over-under seatbelt grip. Choking arm over the shoulder, support arm under. Hooks or body triangle.',
    tags: ['fundamentals', 'back', 'control', 'danaher'],
  },
  {
    name: 'Body Triangle Back Control',
    position: 'back',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Figure-four legs around opponents torso from back. Superior control to hooks. Gordon Ryan preferred method.',
    tags: ['body-triangle', 'back', 'gordon-ryan', 'control'],
  },
  {
    name: 'Bow & Arrow Choke',
    position: 'back',
    category: 'submission',
    gi_nogi: 'gi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Highest percentage gi choke. Cross collar grip from back, grab pant leg, extend for the finish.',
    tags: ['gi', 'back', 'choke', 'bow-arrow'],
  },
  {
    name: 'Short Choke (Mata Leao Variation)',
    position: 'back',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Danaher system short choke. Forearm across throat without linking hands behind head. Quick finish.',
    tags: ['short-choke', 'back', 'danaher', 'submission'],
  },
  {
    name: 'Armbar from Back',
    position: 'back',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Transition from back control to armbar when opponent defends choke. Trap arm, rotate, finish.',
    tags: ['armbar', 'back', 'submission-chain'],
  },
  {
    name: 'Back Escape - Clear Hooks & Turn In',
    position: 'back',
    category: 'escape',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Fight hands, clear bottom hook, turn into opponent to recover half guard or closed guard.',
    tags: ['fundamentals', 'escape', 'back'],
  },

  // ── TURTLE ──────────────────────────────────────────────
  {
    name: 'Turtle - Granby Roll',
    position: 'turtle',
    category: 'escape',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Forward roll from turtle to recover guard. Shoulder roll to invert and reguard.',
    tags: ['turtle', 'escape', 'granby', 'guard-recovery'],
  },
  {
    name: 'Turtle - Sit Out Escape',
    position: 'turtle',
    category: 'escape',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Wrestling sit-out from turtle. Clear wrist, sit through, face opponent.',
    tags: ['turtle', 'escape', 'wrestling', 'fundamentals'],
  },
  {
    name: 'Turtle Breakdown - Spiral Ride',
    position: 'turtle',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Break down turtle with spiral ride to take the back. Seatbelt grip, insert hooks.',
    tags: ['turtle', 'back-take', 'wrestling', 'control'],
  },

  // ── STANDING / TAKEDOWNS ────────────────────────────────
  {
    name: 'Double Leg Takedown',
    position: 'standing',
    category: 'takedown',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Level change, penetration step, drive through. The king of takedowns. Setup with collar ties and hand fighting.',
    tags: ['wrestling', 'takedown', 'fundamentals'],
  },
  {
    name: 'Single Leg Takedown',
    position: 'standing',
    category: 'takedown',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Capture single leg, head inside or outside. Finish with trip, run the pipe, or lift.',
    tags: ['wrestling', 'takedown', 'fundamentals'],
  },
  {
    name: 'Arm Drag to Single/Back Take',
    position: 'standing',
    category: 'takedown',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Two-on-one arm drag from standing. Creates angle for single leg or direct back take. Ruotolo brothers specialty.',
    tags: ['arm-drag', 'takedown', 'back-take', 'ruotolo'],
  },
  {
    name: 'Snap Down to Front Headlock',
    position: 'standing',
    category: 'takedown',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Collar tie snap down. Forces opponent to turtle or take front headlock position. Guillotine series entry.',
    tags: ['wrestling', 'front-headlock', 'snap-down'],
  },
  {
    name: 'Ankle Pick',
    position: 'standing',
    category: 'takedown',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Low single / ankle pick. Collar tie, push head down, reach and pick the ankle. Low energy takedown.',
    tags: ['wrestling', 'takedown', 'ankle-pick'],
  },
  {
    name: 'Osoto Gari (Major Outer Reap)',
    position: 'standing',
    category: 'throw',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Judo throw. Collar and sleeve/underhook, reap the far leg. High amplitude throw.',
    tags: ['judo', 'throw', 'fundamentals'],
  },
  {
    name: 'Ouchi Gari (Major Inner Reap)',
    position: 'standing',
    category: 'throw',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Inside trip. Collar tie and underhook, step inside and reap the leg. Chains with osoto gari.',
    tags: ['judo', 'throw', 'fundamentals'],
  },
  {
    name: 'Drop Seoi Nage',
    position: 'standing',
    category: 'throw',
    gi_nogi: 'gi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Drop shoulder throw. Sleeve grip, turn in on knees, throw over shoulder. High amplitude gi throw.',
    tags: ['judo', 'throw', 'gi'],
  },
  {
    name: 'Body Lock Takedown',
    position: 'standing',
    category: 'takedown',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Clinch to body lock, trip or lift takedown. Gordon Ryan preferred takedown method for nogi.',
    tags: ['body-lock', 'takedown', 'gordon-ryan', 'clinch'],
  },
  {
    name: 'Guard Pull (Seated or Jump)',
    position: 'standing',
    category: 'transition',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Controlled pull to seated guard or closed guard. Collar + sleeve grip (gi) or collar tie + wrist (nogi).',
    tags: ['guard-pull', 'transition', 'competition'],
  },

  // ── CLINCH ──────────────────────────────────────────────
  {
    name: 'Underhook Pummeling',
    position: 'clinch',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Fundamental clinch skill. Fight for underhooks through pummeling. Foundation of all clinch work.',
    tags: ['pummeling', 'clinch', 'fundamentals', 'wrestling'],
  },
  {
    name: 'Collar Tie (Thai Clinch)',
    position: 'clinch',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Cup the back of the head/neck. Control posture and create snap-down and knee tap opportunities.',
    tags: ['clinch', 'collar-tie', 'fundamentals'],
  },
  {
    name: 'Two-on-One (Russian Tie)',
    position: 'clinch',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Wrist and tricep control. Creates arm drag, single leg, and snap down opportunities.',
    tags: ['clinch', 'russian-tie', 'wrestling', 'control'],
  },

  // ── LEG LOCKS (DANAHER / CRAIG JONES SYSTEM) ───────────
  {
    name: 'Straight Ankle Lock',
    position: 'guard',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Ashi garami position, figure-four grip on ankle, arch back for the break. IBJJF legal at all belts.',
    tags: ['leg-lock', 'ankle-lock', 'ashi-garami', 'fundamentals'],
  },
  {
    name: 'Inside Heel Hook',
    position: 'guard',
    category: 'submission',
    gi_nogi: 'nogi',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'The most devastating leg lock. Inside sankaku (411/honey hole), cup the heel, rotate. Danaher system.',
    tags: ['leg-lock', 'heel-hook', 'danaher', 'advanced', 'inside-sankaku'],
  },
  {
    name: 'Outside Heel Hook',
    position: 'guard',
    category: 'submission',
    gi_nogi: 'nogi',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'Standard ashi garami or cross ashi. Heel hook with outside rotation. High percentage from 50/50.',
    tags: ['leg-lock', 'heel-hook', 'outside', 'cross-ashi'],
  },
  {
    name: 'Knee Bar',
    position: 'guard',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'Hyperextend the knee joint. Triangle legs around the leg, hips into the knee, extend.',
    tags: ['leg-lock', 'knee-bar', 'submission'],
  },
  {
    name: 'Toe Hold',
    position: 'guard',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'Kimura grip on the foot, rotate the ankle/knee. Figure-four on foot, twist toward opponent.',
    tags: ['leg-lock', 'toe-hold', 'submission'],
  },
  {
    name: 'Ashi Garami (Standard Position)',
    position: 'guard',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Outside ashi position. One leg across hip, one hooking from inside. Base position for leg lock system.',
    tags: ['leg-lock', 'ashi-garami', 'control', 'danaher'],
  },
  {
    name: 'Inside Sankaku (411 / Saddle / Honey Hole)',
    position: 'guard',
    category: 'control',
    gi_nogi: 'nogi',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'Triangle legs around opponents leg from inside. Most powerful leg lock control. Danaher/Craig Jones system.',
    tags: ['leg-lock', 'inside-sankaku', 'danaher', 'craig-jones', 'advanced'],
  },
  {
    name: '50/50 Guard',
    position: 'guard',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Symmetrical leg entanglement. Both athletes have a hook. Modern use: outside heel hook position or gi sweep battles.',
    tags: ['50-50', 'leg-entanglement', 'guard'],
  },

  // ── GUARD PASSES ────────────────────────────────────────
  {
    name: 'Toreando Pass (Bullfighter)',
    position: 'guard',
    category: 'pass',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Grip pants/ankles, push legs to one side, circle around to side control. Speed pass.',
    tags: ['guard-pass', 'toreando', 'speed-pass', 'fundamentals'],
  },
  {
    name: 'Knee Cut Pass (Knee Slice)',
    position: 'half-guard',
    category: 'pass',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Slide knee through opponents legs. Cross face, far underhook, drive knee to mat. The bread and butter pass.',
    tags: ['guard-pass', 'knee-cut', 'fundamentals', 'pressure-pass'],
  },
  {
    name: 'Headquarters Position',
    position: 'guard',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'One knee in, one knee out stance for guard passing. Danaher system HQ position. Branch to all passes.',
    tags: ['guard-pass', 'headquarters', 'danaher', 'passing-system'],
  },
  {
    name: 'Over-Under Pass',
    position: 'guard',
    category: 'pass',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'One arm over the leg, one arm under. Stack and pressure pass. Bernardo Faria and Gordon Ryan style.',
    tags: ['guard-pass', 'over-under', 'pressure-pass', 'gordon-ryan'],
  },
  {
    name: 'Leg Drag Pass',
    position: 'guard',
    category: 'pass',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Control the leg across your body. Pin the hip, circle to side control or back take. Modern passing essential.',
    tags: ['guard-pass', 'leg-drag', 'modern-passing'],
  },
  {
    name: 'Body Lock Pass',
    position: 'guard',
    category: 'pass',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Close distance, lock body lock around waist, smash pass to side. Gordon Ryan primary passing method.',
    tags: ['guard-pass', 'body-lock', 'pressure-pass', 'gordon-ryan'],
  },
  {
    name: 'Long Step Pass',
    position: 'guard',
    category: 'pass',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'From headquarters, long step the back leg through to clear half guard. Technical passing.',
    tags: ['guard-pass', 'long-step', 'danaher'],
  },
  {
    name: 'Stack Pass',
    position: 'guard',
    category: 'pass',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Drive opponent onto their shoulders/neck, walk around. Effective against closed guard and spider guard.',
    tags: ['guard-pass', 'stack', 'pressure-pass', 'fundamentals'],
  },
  {
    name: 'X Pass',
    position: 'guard',
    category: 'pass',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Control one leg, step over the other in an X pattern. Quick pass against open guard.',
    tags: ['guard-pass', 'x-pass', 'speed-pass'],
  },

  // ── FRONT HEADLOCK / GUILLOTINE SYSTEM ─────────────────
  {
    name: 'Front Headlock Control',
    position: 'turtle',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Chin strap and far wrist control. Sprawl position. Gateway to all front headlock submissions.',
    tags: ['front-headlock', 'control', 'danaher'],
  },
  {
    name: 'Guillotine - Arm In (High Elbow)',
    position: 'guard',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Modern high elbow guillotine. Arm in variation. Chin strap, elbow high, crunch and squeeze.',
    tags: ['guillotine', 'front-headlock', 'submission', 'marcelo-garcia'],
  },
  {
    name: 'D\'Arce Choke (Brabo)',
    position: 'side-control',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Arm-in head and arm choke from side or front headlock. Thread arm under neck and through armpit.',
    tags: ['darce', 'front-headlock', 'choke', 'submission'],
  },
  {
    name: 'Anaconda Choke',
    position: 'turtle',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Arm-in head and arm choke. Thread from front, roll to complete. Reverse of the D\'arce.',
    tags: ['anaconda', 'front-headlock', 'choke', 'submission'],
  },
  {
    name: 'Japanese Necktie',
    position: 'turtle',
    category: 'submission',
    gi_nogi: 'nogi',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'Front headlock submission. Arm-in, sprawl and lock up necktie grip, walk hips to create angle.',
    tags: ['japanese-necktie', 'front-headlock', 'submission'],
  },

  // ── GUARD RETENTION ─────────────────────────────────────
  {
    name: 'Hip Escape (Shrimp) Series',
    position: 'guard',
    category: 'guard-retention',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Foundation of all guard recovery. Hip escape to create distance and reinsert frames and guards.',
    tags: ['fundamentals', 'movement', 'guard-retention'],
  },
  {
    name: 'Leg Pummeling (Guard Retention)',
    position: 'guard',
    category: 'guard-retention',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Active feet and leg pummeling to maintain guard. Keep feet on hips, repummel when legs are cleared.',
    tags: ['guard-retention', 'pummeling', 'fundamentals'],
  },
  {
    name: 'Inversion for Guard Recovery',
    position: 'guard',
    category: 'guard-retention',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Shoulder roll / granby style inversion to recover guard when pass is nearly complete.',
    tags: ['inversion', 'guard-retention', 'advanced'],
  },

  // ── WRESTLING SPECIFIC ──────────────────────────────────
  {
    name: 'Sprawl',
    position: 'standing',
    category: 'escape',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Fundamental takedown defense. Hips back, chest down, crossface. Transition to front headlock.',
    tags: ['wrestling', 'defense', 'sprawl', 'fundamentals'],
  },
  {
    name: 'Fireman\'s Carry',
    position: 'standing',
    category: 'takedown',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Level change, duck under arm, load opponent on shoulders. High amplitude takedown.',
    tags: ['wrestling', 'takedown', 'firemans-carry'],
  },
  {
    name: 'Duck Under',
    position: 'clinch',
    category: 'takedown',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'From collar tie, duck under opponents arm to get behind. Take the back or finish single leg.',
    tags: ['wrestling', 'duck-under', 'clinch'],
  },

  // ── SUBMISSION CHAINS ───────────────────────────────────
  {
    name: 'Omoplata',
    position: 'guard',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Shoulder lock using legs. From guard, isolate arm, swing leg over shoulder, sit up and lean forward.',
    tags: ['omoplata', 'submission', 'guard'],
  },
  {
    name: 'North-South Choke',
    position: 'side-control',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Transition to north-south, wrap arm around neck, squeeze with shoulder pressure.',
    tags: ['north-south', 'choke', 'submission', 'marcelo-garcia'],
  },
  {
    name: 'Ezekiel Choke from Mount',
    position: 'mount',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Feed hand through sleeve (gi) or use fist (nogi). Choke with blade of forearm.',
    tags: ['ezekiel', 'mount', 'choke'],
  },
  {
    name: 'Loop Choke',
    position: 'guard',
    category: 'submission',
    gi_nogi: 'gi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Cross collar grip, loop arm around head as opponent shoots or passes. Sneaky gi choke.',
    tags: ['gi', 'loop-choke', 'collar-choke'],
  },
  {
    name: 'Baseball Bat Choke',
    position: 'side-control',
    category: 'submission',
    gi_nogi: 'gi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Split collar grips (one palm up, one palm down), spin to north-south for the finish.',
    tags: ['gi', 'baseball-bat', 'collar-choke', 'side-control'],
  },
  {
    name: 'Wrist Lock',
    position: 'other',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Bend wrist past natural range. Available from mount, guard, and many grip fighting situations.',
    tags: ['wrist-lock', 'sneaky', 'submission'],
  },
  {
    name: 'Crucifix',
    position: 'back',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Trap both arms using legs and arm. Creates neck cranks, chokes, and armbar opportunities.',
    tags: ['crucifix', 'back', 'control'],
  },

  // ══════════════════════════════════════════════════════════
  // GORDON RYAN — SYSTEMATICALLY ATTACKING SERIES
  // ══════════════════════════════════════════════════════════
  {
    name: 'Gordon Ryan Seated Guard System',
    position: 'open-guard',
    category: 'control',
    gi_nogi: 'nogi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Seated guard with collar tie and wrist control. J-point concept: keep opponent at the optimal distance where you can attack but they cannot pass effectively.',
    tags: ['gordon-ryan', 'seated-guard', 'nogi-meta', 'systematically-attacking'],
  },
  {
    name: 'Body Lock Pass - Half Nelson Finish',
    position: 'guard',
    category: 'pass',
    gi_nogi: 'nogi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'From body lock, drive to half guard, thread half nelson on far side, use head and shoulder pressure to pin while extracting the leg. Gordon Ryan signature finish.',
    tags: ['body-lock', 'pressure-pass', 'gordon-ryan', 'half-nelson'],
  },
  {
    name: 'Gordon Ryan Mount - Low to High Progression',
    position: 'mount',
    category: 'transition',
    gi_nogi: 'nogi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Systematic mount progression: low mount with grapevines to tire opponent, then walk knees up as they fatigue. Transition to S-mount for armbar or gift wrap for back take.',
    tags: ['gordon-ryan', 'mount', 'systematic', 'progression'],
  },
  {
    name: 'S-Mount to Armbar',
    position: 'mount',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'From high mount, slide one leg under opponents head into S-mount. Isolate the arm, lean back for armbar. Highest percentage armbar setup in modern grappling.',
    tags: ['s-mount', 'armbar', 'mount', 'gordon-ryan'],
  },
  {
    name: 'Kimura Trap System',
    position: 'side-control',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Use the kimura grip as a control position from side control, north-south, and mount. Forces opponent to defend the shoulder lock, opening back takes and arm triangles.',
    tags: ['kimura-trap', 'control', 'system', 'gordon-ryan'],
  },
  {
    name: 'Power Guillotine (Standing)',
    position: 'standing',
    category: 'submission',
    gi_nogi: 'nogi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Standing guillotine with body lock. Cup the chin with blade of wrist, lock hands, pull guard while cranking upward. Gordon Ryan competition finisher.',
    tags: ['guillotine', 'standing', 'gordon-ryan', 'front-headlock'],
  },
  {
    name: 'High Wrist Guillotine',
    position: 'guard',
    category: 'submission',
    gi_nogi: 'nogi',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'Guillotine variation with wrist positioned high on the back of the neck. Creates a blood choke rather than windpipe crush. Modern finishing detail.',
    tags: ['guillotine', 'high-wrist', 'submission', 'nogi-meta'],
  },
  {
    name: 'Float Pass',
    position: 'guard',
    category: 'pass',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Light, reactive passing using backstep and hip-switch to float over guard. Stay light on top, react to guard movements rather than forcing through.',
    tags: ['float-pass', 'speed-pass', 'gordon-ryan', 'passing-system'],
  },
  {
    name: 'Gordon Ryan Closed Guard - 6 Vulnerabilities',
    position: 'closed-guard',
    category: 'control',
    gi_nogi: 'nogi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Systematically attacking from closed guard by exploiting 6 posture vulnerabilities: hands on mat, hands on chest, posture broken left, posture broken right, head too high, head too low.',
    tags: ['gordon-ryan', 'closed-guard', 'system', 'vulnerabilities'],
  },

  // ══════════════════════════════════════════════════════════
  // CRAIG JONES SYSTEMS
  // ══════════════════════════════════════════════════════════
  {
    name: 'Craig Jones Z-Guard Attack System',
    position: 'half-guard',
    category: 'sweep',
    gi_nogi: 'nogi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Z-guard (knee shield) as an attacking position. Frame with knee, create underhook opportunities, sweep to top or enter leg entanglements. Craig Jones primary guard.',
    tags: ['z-guard', 'craig-jones', 'half-guard', 'attack-system'],
  },
  {
    name: 'Z-Guard to Inside Sankaku Entry',
    position: 'half-guard',
    category: 'transition',
    gi_nogi: 'nogi',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'From Z-guard, invert under opponent to enter inside sankaku on the far leg. Craig Jones signature entry into the leg lock game from half guard.',
    tags: ['z-guard', 'inside-sankaku', 'craig-jones', 'leg-lock-entry'],
  },
  {
    name: 'Power Ride (Craig Jones)',
    position: 'back',
    category: 'control',
    gi_nogi: 'nogi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Wrestling-style ride from top position. Heavy hips, crossbody control, keep opponent flat on belly. Creates back take and cradle entries.',
    tags: ['power-ride', 'craig-jones', 'wrestling', 'top-control'],
  },
  {
    name: 'Cradle to Inside Sankaku',
    position: 'side-control',
    category: 'transition',
    gi_nogi: 'nogi',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'Near-side or far-side cradle from top position, use the cradle to expose the legs and enter inside sankaku for heel hook. Craig Jones innovation.',
    tags: ['cradle', 'inside-sankaku', 'craig-jones', 'transition'],
  },
  {
    name: 'Power Bottom - Wrestling Escapes for BJJ',
    position: 'turtle',
    category: 'escape',
    gi_nogi: 'nogi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Wrestling-based bottom escapes adapted for BJJ. Standup in base, switch, Peterson roll, and hip heist. Craig Jones system for getting off bottom.',
    tags: ['power-bottom', 'craig-jones', 'wrestling', 'escapes'],
  },
  {
    name: 'Craig Jones Heel Hook Finishing Mechanics',
    position: 'guard',
    category: 'submission',
    gi_nogi: 'nogi',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'Heel hook finishing details: cup the heel (not the toes), control the knee line, rotate the heel toward the opponents butt. Slow, controlled finish.',
    tags: ['heel-hook', 'craig-jones', 'finishing', 'leg-lock'],
  },
  {
    name: 'Battle Tested Closed Guard (Craig Jones)',
    position: 'closed-guard',
    category: 'sweep',
    gi_nogi: 'nogi',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Competition-proven closed guard fundamentals. Hip bump, kimura, guillotine chain with emphasis on high percentage combinations used at the highest levels.',
    tags: ['craig-jones', 'closed-guard', 'fundamentals', 'competition'],
  },

  // ══════════════════════════════════════════════════════════
  // LACHLAN GILES SYSTEMS
  // ══════════════════════════════════════════════════════════
  {
    name: 'K-Guard to Backside 50/50',
    position: 'open-guard',
    category: 'transition',
    gi_nogi: 'nogi',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'From K-guard position, invert and thread legs to enter backside 50/50. Primary path to outside heel hook. Lachlan Giles ADCC system.',
    tags: ['k-guard', 'backside-50-50', 'lachlan-giles', 'leg-lock'],
  },
  {
    name: 'K-Guard to Inside Sankaku',
    position: 'open-guard',
    category: 'transition',
    gi_nogi: 'nogi',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'From K-guard, enter inside sankaku on the near leg. Alternative path when opponent defends backside 50/50 entry. Lachlan Giles secondary attack.',
    tags: ['k-guard', 'inside-sankaku', 'lachlan-giles', 'transition'],
  },
  {
    name: 'Lachlan Giles Half Guard - Knee Shield Plan',
    position: 'half-guard',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Systematic knee shield half guard with decision tree: if opponent pressures, underhook and sweep; if they back away, enter SLX or K-guard; if they crossface, ghost to deep half.',
    tags: ['lachlan-giles', 'half-guard', 'knee-shield', 'decision-tree'],
  },
  {
    name: 'Guard Retention - Frame Hierarchy',
    position: 'guard',
    category: 'guard-retention',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Lachlan Giles guard retention system: feet first (feet on hips), then knees (knee shield), then hands (frames on shoulders/biceps). Progressive frame hierarchy as passer closes distance.',
    tags: ['guard-retention', 'lachlan-giles', 'frames', 'hierarchy'],
  },
  {
    name: 'Body Lock Pass - Lachlan Giles Details',
    position: 'guard',
    category: 'pass',
    gi_nogi: 'nogi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Body lock passing with emphasis on hip positioning and angle. Drive opponents knees to one side, step over to establish side control. Methodical, heavy, unstoppable.',
    tags: ['body-lock', 'lachlan-giles', 'pressure-pass', 'nogi'],
  },
  {
    name: 'Submission Defense Systematic Approach',
    position: 'other',
    category: 'escape',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Lachlan Giles submission defense system: early defense (prevent the grip), middle defense (fight the position), late defense (survive and escape the locked submission). Applied to all major submissions.',
    tags: ['lachlan-giles', 'defense', 'escape', 'system'],
  },
  {
    name: 'Deep Half to Waiter Sweep',
    position: 'half-guard',
    category: 'sweep',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'From deep half, underhook the far leg, extend the trapped leg upward in waiter position, kick through for the sweep. Lachlan Giles half guard anthology technique.',
    tags: ['deep-half', 'waiter-sweep', 'lachlan-giles', 'half-guard'],
  },

  // ══════════════════════════════════════════════════════════
  // JOHN DANAHER — EXPANDED SYSTEMS
  // ══════════════════════════════════════════════════════════
  {
    name: 'Danaher Straight Jacket System - Step 1: Seatbelt',
    position: 'back',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Step 1 of Danaher back attack system. Establish seatbelt with choking arm over shoulder, support arm under armpit. Chest-to-back connection.',
    tags: ['danaher', 'straight-jacket', 'back', 'system'],
  },
  {
    name: 'Danaher Straight Jacket - Step 2: Trapping the Arm',
    position: 'back',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Step 2: Use the choking arm to trap opponents defending arm across their body. Creates a straight jacket effect where one arm controls both of opponents arms.',
    tags: ['danaher', 'straight-jacket', 'back', 'arm-trap'],
  },
  {
    name: 'Danaher Triangle System - Front Triangle',
    position: 'guard',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Danaher system front triangle: isolate one arm, shoot hips high, lock triangle, cut the angle 30 degrees. Emphasis on perpendicular angle for maximum squeeze.',
    tags: ['danaher', 'triangle', 'system', 'guard'],
  },
  {
    name: 'Danaher Armbar System - Speed Armbar',
    position: 'guard',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Fast armbar relying on speed and surprise. Shoot legs up quickly to catch the arm before opponent can pull out. Best from high guard or mount.',
    tags: ['danaher', 'armbar', 'speed', 'system'],
  },
  {
    name: 'Danaher Armbar System - Control Armbar',
    position: 'mount',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Slow, methodical armbar. Isolate the arm, pin the wrist, control the head, then transition to armbar position with complete control. Cannot be escaped.',
    tags: ['danaher', 'armbar', 'control', 'system'],
  },
  {
    name: 'Danaher Pin Escapes - Positional Hierarchy',
    position: 'side-control',
    category: 'escape',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Danaher system for escaping pins: create frames, generate movement, reinsert guard. Priority system for escaping side control, mount, and knee on belly.',
    tags: ['danaher', 'escape', 'pin-escape', 'system'],
  },
  {
    name: 'Feet to Floor - Standing Methodology',
    position: 'standing',
    category: 'takedown',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Danaher standing system: stance, motion, hand fighting, level change. Systematic approach to getting the fight to the ground where jiu-jitsu happens.',
    tags: ['danaher', 'feet-to-floor', 'standing', 'takedown'],
  },
  {
    name: 'Go Further Faster - Half Guard Bottom',
    position: 'half-guard',
    category: 'sweep',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Danaher Go Further Faster half guard system. Simplified half guard with focus on underhook, knee shield, and 3 primary sweeps for beginners to intermediate.',
    tags: ['danaher', 'go-further-faster', 'half-guard', 'fundamentals'],
  },
  {
    name: 'Cross Ashi Garami',
    position: 'guard',
    category: 'control',
    gi_nogi: 'nogi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Leg entanglement where your legs cross over opponents trapped leg. Creates outside heel hook and toe hold opportunities. Danaher system position.',
    tags: ['danaher', 'cross-ashi', 'leg-lock', 'control'],
  },
  {
    name: 'Outside Ashi to Inside Sankaku Transition',
    position: 'guard',
    category: 'transition',
    gi_nogi: 'nogi',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'When opponent defends outside ashi by freeing their knee, transition to inside sankaku by threading your legs into the triangle. Danaher system flow.',
    tags: ['danaher', 'ashi-transition', 'leg-lock', 'inside-sankaku'],
  },

  // ══════════════════════════════════════════════════════════
  // GREG SOUDERS — CLA METHODOLOGY
  // ══════════════════════════════════════════════════════════
  {
    name: 'CLA Invariant: Hip Escape as Movement Solution',
    position: 'other',
    category: 'escape',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Greg Souders CLA concept: hip escape as a fundamental movement invariant that emerges across all escape positions. Not taught as a technique but as a movement solution discovered through constrained practice.',
    tags: ['cla', 'greg-souders', 'invariant', 'movement', 'ecological-dynamics'],
  },
  {
    name: 'CLA Invariant: Frame Creation',
    position: 'other',
    category: 'guard-retention',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'CLA principle: framing as an emergent behavior that develops across all positions. Bone-on-bone structure to manage distance. Discovered through constraint games rather than explicit instruction.',
    tags: ['cla', 'greg-souders', 'invariant', 'frames', 'ecological-dynamics'],
  },
  {
    name: 'CLA Invariant: Off-Balancing (Kuzushi)',
    position: 'other',
    category: 'sweep',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Greg Souders CLA concept: off-balancing as a fundamental invariant present in all sweeps and throws. Push-pull principle discovered through constrained games where students must move opponents center of gravity.',
    tags: ['cla', 'greg-souders', 'invariant', 'kuzushi', 'off-balance'],
  },
  {
    name: 'Representative Learning Design',
    position: 'other',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'CLA concept: design practice tasks that preserve the key information sources of the competitive environment. Games should mirror match conditions while simplifying to isolate key skills.',
    tags: ['cla', 'greg-souders', 'representative-learning', 'ecological-dynamics'],
  },
  {
    name: 'Task Constraint Manipulation',
    position: 'other',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'CLA principle: change the rules of a game to shape behavior. Examples: only sweeps allowed, must maintain contact, no grips above waist. Constraints guide students to discover movement solutions.',
    tags: ['cla', 'greg-souders', 'task-constraint', 'methodology'],
  },

  // ══════════════════════════════════════════════════════════
  // MARCELO GARCIA SYSTEMS
  // ══════════════════════════════════════════════════════════
  {
    name: 'Marcelotine (Marcelo Garcia Guillotine)',
    position: 'guard',
    category: 'submission',
    gi_nogi: 'nogi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Marcelo Garcia signature guillotine variation. High wrist, arm-in, chin strap grip with emphasis on pulling guard and crunching. Highest percentage guillotine variation.',
    tags: ['marcelo-garcia', 'guillotine', 'marcelotine', 'submission'],
  },
  {
    name: 'Marcelo Garcia North-South Choke Details',
    position: 'side-control',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Marcelo Garcia specific details: transition to north-south, trap the arm, lock the head, walk hips away for the squeeze. Focus on chest pressure and proper arm positioning.',
    tags: ['marcelo-garcia', 'north-south', 'choke', 'details'],
  },
  {
    name: 'Arm Drag from Seated Guard',
    position: 'open-guard',
    category: 'transition',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Marcelo Garcia signature move. Two-on-one from seated guard, drag opponents arm across, come up to the back or take single leg. Foundation of his entire game.',
    tags: ['marcelo-garcia', 'arm-drag', 'seated-guard', 'back-take'],
  },
  {
    name: 'X-Guard Technical Standup Sweep',
    position: 'open-guard',
    category: 'sweep',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'From X-guard, elevate opponent, then technical standup to single leg finish. Marcelo Garcia primary X-guard finish. High percentage and safe.',
    tags: ['marcelo-garcia', 'x-guard', 'sweep', 'technical-standup'],
  },
  {
    name: 'X-Guard Back Door Sweep',
    position: 'open-guard',
    category: 'sweep',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'From X-guard, kick out the far leg while pulling the near leg. Opponent falls forward. Come up behind for back take or top position.',
    tags: ['marcelo-garcia', 'x-guard', 'back-door', 'sweep'],
  },
  {
    name: 'Guillotine from Guard Pull',
    position: 'standing',
    category: 'submission',
    gi_nogi: 'nogi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Snap opponents head down while pulling guard, lock guillotine during the transition. Marcelo Garcia signature move that catches people in the scramble.',
    tags: ['marcelo-garcia', 'guillotine', 'guard-pull', 'transition'],
  },

  // ══════════════════════════════════════════════════════════
  // BERNARDO FARIA — PRESSURE PASSING
  // ══════════════════════════════════════════════════════════
  {
    name: 'Over-Under Pass (Bernardo Faria)',
    position: 'guard',
    category: 'pass',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Bernardo Faria signature: one arm over the leg, one under. Drive shoulder into opponents hip, walk around slowly with heavy pressure. Patient, relentless passing.',
    tags: ['bernardo-faria', 'over-under', 'pressure-pass', 'signature'],
  },
  {
    name: 'Double Under Pass (Stack)',
    position: 'guard',
    category: 'pass',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Get double underhooks on both legs, stack opponent on their shoulders, walk around for the pass. Classic pressure pass.',
    tags: ['double-under', 'stack-pass', 'pressure-pass'],
  },

  // ══════════════════════════════════════════════════════════
  // MODERN TECHNIQUES — ADDITIONAL
  // ══════════════════════════════════════════════════════════
  {
    name: 'Bodylock Guard (Williams Guard)',
    position: 'closed-guard',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'Lock a body lock around opponents torso from closed guard. Creates extreme breaking of posture and entries to triangle, armbar, and back takes.',
    tags: ['williams-guard', 'bodylock-guard', 'closed-guard', 'control'],
  },
  {
    name: 'Rubber Guard - Mission Control',
    position: 'closed-guard',
    category: 'control',
    gi_nogi: 'nogi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: '10th Planet system. Overhook the head with your leg from closed guard. Controls posture completely. Entry to gogoplata, omoplata, and invisible collar.',
    tags: ['rubber-guard', '10th-planet', 'mission-control', 'flexible'],
  },
  {
    name: 'Coyote Half Guard',
    position: 'half-guard',
    category: 'sweep',
    gi_nogi: 'nogi',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'Underhook from half guard with opponent sprawled. Thread arm deep, elevate with butterfly hook, come to dog fight or directly to back. Modern half guard innovation.',
    tags: ['coyote', 'half-guard', 'underhook', 'modern'],
  },
  {
    name: 'Mikey Musumeci Butterfly Guard',
    position: 'open-guard',
    category: 'sweep',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Mikey Musumeci style butterfly guard. Extreme hip activity, constant elevation attempts, immediate RDLR transitions when opponent posts. Relentless bottom game.',
    tags: ['mikey-musumeci', 'butterfly', 'sweep', 'active-guard'],
  },
  {
    name: 'Berimbolo',
    position: 'open-guard',
    category: 'transition',
    gi_nogi: 'both',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'Inversion from DLR to take the back. Roll under opponent using DLR hook as lever. Modern gi technique that changed competition BJJ.',
    tags: ['berimbolo', 'dlr', 'back-take', 'modern', 'inversion'],
  },
  {
    name: 'Kiss of the Dragon',
    position: 'open-guard',
    category: 'transition',
    gi_nogi: 'both',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'From RDLR, invert between opponents legs and come out the back side for back take. Named by the Mendes brothers. High-level back take.',
    tags: ['kiss-of-dragon', 'rdlr', 'back-take', 'inversion', 'mendes'],
  },
  {
    name: 'Sit-Up Guard (Craig Jones Style)',
    position: 'open-guard',
    category: 'control',
    gi_nogi: 'nogi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Active sit-up guard with collar tie and wrist control. Threaten single legs, arm drags, and guillotines. Force opponent to deal with your forward pressure from bottom.',
    tags: ['sit-up-guard', 'craig-jones', 'nogi', 'active-guard'],
  },
  {
    name: 'Collar Drag Takedown',
    position: 'standing',
    category: 'takedown',
    gi_nogi: 'gi',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Cross collar grip, snap opponent forward and down while stepping to the side. Simple gi takedown that leads to front headlock or back take.',
    tags: ['gi', 'takedown', 'collar-drag'],
  },
  {
    name: 'Wrestling Standup (Technical Standup)',
    position: 'open-guard',
    category: 'escape',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Technical standup from seated guard or bottom position. Post hand, kick leg through, stand up maintaining guard against opponent. Fundamental wrestling-for-BJJ skill.',
    tags: ['technical-standup', 'wrestling', 'escape', 'fundamentals'],
  },
  {
    name: 'Nicky Rod Style Wrestling for BJJ',
    position: 'standing',
    category: 'takedown',
    gi_nogi: 'nogi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Explosive wrestling adapted for nogi BJJ. Heavy hands, snatch single, run the pipe, chain to body lock. Athletic, pressure-based standup game.',
    tags: ['nicky-rod', 'wrestling', 'takedown', 'explosive'],
  },
  {
    name: 'Gordon Ryan Head & Arm Control from Mount',
    position: 'mount',
    category: 'control',
    gi_nogi: 'nogi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Head and arm control from mount. Trap the head and arm together, create arm triangle threat which forces opponent to give up the back or get submitted.',
    tags: ['gordon-ryan', 'mount', 'head-arm', 'control'],
  },
  {
    name: 'Leg Drag to Back Take',
    position: 'guard',
    category: 'transition',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'From leg drag position, opponent turns away giving access to the back. Thread seatbelt, insert hooks. One of the highest percentage back take entries.',
    tags: ['leg-drag', 'back-take', 'transition', 'modern'],
  },
  {
    name: 'Knee on Belly',
    position: 'side-control',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Place knee on opponents belly from side control. Creates immense pressure and opens armbar, collar choke, and baseball bat opportunities. Score 2 points in IBJJF.',
    tags: ['knee-on-belly', 'control', 'pressure', 'competition'],
  },
  {
    name: 'Heel Hook Defense - Boot',
    position: 'guard',
    category: 'escape',
    gi_nogi: 'nogi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Primary heel hook defense: straighten the leg and point toes like a ballet boot. Prevents opponent from cupping the heel. Must be drilled to instinct.',
    tags: ['heel-hook-defense', 'boot', 'leg-lock-defense', 'essential'],
  },
  {
    name: 'Heel Hook Defense - Hitchhiker Escape',
    position: 'guard',
    category: 'escape',
    gi_nogi: 'nogi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'When caught in heel hook, turn toward the attacking leg (hitchhiker direction) to relieve rotational pressure on the knee. Clear the legs and extract.',
    tags: ['heel-hook-defense', 'hitchhiker', 'leg-lock-defense', 'escape'],
  },
  {
    name: 'Von Flue Choke',
    position: 'side-control',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Counter to opponents guillotine when you pass to side control. Drive shoulder into the neck, post on far side, squeeze. Punishes lazy guillotine attempts.',
    tags: ['von-flue', 'counter', 'choke', 'side-control'],
  },
  {
    name: 'Arm Drag from Standing (Marcelo Garcia)',
    position: 'standing',
    category: 'takedown',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Marcelo Garcia standing arm drag: two-on-one, explosive pull past your hip, circle behind for back take or single leg. Works gi and nogi.',
    tags: ['marcelo-garcia', 'arm-drag', 'standing', 'back-take'],
  },
  {
    name: 'Knee Tap Takedown',
    position: 'standing',
    category: 'takedown',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'From collar tie, push opponents head to one side while tapping the near knee. Low energy, low risk takedown. Effective at all levels.',
    tags: ['knee-tap', 'takedown', 'low-risk'],
  },
  {
    name: 'Pendulum Sweep from Closed Guard',
    position: 'closed-guard',
    category: 'sweep',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Open guard to one side, swing leg like a pendulum to generate momentum, sweep opponent over. Chains to armbar and triangle.',
    tags: ['pendulum', 'sweep', 'closed-guard'],
  },
  {
    name: 'Electric Chair Sweep',
    position: 'half-guard',
    category: 'sweep',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'From lockdown half guard, underhook opponents far leg, elevate with lockdown power and sweep to top. 10th Planet system signature move.',
    tags: ['electric-chair', 'lockdown', '10th-planet', 'half-guard'],
  },
  {
    name: 'Truck Position',
    position: 'back',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Control position with twister hook (lockdown on one leg from back). Creates calf slicer, twister, and back take opportunities. 10th Planet system.',
    tags: ['truck', '10th-planet', 'back', 'control'],
  },
  {
    name: 'Buggy Choke',
    position: 'side-control',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'Triangle choke from bottom side control using the legs. Thread near leg over opponents neck, figure-four with far leg. Modern innovation.',
    tags: ['buggy-choke', 'side-control', 'modern', 'submission'],
  },
  {
    name: 'Calf Slicer',
    position: 'guard',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'Compression lock on the calf. Triangle your legs around opponents leg with your shin behind their calf. Pull foot to compress. Available from many positions.',
    tags: ['calf-slicer', 'leg-lock', 'compression', 'submission'],
  },
  {
    name: 'Dogbar (Calf Slicer from Back)',
    position: 'back',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'Calf slicer applied from back control when opponent straightens their leg. Body triangle variation locks the calf slicer naturally.',
    tags: ['dogbar', 'calf-slicer', 'back', 'submission'],
  },
  {
    name: 'Inside Heel Hook from 50/50',
    position: 'guard',
    category: 'submission',
    gi_nogi: 'nogi',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'From 50/50, control the heel, clear the knee line, finish inside heel hook. Primary attacking option in modern 50/50.',
    tags: ['heel-hook', '50-50', 'leg-lock', 'submission'],
  },
  {
    name: 'SLX Sweep to Leg Drag',
    position: 'open-guard',
    category: 'sweep',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'From single leg X, sweep opponent forward, come up with the leg and transition to leg drag passing position. Connects guard and passing.',
    tags: ['slx', 'sweep', 'leg-drag', 'transition'],
  },
  {
    name: 'Butterfly Guard - Snap Down Guillotine',
    position: 'open-guard',
    category: 'submission',
    gi_nogi: 'nogi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'From butterfly guard, snap opponents head down and lock up guillotine. When butterfly sweep fails, the guillotine is the backup plan.',
    tags: ['butterfly', 'guillotine', 'snap-down', 'submission-chain'],
  },
  {
    name: 'Shin-to-Shin to Single Leg',
    position: 'open-guard',
    category: 'sweep',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'From seated guard, establish shin-to-shin contact, come up to a single leg takedown. Transitions from guard to wrestling seamlessly.',
    tags: ['shin-to-shin', 'single-leg', 'guard-to-wrestling'],
  },
  {
    name: 'Collar Sleeve to Triangle',
    position: 'open-guard',
    category: 'submission',
    gi_nogi: 'gi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'From collar sleeve guard, pull sleeve across while shooting hips up for triangle. Classic gi guard attack. Foot on hip pushes opponent into range.',
    tags: ['collar-sleeve', 'triangle', 'gi-guard', 'submission'],
  },
  {
    name: 'DLR to Baby Bolo Back Take',
    position: 'open-guard',
    category: 'transition',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'From DLR, partial inversion (baby berimbolo) to take the back without fully inverting. Simplified version of the berimbolo for less flexible grapplers.',
    tags: ['dlr', 'baby-bolo', 'back-take', 'simplified'],
  },
  {
    name: 'Whizzer Counter to Single Leg',
    position: 'clinch',
    category: 'escape',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'Overhook (whizzer) defense when opponent shoots single leg. Drive hip into them, circle to the back, or sprawl and apply pressure.',
    tags: ['whizzer', 'defense', 'single-leg-counter', 'clinch'],
  },
  {
    name: 'Reverse Half Guard (Deep Half)',
    position: 'half-guard',
    category: 'control',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Deep half guard where you are completely under opponents base. Control the far leg, elevate for sweeps. Extremely difficult to pass once established.',
    tags: ['deep-half', 'reverse-half', 'control', 'sweep-position'],
  },
  {
    name: 'Leg Weave Pass',
    position: 'guard',
    category: 'pass',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Weave your arm through opponents legs, controlling one leg while passing to the other side. Effective against DLR and open guard.',
    tags: ['leg-weave', 'guard-pass', 'dlr-counter'],
  },
  {
    name: 'Smash Pass',
    position: 'half-guard',
    category: 'pass',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'From half guard top, flatten opponents knee shield, drive shoulder into jaw, crossface and slowly extract the leg. Pure pressure.',
    tags: ['smash-pass', 'pressure-pass', 'half-guard'],
  },
  {
    name: 'Backstep Pass',
    position: 'guard',
    category: 'pass',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Step back leg behind opponents guard, clearing the legs. Creates a passing lane while also exposing leg lock entries. Dual-threat pass.',
    tags: ['backstep', 'guard-pass', 'leg-lock-entry'],
  },
  {
    name: 'Imanari Roll to Leg Entanglement',
    position: 'standing',
    category: 'transition',
    gi_nogi: 'nogi',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'Rolling entry from standing directly into ashi garami or inside sankaku. Named after Masakazu Imanari. High-risk, high-reward leg lock entry.',
    tags: ['imanari-roll', 'leg-lock-entry', 'standing', 'advanced'],
  },
  {
    name: 'Estima Lock (Foot Lock)',
    position: 'guard',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'purple',
    belt_level_max: 'black',
    description: 'Foot lock from a passing position. Trap the foot in your armpit, rotate against the ankle joint. Named after the Estima brothers. Catches people off guard.',
    tags: ['estima-lock', 'foot-lock', 'submission'],
  },
  {
    name: 'Peterson Roll from Turtle',
    position: 'turtle',
    category: 'escape',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Wrestling escape from turtle. Reach back, grab opponents arm or leg, roll through to end up on top or in guard. Named after wrestler Ben Peterson.',
    tags: ['peterson-roll', 'turtle', 'escape', 'wrestling'],
  },
  {
    name: 'Clock Choke',
    position: 'turtle',
    category: 'submission',
    gi_nogi: 'gi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Gi choke from turtle. Cross collar grip, walk around (like a clock) tightening the choke. Classic turtle attack in the gi.',
    tags: ['clock-choke', 'gi', 'turtle', 'choke'],
  },
  {
    name: 'Arm Triangle from Mount',
    position: 'mount',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'From mount, force opponents arm across their neck, lock head and arm triangle. Slide to side control to finish. Very high percentage from mount.',
    tags: ['arm-triangle', 'mount', 'choke', 'submission'],
  },
  {
    name: 'Darce from Half Guard Top',
    position: 'half-guard',
    category: 'submission',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'When opponent underhooks from half guard bottom, thread arm under their neck for d\'arce. Common counter to the underhook game.',
    tags: ['darce', 'half-guard', 'counter', 'choke'],
  },
  {
    name: 'Running Escape from Side Control',
    position: 'side-control',
    category: 'escape',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'Turn away from opponent in side control, create space, and come up to turtle or standing. Alternative escape when standard reguard is blocked.',
    tags: ['running-escape', 'side-control', 'escape'],
  },
  {
    name: 'Knee Cut to Mount',
    position: 'half-guard',
    category: 'pass',
    gi_nogi: 'both',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'After clearing knee cut, instead of settling in side control, immediately transition to mount. Skip side control entirely for a more dominant position.',
    tags: ['knee-cut', 'mount-transition', 'pass-to-mount'],
  },
  {
    name: 'Butterfly Guard to Guillotine Chain',
    position: 'open-guard',
    category: 'submission',
    gi_nogi: 'nogi',
    belt_level_min: 'blue',
    belt_level_max: 'black',
    description: 'From butterfly guard: if sweep works, come up top; if blocked, arm drag to back; if they posture, snap down to guillotine. Complete decision tree from butterfly.',
    tags: ['butterfly', 'chain', 'guillotine', 'decision-tree'],
  },
  {
    name: 'Guard Recovery from Turtle',
    position: 'turtle',
    category: 'escape',
    gi_nogi: 'both',
    belt_level_min: 'white',
    belt_level_max: 'black',
    description: 'From turtle, sit through to seated guard or granby roll to recover full guard. Priority is always to get back to a guard position rather than staying in turtle.',
    tags: ['turtle-to-guard', 'escape', 'guard-recovery', 'fundamentals'],
  },
]
